packages:
  - "packages/*"
allowBuilds:
  esbuild: true
  core-js: true
minimumReleaseAgeExclude:
  - '@vitest/coverage-v8@5.0.2'
  - '@vitest/mocker@5.0.2'
  - '@vitest/spy@5.0.2'
  - vitest@5.0.2
  - vscode-jsonrpc@9.0.3
  - vscode-languageclient@10.1.2
  - vscode-languageserver-protocol@3.18.4
  - vscode-languageserver-types@3.18.4
  - vscode-languageserver@10.1.2
