export { parse } from "./parse.ts";
// stripTypes 单源在 core（parser 依赖 core，避免双份拷贝漂移）
export { stripTypes } from "@nudojs/core";
export {
  asProgram,
  programBody,
  asIdentifier,
  asExpression,
  asAssignmentExpression,
  asMemberExpression,
  nameOrStringValue,
  identifierName,
  getDeclarations,
  getDeclaratorInit,
  getDeclaratorId,
  getFirstDeclaratorId,
  getExportDeclaration,
  unwrapExport,
  getExportSpecifiers,
  exportSpecifierLocalName,
  exportSpecifierExportedName,
  getExpressionStatementExpression,
  fnOrClassIdName,
  classIdName,
  fnOrClassIdLoc,
  memberPropertyKey,
  memberObjectName,
  memberPropertyName,
  isModuleExportsMember,
  getClassMembers,
  classMemberKeyName,
  classMemberKey,
  classInstanceMethods,
  methodFunctionNode,
  paramDisplayName,
  paramName,
  unwrapDefaultExport,
  type InstanceMethod,
} from "./ast-guards.ts";
export {
  type Directive,
  type FileDirective,
  type InlineDirective,
  type AsDirective,
  type ReplaceDirective,
  type CaseDirective,
  type MockDirective,
  type PureDirective,
  type SkipDirective,
  type SampleDirective,
  type EnvDirective,
  type MockModuleDirective,
  type FunctionWithDirectives,
  type SinonExpression,
  extractDirectives,
  extractFileDirectives,
  extractInlineDirectives,
  parseCaseArgExpr,
} from "./directives.ts";
