export { parse } from "./parse.ts";
// 解析/剥除实现单源在 core（core 代数需要 AST，不能依赖本包）。
// 本包产品职责是 @nudo: 指令抽取；此处 re-export 供宿主一条入口拿全。
export { stripTypes } from "@nudojs/core";
export {
  asProgram,
  programBody,
  asIdentifier,
  asExpression,
  asAssignmentExpression,
  asMemberExpression,
  nameOrStringValue,
  identifierName,
  getDeclarations,
  getDeclaratorInit,
  getDeclaratorId,
  getFirstDeclaratorId,
  getExportDeclaration,
  unwrapExport,
  getExportSpecifiers,
  exportSpecifierLocalName,
  exportSpecifierExportedName,
  getExpressionStatementExpression,
  fnOrClassIdName,
  classIdName,
  fnOrClassIdLoc,
  memberPropertyKey,
  memberObjectName,
  memberPropertyName,
  isModuleExportsMember,
  getClassMembers,
  classMemberKeyName,
  classMemberKey,
  classInstanceMethods,
  methodFunctionNode,
  paramDisplayName,
  paramName,
  unwrapDefaultExport,
  type InstanceMethod,
} from "./ast-guards.ts";
export {
  type Directive,
  type FileDirective,
  type InlineDirective,
  type AsDirective,
  type ReplaceDirective,
  type CaseDirective,
  type MockDirective,
  type PureDirective,
  type SkipDirective,
  type SampleDirective,
  type EnvDirective,
  type MockModuleDirective,
  type FunctionWithDirectives,
  type SinonExpression,
  extractDirectives,
  extractFileDirectives,
  extractInlineDirectives,
  parseCaseArgExpr,
} from "./directives.ts";
