export { parse } from "./parse.ts";
// 解析/剥除实现单源在 core（core 代数需要 AST，不能依赖本包）。
// 本包产品职责是 @nudo: 指令抽取；此处 re-export 供宿主一条入口拿全。
export { stripTypes } from "@nudojs/core";
export {
  asProgram,
  programBody,
  asIdentifier,
  asExpression,
  asAssignmentExpression,
  asMemberExpression,
  nameOrStringValue,
  identifierName,
  getDeclarations,
  getDeclaratorInit,
  getDeclaratorId,
  getFirstDeclaratorId,
  getExportDeclaration,
  unwrapExport,
  getExportSpecifiers,
  exportSpecifierLocalName,
  exportSpecifierExportedName,
  getExpressionStatementExpression,
  fnOrClassIdName,
  classIdName,
  fnOrClassIdLoc,
  memberPropertyKey,
  memberObjectName,
  memberPropertyName,
  isModuleExportsMember,
  getClassMembers,
  classMemberKeyName,
  classMemberKey,
  classInstanceMethods,
  methodFunctionNode,
  paramDisplayName,
  paramName,
  unwrapDefaultExport,
  type InstanceMethod,
} from "./ast-guards.ts";
export {
  type Directive,
  type FileDirective,
  type InlineDirective,
  type AsDirective,
  type ReplaceDirective,
  type CaseDirective,
  type MockDirective,
  type PureDirective,
  type SkipDirective,
  type SampleDirective,
  type EnvDirective,
  type MockModuleDirective,
  type FunctionWithDirectives,
  type SinonExpression,
  type DirectiveDiag,
  type ExtractDirectivesOpts,
  extractDirectives,
  extractDirectivesQuiet,
  extractFileDirectives,
  extractInlineDirectives,
  parseCaseArgExpr,
  setDirectiveDiagCollector,
  takeDirectiveDiags,
  takeDirectiveDiagsSince,
  directiveDiagCount,
} from "./directives.ts";

// D5=F1：指令抽取单源 API 的产品面 re-export（实现住 core directive-scan，
// parser 依赖 core，反向会成包环）。core/nudojs 只消费这些 API。
export {
  type CaseTag,
  type FnDirectiveScope,
  type MockModuleRecord,
  type NudoImportRecord,
  extractFileEnvNames,
  extractMockModuleRecords,
  extractNudoImportRecords,
  findFnDirectiveScope,
  fnDirectiveCommentLines,
  listFnDirectiveScopes,
  parseEnvPayload,
  parseMockModulePayload,
  parseNudoImportPayload,
  scanBudgetDecl,
  scanCaseTags,
  scanContractSegments,
  scanThrowsDecl,
} from "@nudojs/core";
