/**
 * B 路径运行时：transpile 后的程序在 Node 上执行时，值就是 Abs。
 * 与 AST 解释器语义同构；TypeValue 不再是求值载体。
 *
 * 实现按域拆在 runtime/*.ts；本文件是 re-export facade。
 * **只**再导出原有公开符号面（public-api.snapshot.json 冻结）；
 * 拆分产生的内部符号从 runtime/* 深路径可见，但不进 facade。
 */
export {
  $fnVal,
  $isBreakTo,
  $lit,
  $loopBreak,
  $loopContinue,
  $loopReturn,
  $pushLoopExit,
  $rawThis,
  $rethrowIfNudoReturn,
  $tryCurrentMark,
  $tryDetachSoftCatch,
  $tryDigestSoftCatch,
  $tryDiscardSoft,
  $tryMark,
  $tryOrphanSoft,
  $tryPopMark,
  $tryReleaseSoftCatch,
  $tryReleaseSoftOut,
  $tryTakeSince,
  NudoLoopSignal,
  NudoReturn,
  NudoThrow,
  asAbsVal,
  callAtFunctionBoundary,
  clearStaleTermPred,
  currentExecPhi,
  isDefinitelyFalse,
  isDefinitelyTrue,
  isNudoBreak,
  isNudoContinue,
  isNudoReturn,
  isNudoThrow,
  litTruth,
  pushLoopExit,
  pushThrowExit,
  runWithLoopExits,
  takeLoopExits,
  takeThrowExits,
  withExecPhi,
} from "./runtime/state.ts";
export {
  $add,
  $bitand,
  $bitnot,
  $bitor,
  $bitxor,
  $div,
  $dynamicImport,
  $eq,
  $eqLoose,
  $ge,
  $gt,
  $importMeta,
  $join,
  $le,
  $lt,
  $mod,
  $mul,
  $ne,
  $neLoose,
  $neg,
  $not,
  $pow,
  $shl,
  $shr,
  $sub,
  $toNumber,
  $typeof,
  $unknown,
  $ushr,
} from "./runtime/ops.ts";
export {
  $classExpr,
  $del,
  $delRes,
  $in,
  $instanceof,
  $instanceofNonIdent,
  $objAccessor,
  lookupObjAccessor,
} from "./runtime/members.ts";
export {
  $catchVal,
  $for,
  $forIter,
  $fork,
  $isForkExit,
  $switch,
  $throw,
  $while,
  $whileSeq,
  DEFAULT_MAX_LOOP_ITERS,
} from "./runtime/control.ts";
export {
  $arguments,
  $arr,
  $arrMutContainer,
  $arrRest,
  $arrWithHoles,
  $collectionForEach,
  $concat,
  $copy,
  $elems,
  $forInKeys,
  $forOf,
  $get,
  $idx,
  $idxSet,
  $len,
  $obj,
  $objRest,
  $regex,
  $set,
  $spread,
  fillTuple,
  isArrMutator,
  namespaceNameOf,
} from "./runtime/containers.ts";
export {
  $async,
  $asyncReturn,
  $await,
  $gen,
  $nullishTest,
  $yield,
} from "./runtime/async.ts";
