/**
 * interface 档 LSP 表面（design-refine-derivation §7.5/§8 / Phase 1 T11）：
 * - nudo.interface 打印三来源（handwritten / generated / implicit）+ functionName 过滤
 * - nudo.interface.emit add/update 两模式 + name-clash 文本（与 CLI 同一写盘器）
 * - computeInterfaceLenses：默认层 / 固化动作 / case 副层排序 / 私有与无 interface 不加
 *
 * server.ts 在 vitest 下不可 import（createConnection 副作用），全部走
 * agent-tools.ts 导出面；打印/固化工具用真实临时目录夹具（interfaceSurface /
 * emitInterface 以磁盘为真值，与 CLI 路径一致），lens 计算用注入 loadModule 纯测。
 */
import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtempSync, writeFileSync, readFileSync, rmSync, existsSync, mkdirSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  interfaceTool,
  interfaceEmitTool,
  interfacePositionalArgs,
  interfaceEmitPositionalArgs,
  computeInterfaceLenses,
} from "../agent-tools.ts";

let dir: string;

beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), "nudo-agent-iface-"));
});

afterEach(() => {
  rmSync(dir, { recursive: true, force: true });
});

// ---------------------------------------------------------------------------
// nudo.interface 打印（interfaceSurface 数据源）
// ---------------------------------------------------------------------------

const SRC_JS = `
export function add(x) {
  return x + 2;
}
`;

const HANDWRITTEN_SIDECAR = `
import { fn, number } from "@nudojs/core";

export const add = fn({ x: number().gt(0) }, number().gt(2));
`;

const GENERATED_SIDECAR = `
import { fn, number } from "@nudojs/core";

// @generated by nudo — do not edit; regenerate with \`nudo interface --emit\`
export const add = fn({ x: number() });
`;

const CALLS_JS = `
export function double(x) {
  return x * 2;
}

double(21);
`;

describe("nudo.interface agent tool", () => {
  it("prints handwritten source with formatConstraint display", async () => {
    writeFileSync(join(dir, "src.js"), SRC_JS);
    writeFileSync(join(dir, "src.nudo.js"), HANDWRITTEN_SIDECAR);

    const r = await interfaceTool({ file: join(dir, "src.js") });
    const text = r.content[0].text;
    expect(text).toContain("add  [handwritten]  (x: number().gt(0)) → number().gt(2)");
    expect(text).toContain(JSON.stringify("handwritten")); // JSON tail 可机读
  });

  it("prints generated source when the sidecar segment is @generated", async () => {
    writeFileSync(join(dir, "src.js"), SRC_JS);
    writeFileSync(join(dir, "src.nudo.js"), GENERATED_SIDECAR);

    const r = await interfaceTool({ file: join(dir, "src.js") });
    expect(r.content[0].text).toContain("add  [generated]  (x: number())");
  });

  it("prints implicit source from call-site evidence without a sidecar", async () => {
    writeFileSync(join(dir, "calls.js"), CALLS_JS);

    const r = await interfaceTool({ file: join(dir, "calls.js") });
    expect(r.content[0].text).toContain("double  [implicit]  (x: 21) → 42");
  });

  it("filters by functionName and reports unknown names", async () => {
    writeFileSync(join(dir, "calls.js"), CALLS_JS);

    const hit = await interfaceTool({ file: join(dir, "calls.js"), functionName: "double" });
    expect(hit.content[0].text).toContain("double  [implicit]");
    expect(hit.content[0].text).not.toContain("no interface found");

    const miss = await interfaceTool({ file: join(dir, "calls.js"), functionName: "nope" });
    expect(miss.content[0].text).toContain("no interface found for 'nope'");
  });
});

// ---------------------------------------------------------------------------
// nudo.interface.emit 固化（emitInterface 同一写盘器）
// ---------------------------------------------------------------------------

const ADD_JS = `export function add2(x) {\n  return x + 2;\n}\n\nadd2(42);\n`;

const CLASH_SIDECAR = `
import { fn, number } from "@nudojs/core";

export const add2 = fn({ x: number().int() });
`;

describe("nudo.interface.emit agent tool", () => {
  it("add mode writes an @generated sidecar segment", async () => {
    const file = join(dir, "add.js");
    writeFileSync(file, ADD_JS);

    const r = await interfaceEmitTool({ file, functionName: "add2", mode: "add" });
    const text = r.content[0].text;
    expect(text).toContain("written: add2");
    expect(text).not.toContain("nudo:interface-name-clash");

    const sidecar = readFileSync(join(dir, "add.nudo.js"), "utf-8");
    expect(sidecar).toContain("// @generated by nudo — do not edit");
    expect(sidecar).toContain("export const add2 = fn({ x: lit(42) }, lit(44));");
  });

  it("update mode is idempotent (second run reports no change)", async () => {
    const file = join(dir, "add.js");
    writeFileSync(file, ADD_JS);

    await interfaceEmitTool({ file, functionName: "add2", mode: "add" });
    const again = await interfaceEmitTool({ file, functionName: "add2", mode: "update" });
    expect(again.content[0].text).toContain("no interface changes");
  });

  it("reports name-clash explicitly when the sidecar has a handwritten binding", async () => {
    const file = join(dir, "clash.js");
    writeFileSync(file, ADD_JS);
    const sidecarPath = join(dir, "clash.nudo.js");
    writeFileSync(sidecarPath, CLASH_SIDECAR);

    const r = await interfaceEmitTool({ file, functionName: "add2", mode: "add" });
    const text = r.content[0].text;
    expect(text).toContain("skipped add2 (name-clash)");
    expect(text).toContain("[error] nudo:interface-name-clash");
    expect(text).toContain("handwritten wins");

    // 手写绑定原样保留，不被生成段覆盖
    expect(readFileSync(sidecarPath, "utf-8")).toContain("fn({ x: number().int() })");
  });
});

// ---------------------------------------------------------------------------
// computeInterfaceLenses（CodeLens interface 档纯计算）
// ---------------------------------------------------------------------------

const LENS_SRC = `
export function add(x) {
  return x + 2;
}

function helper(n) {
  return n;
}
`;

const sidecarLoader = (sidecar: string) => (spec: string) =>
  spec.endsWith("lib.nudo.js") ? sidecar : undefined;

describe("computeInterfaceLenses", () => {
  it("handwritten export gets the default lens only (read-only, no persist lens)", () => {
    const lenses = computeInterfaceLenses(LENS_SRC, "/t/lib.js", {
      loadModule: sidecarLoader(HANDWRITTEN_SIDECAR),
    });
    expect(lenses).toEqual([
      { kind: "interface", fn: "add", line: 2, source: "handwritten" },
    ]);
  });

  it("persisted (@generated) export gets an update-mode emit lens + draft lens", () => {
    const lenses = computeInterfaceLenses(LENS_SRC, "/t/lib.js", {
      loadModule: sidecarLoader(GENERATED_SIDECAR),
    });
    expect(lenses).toEqual([
      { kind: "interface", fn: "add", line: 2, source: "generated" },
      { kind: "emit", fn: "add", line: 2, mode: "update" },
      { kind: "draft", fn: "add", line: 2 },
    ]);
  });

  it("implicit export gets an add-mode emit lens + draft; case lenses stay but rank behind", () => {
    const src = `
// @nudo:case "num" (42)
// @nudo:case "str" ("a")
export function withCase(x) {
  return x;
}

export function plain(x) {
  return x * 2;
}

// @nudo:case "h" (3)
function helper(n) {
  return n + 1;
}
`;
    const lenses = computeInterfaceLenses(src, "/t/plain.js");
    expect(lenses).toEqual([
      { kind: "interface", fn: "withCase", line: 4, source: "implicit" },
      { kind: "emit", fn: "withCase", line: 4, mode: "add" },
      { kind: "draft", fn: "withCase", line: 4 },
      { kind: "case", fn: "withCase", line: 4, caseIndex: 0, caseName: "num", active: true },
      { kind: "case", fn: "withCase", line: 4, caseIndex: 1, caseName: "str", active: false },
      { kind: "interface", fn: "plain", line: 8, source: "implicit" },
      { kind: "emit", fn: "plain", line: 8, mode: "add" },
      { kind: "draft", fn: "plain", line: 8 },
      // 私有函数：不进 interface 档（不绑定不落盘），case 副层原样保留
      { kind: "case", fn: "helper", line: 13, caseIndex: 0, caseName: "h", active: true },
    ]);
  });

  it("marks the active case via activeCases (index ≠ 0)", () => {
    const src = `\n// @nudo:case "a" (1)\n// @nudo:case "b" (2)\nexport function f(x) {\n  return x;\n}\n`;
    const lenses = computeInterfaceLenses(src, "/t/f.js", {
      activeCases: new Map([["f", 1]]),
    });
    const cases = lenses.filter((l) => l.kind === "case");
    expect(cases.map((c) => (c.kind === "case" ? c.active : null))).toEqual([false, true]);
  });

  it("adds no lenses for functions without an interface surface", () => {
    // 非函数导出 + 无 case 私有函数：无 lens；导出箭头函数进 interface 档
    const src = `\nexport const N = 1;\n\nfunction dead(n) {\n  return n;\n}\n\nexport const double = (x) => x * 2;\n`;
    const lenses = computeInterfaceLenses(src, "/t/misc.js");
    expect(lenses).toEqual([
      { kind: "interface", fn: "double", line: 8, source: "implicit" },
      { kind: "emit", fn: "double", line: 8, mode: "add" },
      { kind: "draft", fn: "double", line: 8 },
    ]);
  });

  it("no sidecar file → implicit source even with a loadModule channel", () => {
    const loader = (spec: string) => (spec.endsWith("lib.nudo.js") ? undefined : undefined);
    const lenses = computeInterfaceLenses(LENS_SRC, "/t/lib.js", { loadModule: loader });
    expect(lenses).toEqual([
      { kind: "interface", fn: "add", line: 2, source: "implicit" },
      { kind: "emit", fn: "add", line: 2, mode: "add" },
      { kind: "draft", fn: "add", line: 2 },
    ]);
    expect(existsSync("/t/lib.nudo.js")).toBe(false); // 注入通道不落盘
  });

  it("autoBind:false falls back to implicit even when a handwritten sidecar loads", () => {
    const lenses = computeInterfaceLenses(LENS_SRC, "/t/lib.js", {
      loadModule: sidecarLoader(HANDWRITTEN_SIDECAR),
      autoBind: false,
    });
    expect(lenses).toEqual([
      { kind: "interface", fn: "add", line: 2, source: "implicit" },
      { kind: "emit", fn: "add", line: 2, mode: "add" },
      { kind: "draft", fn: "add", line: 2 },
    ]);
  });
});

describe("interfaceEmitTool 入参校验（非法输入显式报错，不静默降级）", () => {
  it("invalid mode → explicit error text", async () => {
    const r = await interfaceEmitTool({
      file: "/t/x.js",
      functionName: "f",
      mode: "Add" as unknown as "add",
    });
    expect(r.content[0]!.text).toContain("invalid mode");
  });

  it("missing functionName → explicit error text", async () => {
    const r = await interfaceEmitTool({
      file: "/t/x.js",
      functionName: "",
      mode: "add",
    });
    expect(r.content[0]!.text).toContain("functionName is required");
  });

  it("valid params still reach the emitter (no sidecar file → clean no-change)", async () => {
    const file = join(dir, "ok.js");
    writeFileSync(file, `export function f(x) {\n  return x;\n}\n`);
    const r = await interfaceEmitTool({ file, functionName: "f", mode: "add" });
    expect(r.content[0]!.text).toContain("no interface changes");
  });

  it("rejects sidecar contract modules as emit targets", async () => {
    const r = await interfaceEmitTool({
      file: join(dir, "lib.nudo.js"),
      functionName: "f",
      mode: "add",
    });
    expect(r.content[0]!.text).toContain("not an analysis target");
  });

  it("rejects paths outside allowed workspace roots", async () => {
    writeFileSync(
      join(dir, "package.json"),
      JSON.stringify({ name: "proj", version: "1.0.0", nudo: {} }),
    );
    const outside = join(dir, "..", `nudo-outside-${process.pid}.js`);
    writeFileSync(outside, `export function f(x) {\n  return x;\n}\n`);
    try {
      const r = await interfaceEmitTool(
        { file: outside, functionName: "f", mode: "add" },
        { workspaceRoots: [dir] },
      );
      expect(r.content[0]!.text).toContain("outside allowed roots");
    } finally {
      rmSync(outside, { force: true });
    }
  });

  it("allows emit inside workspace roots", async () => {
    const file = join(dir, "inside.js");
    writeFileSync(file, `export function f(x) {\n  return x;\n}\nf(1);\n`);
    const r = await interfaceEmitTool(
      { file, functionName: "f", mode: "add" },
      { workspaceRoots: [dir] },
    );
    expect(r.content[0]!.text).not.toContain("outside allowed roots");
  });

  it("fail-closed when workspaceRoots is empty array", async () => {
    const file = join(dir, "orphan.js");
    writeFileSync(file, `export function f(x) {\n  return x;\n}\n`);
    const r = await interfaceEmitTool(
      { file, functionName: "f", mode: "add" },
      { workspaceRoots: [] },
    );
    expect(r.content[0]!.text).toContain("at least one workspace root");
  });

  it("rejects emit targets inside node_modules", async () => {
    const nm = join(dir, "node_modules", "pkg");
    mkdirSync(nm, { recursive: true });
    const file = join(nm, "index.js");
    writeFileSync(file, `export function f(x) {\n  return x;\n}\n`);
    const r = await interfaceEmitTool(
      { file, functionName: "f", mode: "add" },
      { workspaceRoots: [dir] },
    );
    expect(r.content[0]!.text).toContain("node_modules");
  });
});

describe("executeCommand 位置参数桥接（server.ts 特判的纯函数形态）", () => {
  it("interfacePositionalArgs: [uri] → 全量；[uri, fn] → 过滤", () => {
    expect(interfacePositionalArgs(["file:///t/a.js"])).toEqual({ file: "file:///t/a.js" });
    expect(interfacePositionalArgs(["file:///t/a.js", "scale"])).toEqual({
      file: "file:///t/a.js",
      functionName: "scale",
    });
    expect(interfacePositionalArgs([])).toBeUndefined();
    expect(interfacePositionalArgs([42])).toBeUndefined();
  });

  it("interfaceEmitPositionalArgs: [uri, fn, mode] 三串；非法形态 undefined", () => {
    expect(interfaceEmitPositionalArgs(["file:///t/a.js", "f", "update"])).toEqual({
      file: "file:///t/a.js",
      functionName: "f",
      mode: "update",
    });
    expect(interfaceEmitPositionalArgs(["file:///t/a.js", "f"])).toBeUndefined();
    expect(interfaceEmitPositionalArgs(["file:///t/a.js", "f", 7])).toBeUndefined();
  });
});
