/**
 * A7：semantic tokens 对齐 interface 档
 * - export 函数绑定带 contract / generated / derived modifier
 * - 非导出只带 declaration（不假装进档）
 * - 与 CodeLens / hover 共用 interfaceTierOf（同源）
 */
import { describe, it, expect } from "vitest";
import {
  buildSemanticTokens,
  SEMANTIC_TOKEN_TYPES,
  SEMANTIC_TOKEN_MODIFIERS,
  interfaceTierModifierBit,
} from "../semantic-tokens.ts";

const MOD_DECLARATION = 1 << SEMANTIC_TOKEN_MODIFIERS.indexOf("declaration");
const MOD_CONTRACT = 1 << SEMANTIC_TOKEN_MODIFIERS.indexOf("contract");
const MOD_GENERATED = 1 << SEMANTIC_TOKEN_MODIFIERS.indexOf("generated");
const MOD_DERIVED = 1 << SEMANTIC_TOKEN_MODIFIERS.indexOf("derived");

const TYPE_FUNCTION = SEMANTIC_TOKEN_TYPES.indexOf("function");

type Decoded = { line: number; char: number; length: number; typeIndex: number; modifiers: number };

function decode(data: number[]): Decoded[] {
  const out: Decoded[] = [];
  let line = 0;
  let char = 0;
  for (let i = 0; i < data.length; i += 5) {
    const [deltaLine, deltaChar, length, typeIndex, modifiers] = data.slice(i, i + 5);
    line += deltaLine;
    char = deltaLine === 0 ? char + deltaChar : deltaChar;
    out.push({ line, char, length, typeIndex, modifiers: modifiers! });
  }
  return out;
}

const HANDWRITTEN = `
import { fn, number } from "@nudojs/core";

export const add = fn({ x: number().gt(0) }, number().gt(2));
`;
const GENERATED = `
import { fn, number } from "@nudojs/core";

// @generated by nudo — do not edit; regenerate with \`nudo contract --emit\`
export const add = fn({ x: number() });
`;

const loader = (sidecar: string) => (spec: string) =>
  spec.endsWith("lib.nudo.js") ? sidecar : undefined;

describe("buildSemanticTokens × interface 档 (A7)", () => {
  it("handwritten export function declaration gets contract modifier", () => {
    const src = `export function add(x) {\n  return x + 2;\n}\n`;
    const data = buildSemanticTokens("/t/lib.js", src, { loadModule: loader(HANDWRITTEN) });
    const fnTok = decode(data).find(
      (t) => t.line === 0 && t.typeIndex === TYPE_FUNCTION && t.length === 3,
    );
    expect(fnTok).toBeDefined();
    expect(fnTok!.modifiers).toBe(MOD_DECLARATION | MOD_CONTRACT);
  });

  it("generated export gets generated modifier", () => {
    const src = `export function add(x) {\n  return x + 2;\n}\n`;
    const data = buildSemanticTokens("/t/lib.js", src, { loadModule: loader(GENERATED) });
    const fnTok = decode(data).find((t) => t.typeIndex === TYPE_FUNCTION && t.length === 3);
    expect(fnTok!.modifiers).toBe(MOD_DECLARATION | MOD_GENERATED);
  });

  it("implicit export gets derived modifier", () => {
    const src = `export function double(x) {\n  return x * 2;\n}\n`;
    const data = buildSemanticTokens("/t/calls.js", src);
    const fnTok = decode(data).find((t) => t.typeIndex === TYPE_FUNCTION && t.length === 6);
    expect(fnTok!.modifiers).toBe(MOD_DECLARATION | MOD_DERIVED);
  });

  it("non-export function keeps declaration-only modifier", () => {
    const src = `function helper(n) {\n  return n;\n}\n`;
    const data = buildSemanticTokens("/t/priv.js", src);
    const fnTok = decode(data).find((t) => t.typeIndex === TYPE_FUNCTION);
    expect(fnTok!.modifiers).toBe(MOD_DECLARATION);
  });

  it("nested same-name FunctionDeclaration does not inherit export interface tier", () => {
    const src = `export function add(x) {
  function add(n) {
    return n + 1;
  }
  return add(x) + 2;
}
`;
    const data = buildSemanticTokens("/t/lib.js", src, { loadModule: loader(HANDWRITTEN) });
    const fnToks = decode(data).filter((t) => t.typeIndex === TYPE_FUNCTION && t.length === 3);
    expect(fnToks.length).toBe(2);
    const top = fnToks.find((t) => t.line === 0)!;
    const nested = fnToks.find((t) => t.line === 1)!;
    expect(top.modifiers).toBe(MOD_DECLARATION | MOD_CONTRACT);
    expect(nested.modifiers).toBe(MOD_DECLARATION);
  });

  it("autoBind:false → derived even with handwritten sidecar", () => {
    const src = `export function add(x) {\n  return x + 2;\n}\n`;
    const data = buildSemanticTokens("/t/lib.js", src, {
      loadModule: loader(HANDWRITTEN),
      autoBind: false,
    });
    const fnTok = decode(data).find((t) => t.typeIndex === TYPE_FUNCTION && t.length === 3);
    expect(fnTok!.modifiers).toBe(MOD_DECLARATION | MOD_DERIVED);
  });

  it("interfaceTierModifierBit maps three tiers", () => {
    expect(interfaceTierModifierBit("handwritten")).toBe(MOD_CONTRACT);
    expect(interfaceTierModifierBit("generated")).toBe(MOD_GENERATED);
    expect(interfaceTierModifierBit("implicit")).toBe(MOD_DERIVED);
  });

  it("legend appends contract/generated/derived without reordering prior modifiers", () => {
    expect(SEMANTIC_TOKEN_MODIFIERS.slice(0, 4)).toEqual([
      "declaration",
      "readonly",
      "deprecated",
      "unreachable",
    ]);
    expect(SEMANTIC_TOKEN_MODIFIERS.slice(4)).toEqual(["contract", "generated", "derived"]);
  });
});
