/**
 * 宿主内建面覆盖地板·两级台账（配套 builtin-coverage-floor.test.ts）。
 *
 * 目的：防「未建模面静默漏网」——测试在运行时枚举 globalThis 自有名字 +
 * 策展 brand 的 `.prototype` / 构造器静态自有名字，任何未登记名字即失败。
 * 每条必须写清理由：
 * - `MODELED`：引擎有真实分发/校验 case（注释 cites 具体表/函数）；
 * - `ALLOWED_IMPRECISE`：有意不建模，接受 unknown 口径（写明原因）。
 * 拿不准的一律进 ALLOWED_IMPRECISE 并注明「未建模，接受 unknown」。
 *
 * 键形：
 * - `global:<Name>`            —— globalThis 自有属性名
 * - `<Brand>.static.<prop>`    —— 构造器/命名空间对象自有属性名
 * - `<Brand>.proto.<prop>`     —— `<Brand>.prototype` 自有属性名
 * - `Intl.ns.<prop>`           —— Intl 命名空间自有属性名（含子构造器名）
 * - `Intl.<Sub>.static/proto`  —— Intl 子构造器面
 *
 * 枚举口径：静态面跳过 `length/name/arguments/caller`（函数元属性，全宿主
 * 均匀未建模，不追踪）；原型面跳过 `constructor`（同因）。symbol 键自有
 * 属性（@@iterator 等）不进 getOwnPropertyNames，天然不在地板内。
 *
 * `VERSION_SKEW`：存在性随 Node 版本/执行上下文漂移的键（如 Temporal 仅
 * 新 Node、`module/require` 等仅 CJS 上下文）。这些键仍要求登记，但僵尸
 * 检查（运行时不存在 → 失败）对其豁免——缺席是版本差异而非台账腐化。
 */

/** 地板枚举的策展 brand 列表（ctor = 构造器含 prototype；namespace = 纯对象） */
export interface CuratedBrand {
  name: string;
  kind: "ctor" | "namespace";
}

export const CURATED_BRANDS: readonly CuratedBrand[] = [
  { name: "Object", kind: "ctor" },
  { name: "Array", kind: "ctor" },
  { name: "String", kind: "ctor" },
  { name: "Number", kind: "ctor" },
  { name: "Boolean", kind: "ctor" },
  { name: "Symbol", kind: "ctor" },
  { name: "BigInt", kind: "ctor" },
  { name: "Promise", kind: "ctor" },
  { name: "Map", kind: "ctor" },
  { name: "Set", kind: "ctor" },
  { name: "WeakMap", kind: "ctor" },
  { name: "WeakSet", kind: "ctor" },
  { name: "Date", kind: "ctor" },
  { name: "RegExp", kind: "ctor" },
  // Error 家族（引擎 ERROR_CTOR_NAMES 口径，8 个）
  { name: "Error", kind: "ctor" },
  { name: "TypeError", kind: "ctor" },
  { name: "RangeError", kind: "ctor" },
  { name: "ReferenceError", kind: "ctor" },
  { name: "SyntaxError", kind: "ctor" },
  { name: "EvalError", kind: "ctor" },
  { name: "URIError", kind: "ctor" },
  { name: "AggregateError", kind: "ctor" },
  { name: "ArrayBuffer", kind: "ctor" },
  { name: "SharedArrayBuffer", kind: "ctor" },
  { name: "DataView", kind: "ctor" },
  // TypedArray 全家（Uint8Array 等）
  { name: "Float16Array", kind: "ctor" },
  { name: "Uint8Array", kind: "ctor" },
  { name: "Uint8ClampedArray", kind: "ctor" },
  { name: "Int8Array", kind: "ctor" },
  { name: "Uint16Array", kind: "ctor" },
  { name: "Int16Array", kind: "ctor" },
  { name: "Uint32Array", kind: "ctor" },
  { name: "Int32Array", kind: "ctor" },
  { name: "Float32Array", kind: "ctor" },
  { name: "Float64Array", kind: "ctor" },
  { name: "BigInt64Array", kind: "ctor" },
  { name: "BigUint64Array", kind: "ctor" },
  { name: "URL", kind: "ctor" },
  { name: "URLSearchParams", kind: "ctor" },
  { name: "TextDecoder", kind: "ctor" },
  { name: "TextEncoder", kind: "ctor" },
  { name: "WeakRef", kind: "ctor" },
  { name: "FinalizationRegistry", kind: "ctor" },
  { name: "Proxy", kind: "ctor" }, // 无 .prototype，仅静态面
  { name: "Intl", kind: "namespace" }, // 特判：ns.* + 子构造器
  { name: "Reflect", kind: "namespace" },
  { name: "Math", kind: "namespace" },
  { name: "JSON", kind: "namespace" },
];

/** Intl 子构造器（函数值的自有属性；静态/原型面分别枚举） */
export const INTL_SUB_CTORS: readonly string[] = [
  "Collator",
  "DateTimeFormat",
  "DisplayNames",
  "ListFormat",
  "Locale",
  "NumberFormat",
  "PluralRules",
  "RelativeTimeFormat",
  "Segmenter",
  "DurationFormat",
];

/**
 * MODELED：引擎有分发/校验 case 的名字（理由 cites 派发点）。
 * 分发面速查：
 * - builtins/error.ts   evalBuiltinNew / evalBuiltinInstanceMethod / evalBigIntStatic
 * - exec/class.ts       $new 宿主表 / $invokeInner（数组方法、装箱、bigint/number 折叠）
 * - exec/runtime/containers.ts NAMESPACE_GLOBALS / TYPED_ARRAY_ELEMENT / $get 命名空间投影
 * - exec/runtime/members.ts   BUILTIN_BRAND_METHODS
 * - builtins/object.ts  BUILTIN_BRAND_NO_ENUM_KEYS / evalObjectMethod
 * - builtins/{math,string,number,json,date,regexp,promise,reflect,symbol,global,array,object-proto}.ts
 * - exec/calls.ts       GLOBAL_FNS / NEVER_EXEC_HOST_FN_NAMES
 */
export const MODELED: Record<string, string> = {
  // ---- globalThis 名字（引擎有专属派发/校验/拦截 case） --------------------
  "global:Array": "evalBuiltinNew:Array(makeArrayCtorAbs)+$new Array(exec/class.ts)+GLOBAL_FNS+NAMESPACE_GLOBALS",
  "global:ArrayBuffer": "evalBuiltinNew:ArrayBuffer(makeArrayBufferAbs)+$new ArrayBuffer(Bug41/15)",
  "global:BigInt": "evalBuiltinNew 定抛 TypeError+$new 同口径(Bug45)+GLOBAL_FNS+evalGlobalFn(BigInt)+NAMESPACE_GLOBALS",
  "global:Boolean": "makeBoxedAbs(evalBuiltinNew+$new,Bug22)+GLOBAL_FNS+evalGlobalFn(Boolean)+NAMESPACE_GLOBALS(Bug56)",
  "global:DataView": "makeDataViewAbs(evalBuiltinNew+$new,Bug63)",
  "global:Date": "evalDateCtor(evalBuiltinNew+$new,Bug24)+evalDateStatic/evalDateMethod+NAMESPACE_GLOBALS",
  "global:Error": "errorBrandAbs(isErrorCtor_NAMES)+GLOBAL_FNS+NAMESPACE_GLOBALS",
  "global:EvalError": "ERROR_CTOR_NAMES(errorBrandAbs name/message 槽)+GLOBAL_FNS",
  "global:RangeError": "ERROR_CTOR_NAMES(errorBrandAbs)+GLOBAL_FNS",
  "global:ReferenceError": "ERROR_CTOR_NAMES(errorBrandAbs)+GLOBAL_FNS",
  "global:SyntaxError": "ERROR_CTOR_NAMES(errorBrandAbs)+GLOBAL_FNS",
  "global:TypeError": "ERROR_CTOR_NAMES(errorBrandAbs)+GLOBAL_FNS",
  "global:URIError": "ERROR_CTOR_NAMES(errorBrandAbs)+GLOBAL_FNS",
  "global:AggregateError": "ERROR_CTOR_NAMES(errorBrandAbs)+GLOBAL_FNS",
  "global:JSON": "evalJsonMethod(builtins/json.ts)+NAMESPACE_GLOBALS",
  "global:Map": "evalBuiltinNew:Map(makeMapAbs,C1.1)+$new Map+BUILTIN_BRAND_METHODS.Map+NAMESPACE_GLOBALS(Bug56)",
  "global:Math": "evalMathMethod(builtins/math.ts)+NAMESPACE_GLOBALS",
  "global:Number": "evalNumberStatic+makeBoxedAbs+evalGlobalFn(Number)+NAMESPACE_GLOBALS",
  "global:Object": "evalObjectMethod(builtins/object.ts)+evalGlobalFn(Object)+NAMESPACE_GLOBALS",
  "global:Promise": "evalPromiseCtor+$new Promise+NAMESPACE_GLOBALS",
  "global:Proxy": "makeProxyAbs(evalBuiltinNew+$new,Bug37 target/handler 校验)",
  "global:Reflect": "reflect.ts 13 静态+NAMESPACE_GLOBALS(Bug19/43)",
  "global:RegExp": "evalRegExpCtor+evalRegExpMethod+regexpBrandSlots+NAMESPACE_GLOBALS",
  "global:Set": "evalBuiltinNew:Set(makeSetAbs,C1.2)+$new Set+BUILTIN_BRAND_METHODS.Set+NAMESPACE_GLOBALS(Bug56)",
  "global:SharedArrayBuffer": "makeSharedArrayBufferAbs(evalBuiltinNew+$new,Bug15)",
  "global:String": "evalStringStatic+methods.ts prim string 面+evalGlobalFn(String)+NAMESPACE_GLOBALS",
  "global:Symbol": "evalSymbolCtor+evalSymbolStatic(for/keyFor,Bug43)+GLOBAL_FNS+NAMESPACE_GLOBALS",
  "global:TextDecoder": "makeTextDecoderAbs($new TextDecoder,label 校验+encoding 槽,Bug45)",
  "global:URL": "makeUrlAbs(Bug85)+URL.canParse(Bug24)+NAMESPACE_GLOBALS",
  "global:URLSearchParams": "makeUrlSearchParamsAbs($new,init 形态校验)+BUILTIN_BRAND_NO_ENUM_KEYS(Bug43)",
  "global:WeakMap": "makeWeakCollectionAbs(Bug15)+BUILTIN_BRAND_METHODS.WeakMap+NAMESPACE_GLOBALS(Bug56)",
  "global:WeakRef": "BUILTIN_BRAND_NO_ENUM_KEYS(Bug43 枚举面)；构造/deref 无专属 case（通用口径）",
  "global:WeakSet": "makeWeakCollectionAbs(Bug15)+BUILTIN_BRAND_METHODS.WeakSet+NAMESPACE_GLOBALS(Bug56)",
  "global:FinalizationRegistry": "BUILTIN_BRAND_NO_ENUM_KEYS(Bug43 枚举面)+evalBuiltinInstanceMethod register/unregister(Bug43 弱键校验)+$new 空 brand 兜底实例",
  "global:Intl": "NAMESPACE_GLOBALS(Bug44)+typeof Intl 折 object(ops.$typeof)+$get 成员投影(NumberFormat/DateTimeFormat 构造器值)",
  // TypedArray：元素域建模（下标读投影）
  "global:Uint8Array": "TYPED_ARRAY_ELEMENT 元素域(exec/runtime/containers.ts)",
  "global:Uint8ClampedArray": "TYPED_ARRAY_ELEMENT 元素域",
  "global:Int8Array": "TYPED_ARRAY_ELEMENT 元素域",
  "global:Uint16Array": "TYPED_ARRAY_ELEMENT 元素域",
  "global:Int16Array": "TYPED_ARRAY_ELEMENT 元素域",
  "global:Uint32Array": "TYPED_ARRAY_ELEMENT 元素域",
  "global:Int32Array": "TYPED_ARRAY_ELEMENT 元素域",
  "global:Float32Array": "TYPED_ARRAY_ELEMENT 元素域",
  "global:Float64Array": "TYPED_ARRAY_ELEMENT 元素域",
  "global:BigInt64Array": "TYPED_ARRAY_ELEMENT(bigint) 元素域",
  "global:BigUint64Array": "TYPED_ARRAY_ELEMENT(bigint) 元素域",
  // 值语义内建
  "global:Infinity": "HOST_INTRINSIC_NAMES 转译期折叠(exec/transpile/intrinsics.ts)",
  "global:NaN": "HOST_INTRINSIC_NAMES 转译期折叠",
  "global:undefined": "HOST_INTRINSIC_NAMES 转译期折叠",
  "global:atob": "GLOBAL_FNS+evalGlobalFn(Bug5 base64/URI/escape 族折叠)",
  "global:btoa": "GLOBAL_FNS+evalGlobalFn(Bug5)",
  "global:decodeURI": "GLOBAL_FNS+evalGlobalFn(Bug5)",
  "global:decodeURIComponent": "GLOBAL_FNS+evalGlobalFn(Bug5)",
  "global:encodeURI": "GLOBAL_FNS+evalGlobalFn(Bug5)",
  "global:encodeURIComponent": "GLOBAL_FNS+evalGlobalFn(Bug5)",
  "global:escape": "GLOBAL_FNS+evalGlobalFn(Bug5,Annex B)",
  "global:unescape": "GLOBAL_FNS+evalGlobalFn(Bug5,Annex B)",
  "global:eval": "GLOBAL_FNS+evalGlobalFn(eval,builtins/global.ts)",
  "global:isFinite": "evalGlobalFn 布尔折叠(builtins/global.ts)",
  "global:isNaN": "evalGlobalFn 布尔折叠",
  "global:parseFloat": "evalGlobalFn+foldParseFloat(builtins/number.ts)",
  "global:parseInt": "evalGlobalFn+foldParseInt(builtins/number.ts)",
  // fail-closed 拦截面（显式 case：命中即 unknown#opaque + 上报）
  "global:fetch": "NEVER_EXEC_HOST_FN_NAMES fail-closed 拦截(exec/calls.ts)",
  "global:queueMicrotask": "NEVER_EXEC_HOST_FN_NAMES fail-closed 拦截",
  "global:setImmediate": "NEVER_EXEC_HOST_FN_NAMES fail-closed 拦截",
  "global:setInterval": "NEVER_EXEC_HOST_FN_NAMES fail-closed 拦截",
  "global:setTimeout": "NEVER_EXEC_HOST_FN_NAMES fail-closed 拦截",
  "global:WebSocket": "NEVER_EXEC_HOST_FN_NAMES fail-closed 拦截($new 宿主副作用守卫)",

  // ---- Object -------------------------------------------------------------
  "Object.static.prototype": "$get(ns,'prototype')→objectProtoBrand(NAMESPACE_GLOBALS)",
  "Object.static.assign": "evalObjectMethod(builtins/object.ts)+runtimeAssignObject",
  "Object.static.create": "evalObjectMethod(create 分支)",
  "Object.static.defineProperties": "evalObjectMethod",
  "Object.static.defineProperty": "evalObjectMethod",
  "Object.static.entries": "evalObjectMethod",
  "Object.static.freeze": "evalObjectMethod+不变性标记",
  "Object.static.fromEntries": "evalObjectMethod",
  "Object.static.getOwnPropertyDescriptor": "evalObjectMethod",
  "Object.static.getOwnPropertyDescriptors": "evalObjectMethod",
  "Object.static.getOwnPropertyNames": "evalObjectMethod",
  "Object.static.getOwnPropertySymbols": "evalObjectMethod",
  "Object.static.getPrototypeOf": "evalObjectMethod",
  "Object.static.hasOwn": "evalObjectMethod",
  "Object.static.is": "evalObjectMethod",
  "Object.static.isExtensible": "evalObjectMethod",
  "Object.static.isFrozen": "evalObjectMethod",
  "Object.static.isSealed": "evalObjectMethod",
  "Object.static.keys": "evalObjectMethod",
  "Object.static.preventExtensions": "evalObjectMethod",
  "Object.static.seal": "evalObjectMethod",
  "Object.static.setPrototypeOf": "evalObjectMethod",
  "Object.static.values": "evalObjectMethod",
  "Object.proto.hasOwnProperty": "object-proto.ts+OBJECT_PROTO_METHOD_NAMES",
  "Object.proto.isPrototypeOf": "object-proto.ts",
  "Object.proto.propertyIsEnumerable": "object-proto.ts",
  "Object.proto.toLocaleString": "object-proto.ts(Bug 72 面)",
  "Object.proto.toString": "object-proto.ts(形态标签折叠)",
  "Object.proto.valueOf": "object-proto.ts(恒等)",

  // ---- Array --------------------------------------------------------------
  "Array.static.prototype": "$get(ns,'prototype')→protoBrandAbs+Array 三键 arrayMethodAbs(Bug56)",
  "Array.static.from": "evalArrayStatic(builtins/array.ts)",
  "Array.static.fromAsync": "evalArrayStatic",
  "Array.static.isArray": "evalArrayStatic",
  "Array.static.of": "evalArrayStatic",
  "Array.proto.length": "tuple/arr 长度读核心面",
  "Array.proto.at": "$invokeInner at 分支(exec/class.ts)",
  "Array.proto.concat": "$invokeInner concat 分支",
  "Array.proto.copyWithin": "$arrMutContainer copyWithin(clampWindow)",
  "Array.proto.entries": "$invokeInner entries(数组迭代器)",
  "Array.proto.every": "$invokeInner every(回调谓词折叠)",
  "Array.proto.fill": "$invokeInner fill+$arrMutContainer fillTuple",
  "Array.proto.filter": "$invokeInner filter",
  "Array.proto.find": "$invokeInner find",
  "Array.proto.findIndex": "$invokeInner findIndex",
  "Array.proto.findLast": "$invokeInner findLast",
  "Array.proto.findLastIndex": "$invokeInner findLastIndex",
  "Array.proto.flat": "$invokeInner flat",
  "Array.proto.flatMap": "$invokeInner flatMap",
  "Array.proto.forEach": "$invokeInner forEach",
  "Array.proto.includes": "$invokeInner includes",
  "Array.proto.indexOf": "$invokeInner indexOf/lastIndexOf",
  "Array.proto.join": "arrayJoinWithSep/arrayMethodAbs(builtins/array.ts)",
  "Array.proto.keys": "$invokeInner keys(下标迭代器)",
  "Array.proto.lastIndexOf": "$invokeInner indexOf/lastIndexOf",
  "Array.proto.map": "$invokeInner map(逐元素回调)",
  "Array.proto.pop": "$arrMutContainer pop(C1.4 重绑)",
  "Array.proto.push": "$arrMutContainer push",
  "Array.proto.reduce": "$invokeInner reduce",
  "Array.proto.reduceRight": "$invokeInner reduceRight",
  "Array.proto.reverse": "$arrMutContainer reverse(holes 镜像)",
  "Array.proto.shift": "$arrMutContainer shift",
  "Array.proto.slice": "$invokeInner slice",
  "Array.proto.some": "$invokeInner some(回调谓词折叠)",
  "Array.proto.sort": "$invokeInner sort+$arrMutContainer(降 arr,比较器校验 Bug51)",
  "Array.proto.splice": "$arrMutContainer splice(下标校验 Bug56)",
  "Array.proto.toLocaleString": "arrayJoinToString(builtins/array.ts)",
  "Array.proto.toReversed": "$invokeInner toReversed",
  "Array.proto.toSorted": "$invokeInner toSorted",
  "Array.proto.toSpliced": "$invokeInner toSpliced",
  "Array.proto.toString": "arrayJoinToString",
  "Array.proto.unshift": "$arrMutContainer unshift",
  "Array.proto.values": "$invokeInner values(元素迭代器)",
  "Array.proto.with": "$invokeInner with",

  // ---- String -------------------------------------------------------------
  "String.static.prototype": "$get(ns,'prototype')→protoBrandAbs+PROTO_PRIM_METHOD_NAMES.String(Bug56)",
  "String.static.fromCharCode": "evalStringStatic(builtins/string.ts,ToUint16 面)",
  "String.static.fromCodePoint": "evalStringStatic(code point 校验)",
  "String.static.raw": "evalStringStatic($tpl 模板对象拼接,Bug12)",
  "String.proto.length": "prim string 长度读核心面",
  "String.proto.anchor": "methods.ts Annex B HTML 方法(Bug55)",
  "String.proto.at": "methods.ts at 分支",
  "String.proto.big": "methods.ts Annex B(Bug55)",
  "String.proto.blink": "methods.ts Annex B(Bug55)",
  "String.proto.bold": "methods.ts Annex B(Bug55)",
  "String.proto.charAt": "methods.ts charAt(缺省 pos 折叠)",
  "String.proto.charCodeAt": "methods.ts charCodeAt",
  "String.proto.codePointAt": "methods.ts codePointAt",
  "String.proto.concat": "methods.ts concat(concatString)",
  "String.proto.endsWith": "methods.ts endsWith",
  "String.proto.fixed": "methods.ts Annex B(Bug55)",
  "String.proto.fontcolor": "methods.ts Annex B(实参 ToString 校验)",
  "String.proto.fontsize": "methods.ts Annex B(实参 ToString 校验)",
  "String.proto.includes": "methods.ts includes",
  "String.proto.indexOf": "methods.ts indexOf/lastIndexOf",
  "String.proto.italics": "methods.ts Annex B(Bug55)",
  "String.proto.lastIndexOf": "methods.ts indexOf/lastIndexOf",
  "String.proto.link": "methods.ts Annex B(实参 ToString 校验)",
  "String.proto.localeCompare": "methods.ts localeCompare(Bug72 locale 校验)",
  "String.proto.match": "methods.ts match(matchResultDomain)",
  "String.proto.matchAll": "methods.ts matchAll(matchAllAbstractArm)",
  "String.proto.normalize": "methods.ts normalize(form 校验)",
  "String.proto.padEnd": "methods.ts padEnd(validateIndexArg)",
  "String.proto.padStart": "methods.ts padStart",
  "String.proto.repeat": "methods.ts repeat(count 校验)",
  "String.proto.replace": "methods.ts replace(string-index-methods 面)",
  "String.proto.replaceAll": "methods.ts replaceAll",
  "String.proto.search": "methods.ts search(→ number)",
  "String.proto.slice": "methods.ts slice(ToIntegerOrInfinity 折叠)",
  "String.proto.small": "methods.ts Annex B(Bug55)",
  "String.proto.split": "methods.ts split",
  "String.proto.startsWith": "methods.ts startsWith",
  "String.proto.strike": "methods.ts Annex B(Bug55)",
  "String.proto.sub": "methods.ts Annex B(Bug55)",
  "String.proto.substr": "methods.ts substr(Annex B,Bug72)",
  "String.proto.substring": "methods.ts substring(null-end 口径)",
  "String.proto.sup": "methods.ts Annex B(Bug55)",
  "String.proto.toLocaleLowerCase": "methods.ts(Bug72 宿主折叠)",
  "String.proto.toLocaleUpperCase": "methods.ts(Bug72 宿主折叠)",
  "String.proto.toLowerCase": "methods.ts(字面量宿主折叠)",
  "String.proto.toString": "methods.ts toString(恒等/形态)",
  "String.proto.trim": "methods.ts trim",
  "String.proto.trimEnd": "methods.ts(Bug11 别名同构)",
  "String.proto.trimLeft": "methods.ts(ES2017 别名,Bug11)",
  "String.proto.trimRight": "methods.ts(ES2017 别名,Bug11)",
  "String.proto.trimStart": "methods.ts trimStart",
  "String.proto.toUpperCase": "methods.ts(字面量宿主折叠)",
  "String.proto.valueOf": "methods.ts valueOf(恒等)",

  // ---- Number -------------------------------------------------------------
  "Number.static.prototype": "$get(ns,'prototype')→protoBrandAbs+PROTO_PRIM_METHOD_NAMES.Number(Bug56)",
  "Number.static.EPSILON": "命名空间真值投影 $get→$lit(raw)(containers.ts)",
  "Number.static.MAX_SAFE_INTEGER": "命名空间真值投影 $lit(raw)",
  "Number.static.MAX_VALUE": "命名空间真值投影 $lit(raw)",
  "Number.static.MIN_SAFE_INTEGER": "命名空间真值投影 $lit(raw)",
  "Number.static.MIN_VALUE": "命名空间真值投影 $lit(raw)",
  "Number.static.NEGATIVE_INFINITY": "命名空间真值投影 $lit(raw)",
  "Number.static.NaN": "命名空间真值投影 $lit(raw)",
  "Number.static.POSITIVE_INFINITY": "命名空间真值投影 $lit(raw)",
  "Number.static.isFinite": "evalNumberStatic(builtins/number.ts)",
  "Number.static.isInteger": "evalNumberStatic",
  "Number.static.isNaN": "evalNumberStatic",
  "Number.static.isSafeInteger": "evalNumberStatic",
  "Number.static.parseFloat": "evalNumberStatic→foldParseFloat",
  "Number.static.parseInt": "evalNumberStatic→foldParseInt",
  "Number.proto.toExponential": "$invokeInner number 字面量折叠分支(exec/class.ts)",
  "Number.proto.toFixed": "$invokeInner number 折叠(非法参 RangeError)",
  "Number.proto.toLocaleString": "$invokeInner number 折叠(ICU 不转换实参)",
  "Number.proto.toPrecision": "$invokeInner number 折叠",
  "Number.proto.toString": "$invokeInner number 折叠(radix 校验 Bug65)",
  "Number.proto.valueOf": "$invokeInner number valueOf(恒等)",

  // ---- Boolean / Symbol / BigInt ------------------------------------------
  "Boolean.static.prototype": "$get(ns,'prototype')→protoBrandAbs(Bug56 注释点名)",
  "Boolean.proto.toString": "装箱拆箱(Bug22 boxedPrimitiveValue)→prim boolean 面",
  "Boolean.proto.valueOf": "装箱拆箱→prim boolean 面",
  "Symbol.static.prototype": "$get(ns,'prototype')→protoBrandAbs(NAMESPACE_GLOBALS)",
  "Symbol.static.asyncDispose": "命名空间真值投影 $lit(raw)",
  "Symbol.static.asyncIterator": "命名空间真值投影 $lit(raw)",
  "Symbol.static.dispose": "命名空间真值投影 $lit(raw)",
  "Symbol.static.for": "evalSymbolStatic(Bug43 注册表身份)",
  "Symbol.static.hasInstance": "命名空间真值投影 $lit(raw)",
  "Symbol.static.isConcatSpreadable": "命名空间真值投影 $lit(raw)",
  "Symbol.static.iterator": "命名空间真值投影 $lit(raw)",
  "Symbol.static.keyFor": "evalSymbolStatic(Bug43 反查)",
  "Symbol.static.match": "命名空间真值投影 $lit(raw)",
  "Symbol.static.matchAll": "命名空间真值投影 $lit(raw)",
  "Symbol.static.replace": "命名空间真值投影 $lit(raw)",
  "Symbol.static.search": "命名空间真值投影 $lit(raw)",
  "Symbol.static.species": "命名空间真值投影 $lit(raw)",
  "Symbol.static.split": "命名空间真值投影 $lit(raw)",
  "Symbol.static.toPrimitive": "命名空间真值投影 $lit(raw)",
  "Symbol.static.toStringTag": "命名空间真值投影 $lit(raw)",
  "Symbol.static.unscopables": "命名空间真值投影 $lit(raw)",
  "Symbol.proto.description": "$get symbol description 槽(containers.ts→symbolDescriptionAbs)",
  "Symbol.proto.toString": "$invokeInner Symbol 分支(→stringOfSymbol,SymbolDescriptiveString)",
  "Symbol.proto.valueOf": "$invokeInner Symbol 分支(恒等)",
  "BigInt.static.prototype": "$get(ns,'prototype')→protoBrandAbs(NAMESPACE_GLOBALS)",
  "BigInt.static.asIntN": "evalBigIntStatic(builtins/error.ts,Bug83/41 双实参校验)",
  "BigInt.static.asUintN": "evalBigIntStatic",
  "BigInt.proto.toString": "$invokeInner bigint 折叠(radix 校验 Bug65)",
  "BigInt.proto.valueOf": "$invokeInner bigint valueOf(恒等)",

  // ---- Promise / Map / Set / WeakMap / WeakSet -----------------------------
  "Promise.static.prototype": "$get(ns,'prototype')→protoBrandAbs+BUILTIN_BRAND_METHODS.Promise",
  "Promise.static.all": "builtins/promise.ts 静态派发",
  "Promise.static.allSettled": "builtins/promise.ts",
  "Promise.static.any": "builtins/promise.ts",
  "Promise.static.race": "builtins/promise.ts",
  "Promise.static.reject": "builtins/promise.ts",
  "Promise.static.resolve": "builtins/promise.ts",
  "Promise.static.withResolvers": "builtins/promise.ts",
  "Promise.proto.catch": "evalPromiseMethod+eff(promise) 实例面",
  "Promise.proto.finally": "evalPromiseMethod",
  "Promise.proto.then": "evalPromiseMethod(then 通道映射)",
  "Map.static.prototype": "$get(ns,'prototype')→protoBrandAbs(Bug56 点名)",
  "Map.proto.clear": "evalBuiltinInstanceMethod mapClearEntries",
  "Map.proto.delete": "evalBuiltinInstanceMethod mapDeleteEntry",
  "Map.proto.entries": "evalBuiltinInstanceMethod collectionIteratorAbs(Bug23)",
  "Map.proto.forEach": "$collectionForEach(C1 条目回调)",
  "Map.proto.get": "evalBuiltinInstanceMethod mapGetEntry",
  "Map.proto.has": "evalBuiltinInstanceMethod mapHasEntry",
  "Map.proto.keys": "evalBuiltinInstanceMethod(Bug23)",
  "Map.proto.set": "evalBuiltinInstanceMethod mapSetEntry",
  "Map.proto.size": "evalBuiltinInstanceMethod mapSizeAbs",
  "Map.proto.values": "evalBuiltinInstanceMethod(Bug23)",
  "Set.static.prototype": "$get(ns,'prototype')→protoBrandAbs(Bug56 点名)",
  "Set.proto.add": "evalBuiltinInstanceMethod setAddEntry",
  "Set.proto.clear": "evalBuiltinInstanceMethod setClearEntries",
  "Set.proto.delete": "evalBuiltinInstanceMethod setDeleteEntry",
  "Set.proto.entries": "evalBuiltinInstanceMethod(setEntryTuple,Bug23)",
  "Set.proto.forEach": "$collectionForEach(C1)",
  "Set.proto.has": "evalBuiltinInstanceMethod setHasEntry",
  "Set.proto.keys": "evalBuiltinInstanceMethod(≡values,Bug23)",
  "Set.proto.size": "evalBuiltinInstanceMethod setSizeAbs",
  "Set.proto.values": "evalBuiltinInstanceMethod(Bug23)",
  "WeakMap.static.prototype": "$get(ns,'prototype')→protoBrandAbs(Bug56 点名)",
  "WeakMap.proto.delete": "BUILTIN_BRAND_METHODS.WeakMap+$invoke brand 面",
  "WeakMap.proto.get": "BUILTIN_BRAND_METHODS.WeakMap",
  "WeakMap.proto.has": "BUILTIN_BRAND_METHODS.WeakMap",
  "WeakMap.proto.set": "BUILTIN_BRAND_METHODS.WeakMap",
  "WeakSet.static.prototype": "$get(ns,'prototype')→protoBrandAbs(Bug56 点名)",
  "WeakSet.proto.add": "BUILTIN_BRAND_METHODS.WeakSet",
  "WeakSet.proto.delete": "BUILTIN_BRAND_METHODS.WeakSet",
  "WeakSet.proto.has": "BUILTIN_BRAND_METHODS.WeakSet",
  "FinalizationRegistry.proto.register": "evalBuiltinInstanceMethod(Bug43 CanBeHeldWeakly target/unregisterToken 校验)",
  "FinalizationRegistry.proto.unregister": "evalBuiltinInstanceMethod(Bug43 CanBeHeldWeakly+保守 boolean)",

  // ---- Date ---------------------------------------------------------------
  "Date.static.prototype": "$get(ns,'prototype')→protoBrandAbs(NAMESPACE_GLOBALS)",
  "Date.static.UTC": "evalDateStatic(Bug7 ToNumber 逐实参)",
  "Date.static.now": "evalDateStatic(→number path,非确定值不折)",
  "Date.static.parse": "evalDateStatic(Bug7 ToString+折叠)",
  "Date.proto.getDate": "DATE_NUMBER_GETTERS(builtins/date.ts)",
  "Date.proto.getDay": "DATE_NUMBER_GETTERS",
  "Date.proto.getFullYear": "DATE_NUMBER_GETTERS",
  "Date.proto.getHours": "DATE_NUMBER_GETTERS",
  "Date.proto.getMilliseconds": "DATE_NUMBER_GETTERS",
  "Date.proto.getMinutes": "DATE_NUMBER_GETTERS",
  "Date.proto.getMonth": "DATE_NUMBER_GETTERS",
  "Date.proto.getSeconds": "DATE_NUMBER_GETTERS",
  "Date.proto.getTime": "DATE_NUMBER_GETTERS",
  "Date.proto.getTimezoneOffset": "DATE_NUMBER_GETTERS",
  "Date.proto.getUTCDate": "DATE_NUMBER_GETTERS",
  "Date.proto.getUTCDay": "DATE_NUMBER_GETTERS",
  "Date.proto.getUTCFullYear": "DATE_NUMBER_GETTERS",
  "Date.proto.getUTCHours": "DATE_NUMBER_GETTERS",
  "Date.proto.getUTCMilliseconds": "DATE_NUMBER_GETTERS",
  "Date.proto.getUTCMinutes": "DATE_NUMBER_GETTERS",
  "Date.proto.getUTCMonth": "DATE_NUMBER_GETTERS",
  "Date.proto.getUTCSeconds": "DATE_NUMBER_GETTERS",
  "Date.proto.getYear": "DATE_NUMBER_GETTERS(Annex B,Bug39)",
  "Date.proto.setDate": "DATE_SETTERS(ToNumber 校验 Bug62)",
  "Date.proto.setFullYear": "DATE_SETTERS",
  "Date.proto.setHours": "DATE_SETTERS",
  "Date.proto.setMilliseconds": "DATE_SETTERS",
  "Date.proto.setMinutes": "DATE_SETTERS",
  "Date.proto.setMonth": "DATE_SETTERS",
  "Date.proto.setSeconds": "DATE_SETTERS",
  "Date.proto.setTime": "DATE_SETTERS",
  "Date.proto.setUTCDate": "DATE_SETTERS",
  "Date.proto.setUTCFullYear": "DATE_SETTERS",
  "Date.proto.setUTCHours": "DATE_SETTERS",
  "Date.proto.setUTCMilliseconds": "DATE_SETTERS",
  "Date.proto.setUTCMinutes": "DATE_SETTERS",
  "Date.proto.setUTCMonth": "DATE_SETTERS",
  "Date.proto.setUTCSeconds": "DATE_SETTERS",
  "Date.proto.setYear": "DATE_SETTERS(Annex B,Bug39)",
  "Date.proto.toDateString": "DATE_STRING_METHODS",
  "Date.proto.toGMTString": "DATE_STRING_METHODS(Annex B)",
  "Date.proto.toISOString": "evalDateMethod toISOString(tv facet 精确/Invalid RangeError)",
  "Date.proto.toJSON": "DATE_STRING_METHODS",
  "Date.proto.toLocaleDateString": "DATE_STRING_METHODS",
  "Date.proto.toLocaleString": "DATE_STRING_METHODS",
  "Date.proto.toLocaleTimeString": "DATE_STRING_METHODS",
  "Date.proto.toString": "DATE_STRING_METHODS",
  "Date.proto.toTimeString": "DATE_STRING_METHODS",
  "Date.proto.toUTCString": "DATE_STRING_METHODS",
  "Date.proto.valueOf": "DATE_NUMBER_GETTERS",

  // ---- RegExp -------------------------------------------------------------
  "RegExp.static.prototype": "$get(ns,'prototype')→protoBrandAbs(NAMESPACE_GLOBALS)",
  "RegExp.proto.dotAll": "regexpBrandSlots+REGEX_FLAG_SLOTS(Bug28)",
  "RegExp.proto.exec": "evalRegExpMethod+execRegexBrand(字面量精确执行)",
  "RegExp.proto.flags": "regexpBrandSlots(规范序 strLit)",
  "RegExp.proto.global": "REGEX_FLAG_SLOTS(Bug28)",
  "RegExp.proto.hasIndices": "REGEX_FLAG_SLOTS(Bug28)",
  "RegExp.proto.ignoreCase": "REGEX_FLAG_SLOTS(Bug28)",
  "RegExp.proto.multiline": "REGEX_FLAG_SLOTS(Bug28)",
  "RegExp.proto.source": "regexpBrandSlots(strLit)",
  "RegExp.proto.sticky": "REGEX_FLAG_SLOTS(Bug28)",
  "RegExp.proto.test": "evalRegExpMethod(subject 校验 Bug52)",
  "RegExp.proto.toString": "evalRegExpMethod(→string)",
  "RegExp.proto.unicode": "REGEX_FLAG_SLOTS(Bug28)",

  // ---- Error 家族 ----------------------------------------------------------
  "Error.static.prototype": "$get(ns,'prototype')→protoBrandAbs(NAMESPACE_GLOBALS 含 Error)",
  "Error.proto.message": "errorBrandAbs message 槽(C2.2,catch 形参可读)",
  "Error.proto.name": "errorBrandAbs name 槽(C2.2)",
  "Error.proto.toString": "evalBuiltinInstanceMethod(Bug10 `${name}: ${message}`)",
  "TypeError.proto.message": "errorBrandAbs 家族槽",
  "TypeError.proto.name": "errorBrandAbs 家族槽",
  "RangeError.proto.message": "errorBrandAbs 家族槽",
  "RangeError.proto.name": "errorBrandAbs 家族槽",
  "ReferenceError.proto.message": "errorBrandAbs 家族槽",
  "ReferenceError.proto.name": "errorBrandAbs 家族槽",
  "SyntaxError.proto.message": "errorBrandAbs 家族槽",
  "SyntaxError.proto.name": "errorBrandAbs 家族槽",
  "EvalError.proto.message": "errorBrandAbs 家族槽",
  "EvalError.proto.name": "errorBrandAbs 家族槽",
  "URIError.proto.message": "errorBrandAbs 家族槽",
  "URIError.proto.name": "errorBrandAbs 家族槽",
  "AggregateError.proto.message": "errorBrandAbs 家族槽",
  "AggregateError.proto.name": "errorBrandAbs 家族槽",

  // ---- ArrayBuffer / SharedArrayBuffer / DataView --------------------------
  "ArrayBuffer.proto.byteLength": "makeArrayBufferAbs 槽(Bug41/15)",
  "ArrayBuffer.proto.maxByteLength": "makeArrayBufferAbs 槽(growable 面)",
  "ArrayBuffer.proto.resizable": "makeArrayBufferAbs 槽(布尔折)",
  "SharedArrayBuffer.proto.byteLength": "makeSharedArrayBufferAbs 槽(Bug15)",
  "SharedArrayBuffer.proto.growable": "makeSharedArrayBufferAbs 槽(growable 面)",
  "SharedArrayBuffer.proto.maxByteLength": "makeSharedArrayBufferAbs 槽",
  "DataView.proto.byteLength": "makeDataViewAbs 槽(Bug63)",
  "DataView.proto.byteOffset": "makeDataViewAbs 槽(Bug63)",

  // ---- URL / URLSearchParams / TextDecoder ---------------------------------
  "URL.static.prototype": "$get(ns,'prototype')→protoBrandAbs(NAMESPACE_GLOBALS,Bug24)",
  "URL.static.canParse": "evalUrlStatic canParse(Bug24,total 恒不抛)",
  "URL.proto.hash": "urlBrandAbs componentKeys(Bug29 补 10 组件)",
  "URL.proto.host": "urlBrandAbs componentKeys",
  "URL.proto.hostname": "urlBrandAbs componentKeys",
  "URL.proto.href": "urlBrandAbs componentKeys",
  "URL.proto.origin": "urlBrandAbs componentKeys",
  "URL.proto.password": "urlBrandAbs componentKeys",
  "URL.proto.pathname": "urlBrandAbs componentKeys",
  "URL.proto.port": "urlBrandAbs componentKeys",
  "URL.proto.protocol": "urlBrandAbs componentKeys",
  "URL.proto.search": "urlBrandAbs componentKeys",
  "URL.proto.username": "urlBrandAbs componentKeys",
  "URL.proto.toJSON": "evalBuiltinInstanceMethod(Bug42 ≡href)",
  "TextDecoder.proto.encoding": "makeTextDecoderAbs encoding 槽(Bug45)",

  // ---- Intl（Bug 44：命名空间 + 两个格式化构造器）--------------------------
  "Intl.ns.NumberFormat": "makeIntlCtorAbs 构造器值($get 命名空间分支)+evalBuiltinNew:Intl.NumberFormat(makeIntlFormatAbs locale 校验,Bug44)",
  "Intl.ns.DateTimeFormat": "makeIntlCtorAbs 构造器值($get 命名空间分支)+evalBuiltinNew:Intl.DateTimeFormat(makeIntlFormatAbs locale 校验,Bug44)",
  "Intl.NumberFormat.static.prototype": "$get fn 面 prototype 折 obj（Bug9 构造器值，Bug44）",
  "Intl.DateTimeFormat.static.prototype": "$get fn 面 prototype 折 obj（Bug9 构造器值，Bug44）",

  // ---- Math / JSON / Reflect ----------------------------------------------
  "Math.static.abs": "evalMathMethod 通用折叠(mathMethod 命中即折)",
  "Math.static.acos": "evalMathMethod 通用折叠",
  "Math.static.acosh": "evalMathMethod 通用折叠",
  "Math.static.asin": "evalMathMethod 通用折叠",
  "Math.static.asinh": "evalMathMethod 通用折叠",
  "Math.static.atan": "evalMathMethod 通用折叠",
  "Math.static.atan2": "evalMathMethod 通用折叠",
  "Math.static.atanh": "evalMathMethod 通用折叠",
  "Math.static.cbrt": "evalMathMethod 通用折叠",
  "Math.static.ceil": "evalMathMethod roundingAbs 区间透传(#68)",
  "Math.static.clz32": "evalMathMethod 通用折叠",
  "Math.static.cos": "evalMathMethod 通用折叠",
  "Math.static.cosh": "evalMathMethod 通用折叠",
  "Math.static.E": "命名空间真值投影 $lit(raw)",
  "Math.static.exp": "evalMathMethod 通用折叠",
  "Math.static.expm1": "evalMathMethod 通用折叠",
  "Math.static.f16round": "evalMathMethod 通用折叠(mathMethod 按自有名命中)",
  "Math.static.floor": "evalMathMethod roundingAbs 区间透传(#68)",
  "Math.static.fround": "evalMathMethod 通用折叠",
  "Math.static.hypot": "evalMathMethod 通用折叠",
  "Math.static.imul": "evalMathMethod 通用折叠",
  "Math.static.LN10": "命名空间真值投影 $lit(raw)",
  "Math.static.LN2": "命名空间真值投影 $lit(raw)",
  "Math.static.log": "evalMathMethod 通用折叠",
  "Math.static.log10": "evalMathMethod 通用折叠",
  "Math.static.LOG10E": "命名空间真值投影 $lit(raw)",
  "Math.static.log1p": "evalMathMethod 通用折叠",
  "Math.static.log2": "evalMathMethod 通用折叠",
  "Math.static.LOG2E": "命名空间真值投影 $lit(raw)",
  "Math.static.max": "evalMathMethod minMaxAbs 区间透传(#68)",
  "Math.static.min": "evalMathMethod minMaxAbs 区间透传(#68)",
  "Math.static.PI": "命名空间真值投影 $lit(raw)",
  "Math.static.pow": "evalMathMethod 通用折叠",
  "Math.static.random": "evalMathMethod(→number path,非确定不折)",
  "Math.static.round": "evalMathMethod roundingAbs 区间透传(#68)",
  "Math.static.sign": "evalMathMethod 通用折叠",
  "Math.static.sin": "evalMathMethod 通用折叠",
  "Math.static.sinh": "evalMathMethod 通用折叠",
  "Math.static.SQRT1_2": "命名空间真值投影 $lit(raw)",
  "Math.static.SQRT2": "命名空间真值投影 $lit(raw)",
  "Math.static.sqrt": "evalMathMethod 通用折叠",
  "Math.static.tan": "evalMathMethod 通用折叠",
  "Math.static.tanh": "evalMathMethod 通用折叠",
  "Math.static.trunc": "evalMathMethod roundingAbs 区间透传(#68)",
  "JSON.static.parse": "evalJsonMethod(builtins/json.ts,Bug40/48)",
  "JSON.static.stringify": "evalJsonMethod(槽投影+replacer 口径)",
  "Reflect.static.apply": "reflect.ts apply/construct 分支",
  "Reflect.static.construct": "reflect.ts",
  "Reflect.static.defineProperty": "reflect.ts",
  "Reflect.static.deleteProperty": "reflect.ts",
  "Reflect.static.get": "reflect.ts(Bug19)",
  "Reflect.static.getOwnPropertyDescriptor": "reflect.ts",
  "Reflect.static.getPrototypeOf": "reflect.ts",
  "Reflect.static.has": "reflect.ts",
  "Reflect.static.isExtensible": "reflect.ts",
  "Reflect.static.ownKeys": "reflect.ts",
  "Reflect.static.preventExtensions": "reflect.ts",
  "Reflect.static.set": "reflect.ts",
  "Reflect.static.setPrototypeOf": "reflect.ts",
};

/**
 * ALLOWED_IMPRECISE：有意不建模、接受 unknown 口径的名字（逐条原因）。
 */
export const ALLOWED_IMPRECISE: Record<string, string> = {
  // ---- globalThis：Web/Node 宿主面，未建模，接受 unknown --------------------
  "global:AbortController": "Abort 信号面未建模，接受 unknown",
  "global:AbortSignal": "Abort 信号面未建模，接受 unknown",
  "global:AsyncDisposableStack": "显式资源管理未建模，接受 unknown",
  "global:Atomics": "共享内存原子面未建模，接受 unknown",
  "global:Blob": "二进制数据面未建模，接受 unknown",
  "global:BroadcastChannel": "消息广播宿主面未建模，接受 unknown",
  "global:Buffer": "Node Buffer 未建模，接受 unknown",
  "global:ByteLengthQueuingStrategy": "流背压策略未建模，接受 unknown",
  "global:CloseEvent": "事件宿主面未建模，接受 unknown",
  "global:CompressionStream": "流式压缩未建模，接受 unknown",
  "global:CountQueuingStrategy": "流背压策略未建模，接受 unknown",
  "global:crypto": "WebCrypto 实例未建模，接受 unknown",
  "global:Crypto": "WebCrypto 未建模，接受 unknown",
  "global:CryptoKey": "WebCrypto 未建模，接受 unknown",
  "global:CustomEvent": "事件宿主面未建模，接受 unknown",
  "global:DecompressionStream": "流式解压未建模，接受 unknown",
  "global:DisposableStack": "显式资源管理未建模，接受 unknown",
  "global:DOMException": "Error 形宿主异常，未入 ERROR_CTOR_NAMES，走通用口径，接受 unknown",
  "global:ErrorEvent": "事件宿主面未建模，接受 unknown",
  "global:Event": "事件宿主面未建模，接受 unknown",
  "global:EventTarget": "事件宿主面未建模，接受 unknown",
  "global:File": "二进制数据面未建模，接受 unknown",
  "global:Float16Array": "未入 TYPED_ARRAY_ELEMENT（新版本 TypedArray），元素域未建模，接受 unknown",
  "global:FormData": "表单数据面未建模，接受 unknown",
  "global:Function": "标识符/调用无专属派发；函数面经 fn shape 建模，Function()/new Function 走通用宿主口径，接受 unknown",
  "global:Headers": "fetch 族数据面未建模（仅 fetch 调用被拦截），接受 unknown",
  "global:Iterator": "Iterator helpers 构造器未建模；迭代协议对象另经 collectionIteratorAbs/match-iter 建模，接受 unknown",
  "global:MessageChannel": "消息宿主面未建模，接受 unknown",
  "global:MessageEvent": "消息宿主面未建模，接受 unknown",
  "global:MessagePort": "消息宿主面未建模，接受 unknown",
  "global:navigator": "Navigator 实例未建模，接受 unknown",
  "global:Navigator": "Navigator 构造面未建模，接受 unknown",
  "global:performance": "性能类 API 未建模，接受 unknown（任务口径）",
  "global:Performance": "性能类 API 未建模，接受 unknown",
  "global:PerformanceEntry": "性能类 API 未建模，接受 unknown",
  "global:PerformanceMark": "性能类 API 未建模，接受 unknown",
  "global:PerformanceMeasure": "性能类 API 未建模，接受 unknown",
  "global:PerformanceObserver": "性能类 API 未建模，接受 unknown",
  "global:PerformanceObserverEntryList": "性能类 API 未建模，接受 unknown",
  "global:PerformanceResourceTiming": "性能类 API 未建模，接受 unknown",
  "global:QuotaExceededError": "Error 形宿主异常，未入 ERROR_CTOR_NAMES，接受 unknown",
  "global:ReadableByteStreamController": "WHATWG 流未建模，接受 unknown",
  "global:ReadableStream": "WHATWG 流未建模，接受 unknown",
  "global:ReadableStreamBYOBReader": "WHATWG 流未建模，接受 unknown",
  "global:ReadableStreamBYOBRequest": "WHATWG 流未建模，接受 unknown",
  "global:ReadableStreamDefaultController": "WHATWG 流未建模，接受 unknown",
  "global:ReadableStreamDefaultReader": "WHATWG 流未建模，接受 unknown",
  "global:Request": "fetch 族数据面未建模，接受 unknown",
  "global:Response": "fetch 族数据面未建模，接受 unknown",
  "global:sessionStorage": "存储 API 未建模，接受 unknown",
  "global:localStorage": "存储 API 未建模，接受 unknown",
  "global:Storage": "存储 API 未建模，接受 unknown",
  "global:SubtleCrypto": "WebCrypto 未建模，接受 unknown",
  "global:SuppressedError": "Error 形宿主异常，未入 ERROR_CTOR_NAMES，接受 unknown",
  "global:Temporal": "Temporal 未建模，接受 unknown",
  "global:TextDecoderStream": "流式编解码未建模，接受 unknown",
  "global:TextEncoder": "编码器未建模（TextDecoder 已有构造面），接受 unknown",
  "global:TextEncoderStream": "流式编解码未建模，接受 unknown",
  "global:TransformStream": "WHATWG 流未建模，接受 unknown",
  "global:TransformStreamDefaultController": "WHATWG 流未建模，接受 unknown",
  "global:URLPattern": "URL 模式匹配未建模，接受 unknown",
  "global:WebAssembly": "命名空间未建模，接受 unknown",
  "global:WritableStream": "WHATWG 流未建模，接受 unknown",
  "global:WritableStreamDefaultController": "WHATWG 流未建模，接受 unknown",
  "global:WritableStreamDefaultWriter": "WHATWG 流未建模，接受 unknown",
  "global:clearImmediate": "定时器清理面未建模（仅 set* 被拦截），接受 unknown",
  "global:clearInterval": "定时器清理面未建模，接受 unknown",
  "global:clearTimeout": "定时器清理面未建模，接受 unknown",
  "global:console": "调试面未建模，接受 unknown（任务口径）",
  "global:global": "Node legacy 全局别名未建模，接受 unknown",
  "global:globalThis": "无专属 case；读取走 env 全局绑定口径，接受 unknown",
  "global:process": "Node 宿主对象未建模，接受 unknown",
  "global:structuredClone": "结构化克隆未建模，接受 unknown",

  // ---- CJS 模块包装局部（仅 CJS/worker 上下文存在；ESM 源不适用） ---------
  "global:__dirname": "CJS 包装局部，非引擎面；ESM 源不适用，接受 unknown",
  "global:__filename": "CJS 包装局部，非引擎面；ESM 源不适用，接受 unknown",
  "global:exports": "CJS 包装局部，接受 unknown",
  "global:module": "CJS 包装局部，接受 unknown",
  "global:require": "CJS 互操作面未建模（ESM 分析面 require 不适用），接受 unknown",
  // vitest 测试运行器注入（仅测试上下文存在；非产品宿主面）
  "global:__vitest_index__": "vitest 运行器注入索引绑定，非产品宿主面，接受 unknown",
  "global:__vitest_mocker__": "vitest 运行器注入 mocker 绑定，非产品宿主面，接受 unknown",
  "global:__vitest_required__": "vitest 运行器注入 CJS 桥绑定，非产品宿主面，接受 unknown",
  "global:__vitest_worker__": "vitest worker 注入绑定，非产品宿主面，接受 unknown",

  // ---- Object 面 -----------------------------------------------------------
  "Object.static.groupBy": "Object.groupBy 未建模，接受 unknown",
  "Object.proto.__defineGetter__": "Annex B 访问器未建模，接受 unknown",
  "Object.proto.__defineSetter__": "Annex B 访问器未建模，接受 unknown",
  "Object.proto.__lookupGetter__": "Annex B 访问器未建模，接受 unknown",
  "Object.proto.__lookupSetter__": "Annex B 访问器未建模，接受 unknown",
  "Object.proto.__proto__": "Annex B 原型访问器未建模，接受 unknown",

  // ---- Array / String / Number ---------------------------------------------
  "String.proto.isWellFormed": "仅入 STRING_METHODS 缺失判定表；求值未建模，接受 unknown",
  "String.proto.toWellFormed": "仅入 STRING_METHODS 缺失判定表；求值未建模，接受 unknown",

  // ---- Symbol / BigInt / Promise -------------------------------------------
  "BigInt.proto.toLocaleString": "调用未建模（toString/valueOf 已折），接受 unknown",
  "Promise.static.try": "Promise.try 未建模，接受 unknown",

  // ---- Map / Set 集合新方法 -------------------------------------------------
  "Map.static.groupBy": "Map.groupBy 未建模，接受 unknown",
  "Map.proto.getOrInsert": "未建模，接受 unknown",
  "Map.proto.getOrInsertComputed": "未建模，接受 unknown",
  "WeakMap.proto.getOrInsert": "未建模，接受 unknown",
  "WeakMap.proto.getOrInsertComputed": "未建模，接受 unknown",
  "Set.proto.difference": "Set 集合运算未建模，接受 unknown",
  "Set.proto.intersection": "Set 集合运算未建模，接受 unknown",
  "Set.proto.isDisjointFrom": "Set 集合运算未建模，接受 unknown",
  "Set.proto.isSubsetOf": "Set 集合运算未建模，接受 unknown",
  "Set.proto.isSupersetOf": "Set 集合运算未建模，接受 unknown",
  "Set.proto.symmetricDifference": "Set 集合运算未建模，接受 unknown",
  "Set.proto.union": "Set 集合运算未建模，接受 unknown",

  // ---- Date / RegExp -------------------------------------------------------
  "Date.proto.toTemporalInstant": "Temporal 桥未建模，接受 unknown",
  "RegExp.static.$1": "Annex B 遗留静态属性未建模，接受 unknown",
  "RegExp.static.$2": "Annex B 遗留静态属性未建模，接受 unknown",
  "RegExp.static.$3": "Annex B 遗留静态属性未建模，接受 unknown",
  "RegExp.static.$4": "Annex B 遗留静态属性未建模，接受 unknown",
  "RegExp.static.$5": "Annex B 遗留静态属性未建模，接受 unknown",
  "RegExp.static.$6": "Annex B 遗留静态属性未建模，接受 unknown",
  "RegExp.static.$7": "Annex B 遗留静态属性未建模，接受 unknown",
  "RegExp.static.$8": "Annex B 遗留静态属性未建模，接受 unknown",
  "RegExp.static.$9": "Annex B 遗留静态属性未建模，接受 unknown",
  "RegExp.static.$_": "Annex B 遗留静态属性未建模，接受 unknown",
  "RegExp.static.$&": "Annex B 遗留静态属性未建模，接受 unknown",
  "RegExp.static.$`": "Annex B 遗留静态属性未建模，接受 unknown",
  "RegExp.static.$'": "Annex B 遗留静态属性未建模，接受 unknown",
  "RegExp.static.$+": "Annex B 遗留静态属性未建模，接受 unknown",
  "RegExp.static.escape": "RegExp.escape 未建模，接受 unknown",
  "RegExp.static.input": "Annex B 遗留静态属性未建模，接受 unknown",
  "RegExp.static.lastMatch": "Annex B 遗留静态属性未建模，接受 unknown",
  "RegExp.static.lastParen": "Annex B 遗留静态属性未建模，接受 unknown",
  "RegExp.static.leftContext": "Annex B 遗留静态属性未建模，接受 unknown",
  "RegExp.static.rightContext": "Annex B 遗留静态属性未建模，接受 unknown",
  "RegExp.proto.compile": "RegExp.prototype.compile 未建模，接受 unknown",
  "RegExp.proto.unicodeSets": "v 标志槽未入 REGEX_FLAG_SLOTS（仅 7 标志），接受 unknown",

  // ---- Error 家族静态面 / V8 扩展 ------------------------------------------
  "Error.static.captureStackTrace": "V8 扩展未建模，接受 unknown",
  "Error.static.isError": "未建模，接受 unknown",
  "Error.static.prepareStackTrace": "V8 扩展未建模，接受 unknown",
  "Error.static.stackTraceLimit": "V8 扩展未建模，接受 unknown",
  "TypeError.static.prototype": "Error 子类未入 NAMESPACE_GLOBALS，prototype 值读未建模，接受 unknown",
  "RangeError.static.prototype": "Error 子类未入 NAMESPACE_GLOBALS，接受 unknown",
  "ReferenceError.static.prototype": "Error 子类未入 NAMESPACE_GLOBALS，接受 unknown",
  "SyntaxError.static.prototype": "Error 子类未入 NAMESPACE_GLOBALS，接受 unknown",
  "EvalError.static.prototype": "Error 子类未入 NAMESPACE_GLOBALS，接受 unknown",
  "URIError.static.prototype": "Error 子类未入 NAMESPACE_GLOBALS，接受 unknown",
  "AggregateError.static.prototype": "Error 子类未入 NAMESPACE_GLOBALS，接受 unknown",

  // ---- ArrayBuffer / DataView / TypedArray ----------------------------------
  "ArrayBuffer.static.prototype": "未入 NAMESPACE_GLOBALS，prototype 值读未建模，接受 unknown",
  "ArrayBuffer.static.isView": "未建模，接受 unknown",
  "ArrayBuffer.proto.detached": "未建模，接受 unknown",
  "ArrayBuffer.proto.resize": "resize 调用未建模（仅构造期 maxByteLength 校验），接受 unknown",
  "ArrayBuffer.proto.slice": "未建模，接受 unknown",
  "ArrayBuffer.proto.transfer": "未建模，接受 unknown",
  "ArrayBuffer.proto.transferToFixedLength": "未建模，接受 unknown",
  "SharedArrayBuffer.static.prototype": "未入 NAMESPACE_GLOBALS，接受 unknown",
  "SharedArrayBuffer.proto.grow": "grow 调用未建模，接受 unknown",
  "SharedArrayBuffer.proto.slice": "未建模，接受 unknown",
  "DataView.static.prototype": "未入 NAMESPACE_GLOBALS，接受 unknown",
  "DataView.proto.buffer": "槽未建模（仅 byteOffset/byteLength 槽），接受 unknown",
  "DataView.proto.getBigInt64": "存取方法未建模，接受 unknown",
  "DataView.proto.getBigUint64": "存取方法未建模，接受 unknown",
  "DataView.proto.getFloat16": "存取方法未建模，接受 unknown",
  "DataView.proto.getFloat32": "存取方法未建模，接受 unknown",
  "DataView.proto.getFloat64": "存取方法未建模，接受 unknown",
  "DataView.proto.getInt16": "存取方法未建模，接受 unknown",
  "DataView.proto.getInt32": "存取方法未建模，接受 unknown",
  "DataView.proto.getInt8": "存取方法未建模，接受 unknown",
  "DataView.proto.getUint16": "存取方法未建模，接受 unknown",
  "DataView.proto.getUint32": "存取方法未建模，接受 unknown",
  "DataView.proto.getUint8": "存取方法未建模，接受 unknown",
  "DataView.proto.setBigInt64": "存取方法未建模，接受 unknown",
  "DataView.proto.setBigUint64": "存取方法未建模，接受 unknown",
  "DataView.proto.setFloat16": "存取方法未建模，接受 unknown",
  "DataView.proto.setFloat32": "存取方法未建模，接受 unknown",
  "DataView.proto.setFloat64": "存取方法未建模，接受 unknown",
  "DataView.proto.setInt16": "存取方法未建模，接受 unknown",
  "DataView.proto.setInt32": "存取方法未建模，接受 unknown",
  "DataView.proto.setInt8": "存取方法未建模，接受 unknown",
  "DataView.proto.setUint16": "存取方法未建模，接受 unknown",
  "DataView.proto.setUint32": "存取方法未建模，接受 unknown",
  "DataView.proto.setUint8": "存取方法未建模，接受 unknown",

  // ---- TypedArray 静态/常量面（元素域已建模，构造器面未入身份路由表） -------
  "Float16Array.static.prototype": "未入 NAMESPACE_GLOBALS，接受 unknown",
  "Float16Array.static.BYTES_PER_ELEMENT": "未建模，接受 unknown",
  "Float16Array.proto.BYTES_PER_ELEMENT": "未建模，接受 unknown",
  "Uint8Array.static.prototype": "未入 NAMESPACE_GLOBALS，接受 unknown",
  "Uint8Array.static.BYTES_PER_ELEMENT": "未建模，接受 unknown",
  "Uint8Array.static.fromBase64": "base64/hex 提案面未建模，接受 unknown",
  "Uint8Array.static.fromHex": "base64/hex 提案面未建模，接受 unknown",
  "Uint8Array.proto.BYTES_PER_ELEMENT": "未建模，接受 unknown",
  "Uint8Array.proto.setFromBase64": "base64/hex 提案面未建模，接受 unknown",
  "Uint8Array.proto.setFromHex": "base64/hex 提案面未建模，接受 unknown",
  "Uint8Array.proto.toBase64": "base64/hex 提案面未建模，接受 unknown",
  "Uint8Array.proto.toHex": "base64/hex 提案面未建模，接受 unknown",
  "Uint8ClampedArray.static.prototype": "未入 NAMESPACE_GLOBALS，接受 unknown",
  "Uint8ClampedArray.static.BYTES_PER_ELEMENT": "未建模，接受 unknown",
  "Uint8ClampedArray.proto.BYTES_PER_ELEMENT": "未建模，接受 unknown",
  "Int8Array.static.prototype": "未入 NAMESPACE_GLOBALS，接受 unknown",
  "Int8Array.static.BYTES_PER_ELEMENT": "未建模，接受 unknown",
  "Int8Array.proto.BYTES_PER_ELEMENT": "未建模，接受 unknown",
  "Uint16Array.static.prototype": "未入 NAMESPACE_GLOBALS，接受 unknown",
  "Uint16Array.static.BYTES_PER_ELEMENT": "未建模，接受 unknown",
  "Uint16Array.proto.BYTES_PER_ELEMENT": "未建模，接受 unknown",
  "Int16Array.static.prototype": "未入 NAMESPACE_GLOBALS，接受 unknown",
  "Int16Array.static.BYTES_PER_ELEMENT": "未建模，接受 unknown",
  "Int16Array.proto.BYTES_PER_ELEMENT": "未建模，接受 unknown",
  "Uint32Array.static.prototype": "未入 NAMESPACE_GLOBALS，接受 unknown",
  "Uint32Array.static.BYTES_PER_ELEMENT": "未建模，接受 unknown",
  "Uint32Array.proto.BYTES_PER_ELEMENT": "未建模，接受 unknown",
  "Int32Array.static.prototype": "未入 NAMESPACE_GLOBALS，接受 unknown",
  "Int32Array.static.BYTES_PER_ELEMENT": "未建模，接受 unknown",
  "Int32Array.proto.BYTES_PER_ELEMENT": "未建模，接受 unknown",
  "Float32Array.static.prototype": "未入 NAMESPACE_GLOBALS，接受 unknown",
  "Float32Array.static.BYTES_PER_ELEMENT": "未建模，接受 unknown",
  "Float32Array.proto.BYTES_PER_ELEMENT": "未建模，接受 unknown",
  "Float64Array.static.prototype": "未入 NAMESPACE_GLOBALS，接受 unknown",
  "Float64Array.static.BYTES_PER_ELEMENT": "未建模，接受 unknown",
  "Float64Array.proto.BYTES_PER_ELEMENT": "未建模，接受 unknown",
  "BigInt64Array.static.prototype": "未入 NAMESPACE_GLOBALS，接受 unknown",
  "BigInt64Array.static.BYTES_PER_ELEMENT": "未建模，接受 unknown",
  "BigInt64Array.proto.BYTES_PER_ELEMENT": "未建模，接受 unknown",
  "BigUint64Array.static.prototype": "未入 NAMESPACE_GLOBALS，接受 unknown",
  "BigUint64Array.static.BYTES_PER_ELEMENT": "未建模，接受 unknown",
  "BigUint64Array.proto.BYTES_PER_ELEMENT": "未建模，接受 unknown",

  // ---- URL / URLSearchParams / TextDecoder / TextEncoder --------------------
  "URL.static.createObjectURL": "blob URL 面未建模，接受 unknown",
  "URL.static.parse": "未建模（仅 canParse 派发），接受 unknown",
  "URL.static.revokeObjectURL": "blob URL 面未建模，接受 unknown",
  "URL.proto.searchParams": "组件槽未含 searchParams（10 组件外），接受 unknown",
  "URL.proto.toString": "brand toString 值读未入方法表（toJSON 已接管），接受 unknown",
  "URLSearchParams.static.prototype": "未入 NAMESPACE_GLOBALS，接受 unknown",
  "URLSearchParams.proto.append": "条目表不建模（空 brand 口径），接受 unknown",
  "URLSearchParams.proto.delete": "条目表不建模，接受 unknown",
  "URLSearchParams.proto.entries": "条目表不建模，接受 unknown",
  "URLSearchParams.proto.forEach": "条目表不建模，接受 unknown",
  "URLSearchParams.proto.get": "条目表不建模，接受 unknown",
  "URLSearchParams.proto.getAll": "条目表不建模，接受 unknown",
  "URLSearchParams.proto.has": "条目表不建模，接受 unknown",
  "URLSearchParams.proto.keys": "条目表不建模，接受 unknown",
  "URLSearchParams.proto.set": "条目表不建模，接受 unknown",
  "URLSearchParams.proto.size": "条目表不建模，接受 unknown",
  "URLSearchParams.proto.sort": "条目表不建模，接受 unknown",
  "URLSearchParams.proto.toString": "条目表不建模，接受 unknown",
  "URLSearchParams.proto.values": "条目表不建模，接受 unknown",
  "TextDecoder.static.prototype": "未入 NAMESPACE_GLOBALS，接受 unknown",
  "TextDecoder.proto.decode": "解码调用未建模（构造+encoding 槽已派发），接受 unknown",
  "TextDecoder.proto.fatal": "options 不校验、槽未建模，接受 unknown",
  "TextDecoder.proto.ignoreBOM": "options 不校验、槽未建模，接受 unknown",
  "TextEncoder.static.prototype": "未入 NAMESPACE_GLOBALS，接受 unknown",
  "TextEncoder.proto.encode": "未建模，接受 unknown",
  "TextEncoder.proto.encodeInto": "未建模，接受 unknown",
  "TextEncoder.proto.encoding": "未建模，接受 unknown",

  // ---- WeakRef / FinalizationRegistry / Proxy -------------------------------
  "WeakRef.static.prototype": "未入 NAMESPACE_GLOBALS，接受 unknown",
  "WeakRef.proto.deref": "未建模，接受 unknown",
  "FinalizationRegistry.static.prototype": "未入 NAMESPACE_GLOBALS，接受 unknown",
  "Proxy.static.revocable": "未建模（仅 Proxy(target,handler) 构造面），接受 unknown",

  // ---- JSON / Math 之外 -----------------------------------------------------
  "JSON.static.isRawJSON": "JSON source-text-access 面未建模，接受 unknown",
  "JSON.static.rawJSON": "JSON source-text-access 面未建模，接受 unknown",

  // ---- Intl：任务口径「Intl 非 ctor 成员与格式化面」全未建模，接受 unknown --
  "Intl.ns.Collator": "Intl 成员未建模，接受 unknown",
  "Intl.ns.DisplayNames": "Intl 成员未建模，接受 unknown",
  "Intl.ns.DurationFormat": "Intl 成员未建模，接受 unknown",
  "Intl.ns.ListFormat": "Intl 成员未建模，接受 unknown",
  "Intl.ns.Locale": "Intl 成员未建模，接受 unknown",
  "Intl.ns.PluralRules": "Intl 成员未建模，接受 unknown",
  "Intl.ns.RelativeTimeFormat": "Intl 成员未建模，接受 unknown",
  "Intl.ns.Segmenter": "Intl 成员未建模，接受 unknown",
  "Intl.ns.getCanonicalLocales": "未建模，接受 unknown",
  "Intl.ns.supportedValuesOf": "未建模，接受 unknown",
  "Intl.Collator.static.prototype": "未建模，接受 unknown",
  "Intl.Collator.static.supportedLocalesOf": "未建模，接受 unknown",
  "Intl.Collator.proto.compare": "未建模，接受 unknown",
  "Intl.Collator.proto.resolvedOptions": "未建模，接受 unknown",
  "Intl.DateTimeFormat.static.supportedLocalesOf": "未建模，接受 unknown",
  "Intl.DateTimeFormat.proto.format": "未建模，接受 unknown",
  "Intl.DateTimeFormat.proto.formatRange": "未建模，接受 unknown",
  "Intl.DateTimeFormat.proto.formatRangeToParts": "未建模，接受 unknown",
  "Intl.DateTimeFormat.proto.formatToParts": "未建模，接受 unknown",
  "Intl.DateTimeFormat.proto.resolvedOptions": "未建模，接受 unknown",
  "Intl.DisplayNames.static.prototype": "未建模，接受 unknown",
  "Intl.DisplayNames.static.supportedLocalesOf": "未建模，接受 unknown",
  "Intl.DisplayNames.proto.of": "未建模，接受 unknown",
  "Intl.DisplayNames.proto.resolvedOptions": "未建模，接受 unknown",
  "Intl.ListFormat.static.prototype": "未建模，接受 unknown",
  "Intl.ListFormat.static.supportedLocalesOf": "未建模，接受 unknown",
  "Intl.ListFormat.proto.format": "未建模，接受 unknown",
  "Intl.ListFormat.proto.formatToParts": "未建模，接受 unknown",
  "Intl.ListFormat.proto.resolvedOptions": "未建模，接受 unknown",
  "Intl.Locale.static.prototype": "未建模，接受 unknown",
  "Intl.Locale.proto.baseName": "未建模，接受 unknown",
  "Intl.Locale.proto.calendar": "未建模，接受 unknown",
  "Intl.Locale.proto.caseFirst": "未建模，接受 unknown",
  "Intl.Locale.proto.collation": "未建模，接受 unknown",
  "Intl.Locale.proto.firstDayOfWeek": "未建模，接受 unknown",
  "Intl.Locale.proto.getCalendars": "未建模，接受 unknown",
  "Intl.Locale.proto.getCollations": "未建模，接受 unknown",
  "Intl.Locale.proto.getHourCycles": "未建模，接受 unknown",
  "Intl.Locale.proto.getNumberingSystems": "未建模，接受 unknown",
  "Intl.Locale.proto.getTextInfo": "未建模，接受 unknown",
  "Intl.Locale.proto.getTimeZones": "未建模，接受 unknown",
  "Intl.Locale.proto.getWeekInfo": "未建模，接受 unknown",
  "Intl.Locale.proto.hourCycle": "未建模，接受 unknown",
  "Intl.Locale.proto.language": "未建模，接受 unknown",
  "Intl.Locale.proto.maximize": "未建模，接受 unknown",
  "Intl.Locale.proto.minimize": "未建模，接受 unknown",
  "Intl.Locale.proto.numeric": "未建模，接受 unknown",
  "Intl.Locale.proto.numberingSystem": "未建模，接受 unknown",
  "Intl.Locale.proto.region": "未建模，接受 unknown",
  "Intl.Locale.proto.script": "未建模，接受 unknown",
  "Intl.Locale.proto.toString": "未建模，接受 unknown",
  "Intl.NumberFormat.static.supportedLocalesOf": "未建模，接受 unknown",
  "Intl.NumberFormat.proto.format": "未建模，接受 unknown",
  "Intl.NumberFormat.proto.formatRange": "未建模，接受 unknown",
  "Intl.NumberFormat.proto.formatRangeToParts": "未建模，接受 unknown",
  "Intl.NumberFormat.proto.formatToParts": "未建模，接受 unknown",
  "Intl.NumberFormat.proto.resolvedOptions": "未建模，接受 unknown",
  "Intl.PluralRules.static.prototype": "未建模，接受 unknown",
  "Intl.PluralRules.static.supportedLocalesOf": "未建模，接受 unknown",
  "Intl.PluralRules.proto.resolvedOptions": "未建模，接受 unknown",
  "Intl.PluralRules.proto.select": "未建模，接受 unknown",
  "Intl.PluralRules.proto.selectRange": "未建模，接受 unknown",
  "Intl.RelativeTimeFormat.static.prototype": "未建模，接受 unknown",
  "Intl.RelativeTimeFormat.static.supportedLocalesOf": "未建模，接受 unknown",
  "Intl.RelativeTimeFormat.proto.format": "未建模，接受 unknown",
  "Intl.RelativeTimeFormat.proto.formatToParts": "未建模，接受 unknown",
  "Intl.RelativeTimeFormat.proto.resolvedOptions": "未建模，接受 unknown",
  "Intl.Segmenter.static.prototype": "未建模，接受 unknown",
  "Intl.Segmenter.static.supportedLocalesOf": "未建模，接受 unknown",
  "Intl.Segmenter.proto.resolvedOptions": "未建模，接受 unknown",
  "Intl.Segmenter.proto.segment": "未建模，接受 unknown",
  "Intl.DurationFormat.static.prototype": "未建模，接受 unknown",
  "Intl.DurationFormat.static.supportedLocalesOf": "未建模，接受 unknown",
  "Intl.DurationFormat.proto.format": "未建模，接受 unknown",
  "Intl.DurationFormat.proto.formatToParts": "未建模，接受 unknown",
  "Intl.DurationFormat.proto.resolvedOptions": "未建模，接受 unknown",
};

/**
 * VERSION_SKEW：存在性随 Node 版本/执行上下文漂移的登记键（僵尸检查豁免）。
 * 这些键仍必须先在 MODELED/ALLOWED_IMPRECISE 登记过；此表只防跨版本假僵尸。
 */
export const VERSION_SKEW: ReadonlySet<string> = new Set([
  // 新 Stage 提案/新版本宿主面（老 Node 可能缺席）
  "global:Temporal",
  "global:URLPattern",
  "global:QuotaExceededError",
  "global:SuppressedError",
  "global:DisposableStack",
  "global:AsyncDisposableStack",
  "global:Float16Array",
  "global:Iterator",
  "global:localStorage",
  "global:sessionStorage",
  "global:Storage",
  "Float16Array.static.prototype",
  "Float16Array.static.BYTES_PER_ELEMENT",
  "Float16Array.proto.BYTES_PER_ELEMENT",
  "Math.static.f16round",
  "Promise.static.try",
  "Map.proto.getOrInsert",
  "Map.proto.getOrInsertComputed",
  "WeakMap.proto.getOrInsert",
  "WeakMap.proto.getOrInsertComputed",
  "Uint8Array.static.fromBase64",
  "Uint8Array.static.fromHex",
  "Uint8Array.proto.toBase64",
  "Uint8Array.proto.toHex",
  "Uint8Array.proto.setFromBase64",
  "Uint8Array.proto.setFromHex",
  "JSON.static.rawJSON",
  "JSON.static.isRawJSON",
  "RegExp.static.escape",
  "RegExp.proto.unicodeSets",
  "URL.static.parse",
  "Date.proto.toTemporalInstant",
  "Error.static.isError",
  "ArrayBuffer.proto.resize",
  "ArrayBuffer.proto.transfer",
  "ArrayBuffer.proto.transferToFixedLength",
  "ArrayBuffer.proto.detached",
  "SharedArrayBuffer.proto.grow",
  "Intl.ns.DurationFormat",
  "Intl.DurationFormat.static.prototype",
  "Intl.DurationFormat.static.supportedLocalesOf",
  "Intl.DurationFormat.proto.format",
  "Intl.DurationFormat.proto.formatToParts",
  "Intl.DurationFormat.proto.resolvedOptions",
  // CJS 包装局部：仅 CJS/特定 worker 上下文暴露，ESM(vitest worker)常缺席
  "global:module",
  "global:exports",
  "global:require",
  "global:__dirname",
  "global:__filename",
  // vitest 运行器注入：名字随 vitest 版本变化，缺席是版本差异非台账腐化
  "global:__vitest_index__",
  "global:__vitest_mocker__",
  "global:__vitest_required__",
  "global:__vitest_worker__",
]);
