/**
 * nudo:interface-drift（T10a）：固化生成段 ≠ 今日重算 → warning。
 *
 * - 参数位 drift：@generated 快照 number().gt(0)，今日调用域吸收 -1 变宽 → 报
 * - emit 后快照与今日域一致（number() ↔ 字面量域并集投影）→ 无 issue
 * - 手写契约同场景不报 drift（drift 只对 generated；手写走执法 constraint-violated）
 * - §6 证据门槛：无证据（unknown 实参）不判 drift
 * - 返回位 drift 正例（快照 returns gt(0)，今日推断 lit(-1)）与一致反例
 * - 每 fn 每位最多一条（多调用点去重）
 */
import { describe, it, expect, beforeEach } from "vitest";
import { checkSource, pTrue } from "../index.ts";
import { resetCheckSourceMemo } from "../check.ts";
import { resetGeneralizeMemo } from "../generalize.ts";
import { takeInterfaceDiags } from "../interface.ts";
import { takeRefineDiags } from "../refine.ts";

/** 虚拟文件系统 loader：相对 spec 按 fromFile 目录解析 */
function makeFiles(files: Record<string, string>) {
  const resolve = (from: string, spec: string): string => {
    if (!spec.startsWith(".")) return spec;
    const parts = from.split("/").slice(0, -1);
    for (const seg of spec.split("/")) {
      if (seg === "." || seg === "") continue;
      if (seg === "..") parts.pop();
      else parts.push(seg);
    }
    return parts.join("/");
  };
  return {
    loadModule: (spec: string, from: string): string | undefined =>
      files[resolve(from, spec)],
  };
}

const GEN = (body: string) =>
  `import { fn, number } from "@nudojs/core";\n// @generated by nudo — do not edit\n${body}`;

describe("nudo:interface-drift（固化生成段 ≠ 今日重算）", () => {
  beforeEach(() => {
    resetCheckSourceMemo();
    resetGeneralizeMemo();
    takeRefineDiags();
    takeInterfaceDiags();
  });

  it("参数域变宽：快照 gt(0)，今日调用域吸收 -1 → 一条 drift warning", () => {
    const { loadModule } = makeFiles({
      "/t/area.nudo.js": GEN(`export const area = fn({ x: number().gt(0) });`),
    });
    const src = `
export function area(x) {
  return x;
}
area(5);
area(-1);
area(7);
`;
    const r = checkSource("/t/area.js", src, pTrue, {
      loadModule,
      fromFile: "/t/area.js",
    });
    const drifts = r.issues.filter((i) => i.code === "nudo:interface-drift");
    expect(drifts.length).toBe(1);
    expect(drifts[0]!.severity).toBe("warning");
    expect(drifts[0]!.fn).toBe("area");
    expect(drifts[0]!.message).toContain("area");
    expect(drifts[0]!.message).toContain("x");
    expect(drifts[0]!.expected).toBe("number().gt(0)");
    expect(drifts[0]!.actual).toContain("number");
    // warning 不破门禁（generated 不执法）
    expect(r.ok).toBe(true);
  });

  it("emit 后快照与今日字面量域一致（union(lit…)）→ 无 issue", () => {
    // joinThenProject 的字面量快路径产出 union(lit…)，快照与今日同构时零 drift。
    // 快照若是 number() 而今日是 {1,-2} 字面量集——语义不等，会报 drift（见下一条）。
    const { loadModule } = makeFiles({
      "/t/area.nudo.js": GEN(
        `export const area = fn({ x: union(lit(1), lit(-2)) }, union(lit(1), lit(-2)));`,
      ),
    });
    const src = `
export function area(x) {
  return x;
}
area(1);
area(-2);
`;
    const r = checkSource("/t/area.js", src, pTrue, {
      loadModule,
      fromFile: "/t/area.js",
    });
    expect(
      r.issues.filter((i) => i.code === "nudo:interface-drift"),
    ).toEqual([]);
    expect(r.ok).toBe(true);
  });

  it("快照 number() vs 今日字面量集 {1,-2} → drift（语义不等，不再靠 join 塌缩掩盖）", () => {
    const { loadModule } = makeFiles({
      "/t/area.nudo.js": GEN(`export const area = fn({ x: number() }, number());`),
    });
    const src = `
export function area(x) {
  return x;
}
area(1);
area(-2);
`;
    const r = checkSource("/t/area.js", src, pTrue, {
      loadModule,
      fromFile: "/t/area.js",
    });
    const drifts = r.issues.filter((i) => i.code === "nudo:interface-drift");
    expect(drifts.length).toBeGreaterThanOrEqual(1);
    expect(drifts[0]!.fn).toBe("area");
  });

  it("字面量 union 快照被更宽调用域吸收 → drift（同 prim 不塌缩）", () => {
    // 回归：joinValues 对同 prim 双字面量曾急切塌成裸 number，导致
    // union(lit(5),lit(7)) 与 union(lit(5),lit(7),lit(-1)) 在 entry Abs
    // 下不可区分——drift 漏报。entry Abs 现走 or(eq…) 保留字面量域。
    const { loadModule } = makeFiles({
      "/t/area.nudo.js": GEN(
        `export const area = fn({ x: union(lit(5), lit(7)) }, union(lit(5), lit(7)));`,
      ),
    });
    const src = `
export function area(x) {
  return x;
}
area(5);
area(7);
area(-1);
`;
    const r = checkSource("/t/area.js", src, pTrue, {
      loadModule,
      fromFile: "/t/area.js",
    });
    const drifts = r.issues.filter((i) => i.code === "nudo:interface-drift");
    expect(drifts.length).toBeGreaterThanOrEqual(1);
    expect(drifts[0]!.fn).toBe("area");
  });

  it("执行态证据：兄弟函数内未执行的调用不进今日域（fresh emit 零 drift）", () => {
    // 回归（T10a）：语法全树扫描曾把 process() 体内从未执行的 area(-50)
    // 算进今日域 → fresh emit 后立即误报 drift 且重跑 emit 无法消除；
    // 今日域证据必须与 emit 同为执行态（AbsCallRecord，host 模块图求值收集）
    const { loadModule } = makeFiles({
      "/t/area.nudo.js": GEN(`export const area = fn({ x: lit(3) }, lit(3));`),
    });
    const src = `
export function area(x) {
  return x;
}
export function process() {
  return area(-50);
}
area(3);
`;
    const r2 = checkSource("/t/area.js", src, pTrue, {
      loadModule,
      fromFile: "/t/area.js",
    });
    expect(
      r2.issues.filter((i) => i.code === "nudo:interface-drift"),
    ).toEqual([]);
    expect(r2.ok).toBe(true);
  });

  it("兄弟函数被调用后其内部调用进今日域 → 真 drift", () => {
    // process() 在顶层被调用 → area(-50) 真实执行，今日域吸收 -50
    const { loadModule } = makeFiles({
      "/t/area.nudo.js": GEN(`export const area = fn({ x: lit(3) }, lit(3));`),
    });
    const src = `
export function area(x) {
  return x;
}
export function process() {
  return area(-50);
}
area(3);
process();
`;
    const r3 = checkSource("/t/area.js", src, pTrue, {
      loadModule,
      fromFile: "/t/area.js",
    });
    const drifts = r3.issues.filter((i) => i.code === "nudo:interface-drift");
    expect(drifts.length).toBeGreaterThanOrEqual(1);
    expect(drifts[0]!.fn).toBe("area");
  });

  it("手写契约同场景不报 drift（执法走 constraint-violated）", () => {
    const { loadModule } = makeFiles({
      "/t/area.nudo.js": `import { fn, number } from "@nudojs/core";\nexport const area = fn({ x: number().gt(0) });`,
    });
    const src = `
export function area(x) {
  return x;
}
area(-1);
`;
    const r = checkSource("/t/area.js", src, pTrue, {
      loadModule,
      fromFile: "/t/area.js",
    });
    const violation = r.issues.find((i) => i.code === "nudo:constraint-violated");
    expect(violation).toBeDefined();
    expect(violation!.fn).toBe("area");
    expect(r.issues.filter((i) => i.code === "nudo:interface-drift")).toEqual([]);
    expect(r.ok).toBe(false);
  });

  it("无证据（unknown 实参）不判 drift", () => {
    const { loadModule } = makeFiles({
      "/t/area.nudo.js": GEN(`export const area = fn({ x: number().gt(0) });`),
    });
    const src = `
export function area(x) {
  return x;
}
area(u);
`;
    const r = checkSource("/t/area.js", src, pTrue, {
      loadModule,
      fromFile: "/t/area.js",
    });
    expect(
      r.issues.filter((i) => i.code === "nudo:interface-drift"),
    ).toEqual([]);
    expect(r.ok).toBe(true);
  });

  it("返回位 drift 正例：快照 returns gt(0)，今日调用点结果 lit(-1)", () => {
    const { loadModule } = makeFiles({
      "/t/ret.nudo.js": GEN(
        `export const ret = fn({ x: number() }, number().gt(0));`,
      ),
    });
    const src = `
export function ret(x) {
  return -1;
}
ret(1);
ret(-2);
`;
    const r = checkSource("/t/ret.js", src, pTrue, {
      loadModule,
      fromFile: "/t/ret.js",
    });
    const drifts = r.issues.filter((i) => i.code === "nudo:interface-drift");
    // 参数位：快照 number()，今日 {1,-2} 字面量集——语义不等（number ⊄ {1,-2}）
    // 也报 drift（域变化，§6）；返回位 lit(-1) ⊄ gt(0) 另一条
    expect(drifts.length).toBe(2);
    const retDrift = drifts.find((d) => d.message.includes("return"));
    expect(retDrift).toBeDefined();
    expect(retDrift!.severity).toBe("warning");
    expect(retDrift!.fn).toBe("ret");
    expect(retDrift!.expected).toBe("number().gt(0)");
    expect(retDrift!.actual).toContain("-1");
    expect(r.ok).toBe(true);
  });

  it("返回位一致：快照 returns gt(0)，今日推断 x>0 透传 → 无 drift", () => {
    const { loadModule } = makeFiles({
      "/t/ret.nudo.js": GEN(
        `export const ret = fn({ x: number().gt(0) }, number().gt(0));`,
      ),
    });
    const src = `
export function ret(x) {
  return x;
}
`;
    const r = checkSource("/t/ret.js", src, pTrue, {
      loadModule,
      fromFile: "/t/ret.js",
    });
    expect(
      r.issues.filter((i) => i.code === "nudo:interface-drift"),
    ).toEqual([]);
    expect(r.ok).toBe(true);
  });

  it("fresh emit 后 check 零 drift（返回位与 emit 证据同源，不误报）", () => {
    // 回归：返回位曾用 generalize 符号 Abs 对比，emit 的逐 case 精确结果
    // （lit(8)）与符号返回（number = return where typeof return = "number"）
    // 语义不等 → 每次 fresh emit 后 check 都误报返回位 drift。
    const { loadModule } = makeFiles({
      "/t/double.nudo.js": GEN(
        `export const double = fn({ x: lit(4) }, lit(8));`,
      ),
    });
    const src = `
export function double(x) {
  return x + x;
}
double(4);
`;
    const r = checkSource("/t/double.js", src, pTrue, {
      loadModule,
      fromFile: "/t/double.js",
    });
    expect(
      r.issues.filter((i) => i.code === "nudo:interface-drift"),
    ).toEqual([]);
    expect(r.ok).toBe(true);
  });
});
