import { describe, it, expect } from "vitest";
import { checkSource, pTrue } from "../index.ts";
import { withStdImport, stdOpts, stdLoadModule } from "./nudo-constraints.ts";

/**
 * nudo check 金标：多形态 JS 片段上的门禁行为。
 * 每条：source + 期望 ok / 期望出现的 issue code。
 */

type Gold = {
  name: string;
  source: string;
  expectOk: boolean;
  expectCode?: string;
  /**
   * T10a drift 夹具：按 spec 键（如 "./file.nudo.js"）提供侧车内容，
   * 优先于 stdLoadModule（其对任意 .nudo.js 都回 STD 约束库）。
   */
  files?: Record<string, string>;
};

const golds: Gold[] = [
  {
    name: "valid positive call",
    source: `
/**
 * @nudo:refine x positive
 */
function needsPositive(x) {
  if (x > 0) return x;
  return 0;
}
const r = needsPositive(5);
`,
    expectOk: true,
  },
  {
    name: "negative call violates x>0",
    source: `
/**
 * @nudo:refine x positive
 */
function needsPositive(x) {
  if (x > 0) return x;
  return 0;
}
const r = needsPositive(-1);
`,
    expectOk: false,
    expectCode: "nudo:constraint-violated",
  },
  {
    name: "range guard lo is clamp not violation",
    source: `
function clampId(id) {
  if (id < 1) return 1;
  if (id > 9999) return 9999;
  return id;
}
clampId(0);
`,
    // `id < 1` 是回退守卫，不作为调用前置
    expectOk: true,
  },
  {
    name: "range guard valid mid",
    source: `
function clampId(id) {
  if (id < 1) return 1;
  if (id > 9999) return 9999;
  return id;
}
clampId(50);
`,
    expectOk: true,
  },
  {
    name: "pure arithmetic no constraints",
    source: `
function add(a, b) { return a + b; }
const r = add(1, 2);
`,
    expectOk: true,
  },
  {
    name: "ESM export function still listed",
    source: `
export function scale(x) { return x + 1; }
`,
    expectOk: true,
  },
  {
    name: "async function listed",
    source: `
export async function load(id) { return id + 1; }
`,
    expectOk: true,
  },
  {
    name: "class constructor listed",
    source: `
class Counter {
  constructor(n) { this.n = n; }
  get() { return this.n; }
}
export function main() { return new Counter(1).get(); }
`,
    expectOk: true,
  },
  // --- 真阳性：必须报 ---
  {
    name: "zero violates x>0",
    source: `
/**
 * @nudo:refine x positive
 */
function needsPositive(x) {
  if (x > 0) return x;
  return 0;
}
needsPositive(0);
`,
    expectOk: false,
    expectCode: "nudo:constraint-violated",
  },
  {
    name: "unary negative call",
    source: `
/**
 * @nudo:refine x positive
 */
function needsPositive(x) {
  if (x > 0) return x;
  return 0;
}
needsPositive(-3);
`,
    expectOk: false,
    expectCode: "nudo:constraint-violated",
  },
  {
    name: "x>=1 rejects 0",
    source: `
/**
 * @nudo:refine i atLeast1
 */
function idx(i) {
  if (i >= 1) return i;
  return 1;
}
idx(0);
`,
    expectOk: false,
    expectCode: "nudo:constraint-violated",
  },
  {
    name: "upper bound x<10 rejects 10",
    source: `
/**
 * @nudo:refine n small
 */
function small(n) {
  if (n < 10) return n;
  return 9;
}
small(10);
`,
    expectOk: false,
    expectCode: "nudo:constraint-violated",
  },
  // --- 真阴性：不得误报（clamp / 无前置） ---
  {
    name: "clamp negative input is not violation",
    source: `
function clamp(n, lo, hi) {
  if (n < lo) return lo;
  if (n > hi) return hi;
  return n;
}
clamp(-5, 0, 100);
`,
    expectOk: true,
  },
  {
    name: "no guard no constraint",
    source: `
function double(n) { return n * 2; }
double(-1);
`,
    expectOk: true,
  },
  {
    name: "equality guard is not numeric precondition",
    source: `
function onlyZero(x) {
  if (x === 0) return 0;
  return 1;
}
onlyZero(5);
`,
    expectOk: true,
  },
  {
    name: "min boundary valid",
    source: `
function needsPositive(x) {
  if (x > 0) return x;
  return 0;
}
needsPositive(1);
`,
    expectOk: true,
  },
  // --- 结构 ---
  {
    name: "arrow function constraint",
    source: `
/**
 * @nudo:refine x positive
 */
const needsPositive = (x) => {
  if (x > 0) return x;
  return 0;
};
needsPositive(-2);
`,
    expectOk: false,
    expectCode: "nudo:constraint-violated",
  },
  {
    name: "export default function",
    source: `
/**
 * @nudo:refine x positive
 */
export default function needsPositive(x) {
  if (x > 0) return x;
  return 0;
}
needsPositive(-1);
`,
    expectOk: false,
    expectCode: "nudo:constraint-violated",
  },
  {
    name: "both bounds mid valid",
    source: `
/**
 * @nudo:refine n percent
 */
function pct(n) {
  if (n >= 0 && n <= 100) return n;
  return 0;
}
pct(50);
`,
    expectOk: true,
  },
  {
    name: "both bounds high invalid",
    source: `
/**
 * @nudo:refine n percent
 */
function pct(n) {
  if (n >= 0 && n <= 100) return n;
  return 0;
}
pct(150);
`,
    expectOk: false,
    expectCode: "nudo:constraint-violated",
  },
  // --- T10a：固化生成段 drift（nudo:interface-drift，warning）---
  {
    name: "generated segment param drift warns",
    files: {
      "./file.nudo.js":
        'import { fn, number } from "@nudojs/core";\n// @generated by nudo — do not edit\nexport const area = fn({ x: number().gt(0) });',
    },
    source: `
export function area(x) {
  return x;
}
area(5);
area(-1);
`,
    // 快照 gt(0)；今日调用域吸收 -1 → 域变宽 ≠ 生成段（warning 不破门禁）
    expectOk: true,
    expectCode: "nudo:interface-drift",
  },
  {
    name: "generated segment matching domain is silent",
    files: {
      "./file.nudo.js":
        'import { fn, number } from "@nudojs/core";\n// @generated by nudo — do not edit\nexport const area = fn({ x: number() });',
    },
    source: `
export function area(x) {
  return x;
}
area(1);
area(-2);
`,
    // emit 后调用点未变：快照 number() 与今日域（字面量并集投影）一致
    expectOk: true,
  },
  {
    name: "handwritten contract same scenario enforces not drift",
    source: `
/**
 * @nudo:refine x positive
 */
export function area(x) {
  return x;
}
area(-1);
`,
    // 手写契约同场景：走执法 constraint-violated，drift 只对 generated
    expectOk: false,
    expectCode: "nudo:constraint-violated",
  },
];

describe("nudo check gold standards", () => {
  for (const g of golds) {
    it(g.name, () => {
      const opts = g.files
        ? {
            loadModule: (spec: string): string | undefined =>
              g.files![spec] ?? stdLoadModule(spec),
            fromFile: "/test/file.js",
          }
        : stdOpts;
      const report = checkSource("gold.js", withStdImport(g.source), pTrue, opts);
      expect(report.ok, formatIssues(report)).toBe(g.expectOk);
      if (g.expectCode) {
        expect(
          report.issues.some((i) => i.code === g.expectCode),
          formatIssues(report),
        ).toBe(true);
      }
      // 每个 case 至少能列出函数或明确无函数
      expect(Array.isArray(report.signatures)).toBe(true);
    });
  }
});

function formatIssues(r: { issues: Array<{ severity: string; code: string; message: string }> }): string {
  return r.issues.map((i) => `${i.severity} ${i.code}: ${i.message}`).join("; ") || "(none)";
}

// ---------------------------------------------------------------------------
// T10b：跨文件注入域证据金标（nudo:interface-domain-exceeds，error）
//
// domain-exceeds 只消费经 --callsites 注入的跨文件调用记录，checkSource
// 单文件面没有注入通道——正/负例走 core 侧唯一检查函数
// checkInjectedDomainEvidence（analyzer 注入消费区的执法核心），证据以
// 手写 positive 契约 + 注入字面量记录给出。既有 golds 与 pin 零改动。
// ---------------------------------------------------------------------------
import { T, type TypeValue } from "../../type-value.ts";
import { checkInjectedDomainEvidence, type InjectedDomainRecord } from "../scan.ts";

type DomainGold = {
  name: string;
  /** 被分析文件源码（手写契约所在） */
  source: string;
  /** 注入的使用现场记录实参（每元素一条记录） */
  argSets: TypeValue[][];
  /** 期望出现的 issue code；undefined = 期望零 domain-exceeds */
  expectCode?: string;
  /** 期望 issue 数（默认 1） */
  expectCount?: number;
};

const domainGolds: DomainGold[] = [
  {
    name: "injected \"a\" evidence exceeds handwritten positive contract",
    source: `
/**
 * @nudo:refine x positive
 */
export function area(x) {
  return x;
}
area(5);
`,
    // 手写 positive 契约；本文件内调用 5 合规（不产生任何 issue），
    // 注入的使用现场证据 "a" 越域 → 恰一条 domain-exceeds error
    argSets: [[T.literal("a")]],
    expectCode: "nudo:interface-domain-exceeds",
  },
  {
    name: "injected evidence within handwritten contract is silent",
    source: `
/**
 * @nudo:refine x positive
 */
export function area(x) {
  return x;
}
area(5);
`,
    // 证据 7 / 1 ⊆ positive：零 domain-exceeds（负例）
    argSets: [[T.literal(7)], [T.literal(1)]],
  },
];

describe("injected domain evidence gold standards", () => {
  for (const g of domainGolds) {
    it(g.name, () => {
      const records: InjectedDomainRecord[] = g.argSets.map((argTypes) => ({
        argTypes,
        resultType: T.literal(1),
        throws: T.never,
      }));
      const issues = checkInjectedDomainEvidence(
        "area",
        withStdImport(g.source),
        records,
        {
          paramNames: ["x"],
          loadModule: stdLoadModule,
          fromFile: "/test/file.js",
          loc: { line: 2, column: 0 },
        },
      );
      const domainIssues = issues.filter(
        (i) => i.code === "nudo:interface-domain-exceeds",
      );
      if (g.expectCode) {
        expect(domainIssues.length).toBe(g.expectCount ?? 1);
        expect(domainIssues[0]!.severity).toBe("error");
      } else {
        expect(domainIssues).toEqual([]);
      }
    });
  }
});
