/**
 * nudo:interface-domain-exceeds（T10b）：跨文件注入的调用点域证据 ⊄ 手写契约。
 *
 * - helper 面（checkInjectedDomainEvidence）：正例 / 负例 / null 预过滤 /
 *   conf 门槛（widened 字面量证据不触发）/ never∧never 泄漏记录不触发 /
 *   generated 与 implicit 来源不执法 / HOF fn 参数位豁免 / 证据去重与
 *   每函数每参数位最多一条
 * - 来源分流铁律（checkSource 面）：写在被分析文件里的调用点违例（含
 *   require 跨文件被调路径）维持 nudo:constraint-violated 原码原语义，
 *   不产生 domain-exceeds
 *
 * 证据门槛依据（§6）：CallRecord 无截断字段（evaluator.ts 声明仅
 * fnName/argTypes/resultType/throws/callLoc/targetModule/targetExport/
 * targetAliases/fnModule 十项）——resultType=never ∧ throws=never 的求值
 * 中断泄漏是记录上唯一的完整性标记，与 analyzer 注入消费区同款过滤；
 * widened/partial conf 的实参不构成字面量证据（§6 只收 exact/path）。
 */
import { describe, it, expect, beforeEach } from "vitest";
import { checkSource, pTrue } from "../index.ts";
import { checkInjectedDomainEvidence, type InjectedDomainRecord } from "../scan.ts";
import { resetCheckSourceMemo } from "../check.ts";
import { resetGeneralizeMemo } from "../generalize.ts";
import { takeInterfaceDiags } from "../interface.ts";
import { takeRefineDiags } from "../refine.ts";
import { STD_NUDO_SRC } from "./nudo-constraints.ts";
import { abs as makeAbs, numLit, strLit, num, type Abs } from "../abs.ts";
import { lit as termLit } from "../term.ts";

/** 虚拟文件系统 loader（T10a gold files 先例）：相对 spec 按 fromFile 目录解析 */
function makeFiles(files: Record<string, string>) {
  const resolveSpec = (from: string, spec: string): string => {
    if (!spec.startsWith(".")) return spec;
    const parts = from.split("/").slice(0, -1);
    for (const seg of spec.split("/")) {
      if (seg === "." || seg === "") continue;
      if (seg === "..") parts.pop();
      else parts.push(seg);
    }
    return parts.join("/");
  };
  return {
    loadModule: (spec: string, from: string): string | undefined =>
      spec.includes("std.nudo")
        ? STD_NUDO_SRC
        : files[resolveSpec(from, spec)] ?? files[spec],
  };
}

/** 手写源码 refine：x > 0 */
const POS_SRC = `
/// @nudo:import { positive } from "./std.nudo.js"
/**
 * @nudo:refine x positive
 */
export function area(x) {
  return x;
}
`;

const GEN = (body: string) =>
  `import { fn, number } from "@nudojs/core";\n// @generated by nudo — do not edit\n${body}`;

/** 最小注入记录：结果有信息量（非 never∧never 泄漏形态） */
const neverAbs = (): Abs => makeAbs({ k: "never" }, undefined, undefined, "exact");
const nullLit = (): Abs => makeAbs({ k: "unknown" }, termLit(null), undefined, "exact");
const rec = (...argAbs: Abs[]): InjectedDomainRecord => ({
  argAbs,
  resultAbs: numLit(1),
  throwsAbs: neverAbs(),
});

describe("checkInjectedDomainEvidence（helper 面）", () => {
  beforeEach(() => {
    resetCheckSourceMemo();
    resetGeneralizeMemo();
    takeRefineDiags();
    takeInterfaceDiags();
  });

  it("正例：手写 positive 契约 + 注入 \"a\" 证据 → 恰一条 domain-exceeds error", () => {
    const { loadModule } = makeFiles({});
    const issues = checkInjectedDomainEvidence("area", POS_SRC, [rec(strLit("a"))], {
      paramNames: ["x"],
      loadModule,
      fromFile: "/t/area.js",
      loc: { line: 6, column: 0 },
    });
    expect(issues).toHaveLength(1);
    expect(issues[0]!.code).toBe("nudo:interface-domain-exceeds");
    expect(issues[0]!.severity).toBe("error");
    expect(issues[0]!.fn).toBe("area");
    expect(issues[0]!.actual).toBe('"a"');
    expect(issues[0]!.expected).toBe("number().gt(0)");
    expect(issues[0]!.line).toBe(6);
    expect(issues[0]!.message).toContain("area");
    expect(issues[0]!.message).toContain("x");
  });

  it("负例：证据 5 ⊆ positive 契约 → 无 issue", () => {
    const { loadModule } = makeFiles({});
    const issues = checkInjectedDomainEvidence("area", POS_SRC, [rec(numLit(5))], {
      paramNames: ["x"],
      loadModule,
      fromFile: "/t/area.js",
    });
    expect(issues).toEqual([]);
  });

  it("null 证据预过滤：lit(null) 对任何约束恒不满足，不报（T4 caveat）", () => {
    const { loadModule } = makeFiles({});
    const issues = checkInjectedDomainEvidence("area", POS_SRC, [rec(nullLit())], {
      paramNames: ["x"],
      loadModule,
      fromFile: "/t/area.js",
    });
    expect(issues).toEqual([]);
  });

  it("conf 门槛：widened 字面量证据不触发", () => {
    const { loadModule } = makeFiles({});
    const widenedLit = makeAbs({ k: "prim", type: "number" }, termLit(5), undefined, "widened");
    const issues = checkInjectedDomainEvidence("area", POS_SRC, [rec(widenedLit)], {
      paramNames: ["x"],
      loadModule,
      fromFile: "/t/area.js",
    });
    expect(issues).toEqual([]);
  });

  it("conf 门槛：partial conf 字面量证据同样不触发（§6 只收 exact/path）", () => {
    const { loadModule } = makeFiles({});
    const partialLit = makeAbs({ k: "prim", type: "number" }, termLit(-1), undefined, "partial");
    const issues = checkInjectedDomainEvidence("area", POS_SRC, [rec(partialLit)], {
      paramNames: ["x"],
      loadModule,
      fromFile: "/t/area.js",
    });
    expect(issues).toEqual([]);
  });

  it("Abs exact lit 执法", () => {
    const { loadModule } = makeFiles({});
    const absRec = rec(makeAbs({ k: "prim", type: "string" }, termLit("a"), undefined, "exact"));
    const issues = checkInjectedDomainEvidence("area", POS_SRC, [absRec], {
      paramNames: ["x"],
      loadModule,
      fromFile: "/t/area.js",
    });
    expect(issues).toHaveLength(1);
    expect(issues[0]!.code).toBe("nudo:interface-domain-exceeds");
    expect(issues[0]!.actual).toBe('"a"');
  });

  it("Abs 证据 conf 门槛：widened Abs lit 不执法", () => {
    const { loadModule } = makeFiles({});
    const absRec = rec(makeAbs({ k: "prim", type: "string" }, termLit("a"), undefined, "widened"));
    const issues = checkInjectedDomainEvidence("area", POS_SRC, [absRec], {
      paramNames: ["x"],
      loadModule,
      fromFile: "/t/area.js",
    });
    expect(issues).toEqual([]);
  });

  it("Abs 证据：无 lit 的 prim（符号项）不构成字面量证据", () => {
    const { loadModule } = makeFiles({});
    const absRec = rec(
      makeAbs({ k: "prim", type: "number" }, { op: "var", id: "x" }, undefined, "path"),
    );
    const issues = checkInjectedDomainEvidence("area", POS_SRC, [absRec], {
      paramNames: ["x"],
      loadModule,
      fromFile: "/t/area.js",
    });
    expect(issues).toEqual([]);
  });

  it("never∧never 泄漏记录（求值中断）不触发", () => {
    const { loadModule } = makeFiles({});
    const leaked: InjectedDomainRecord = {
      argAbs: [strLit("a")],
      resultAbs: neverAbs(),
      throwsAbs: neverAbs(),
    };
    const issues = checkInjectedDomainEvidence("area", POS_SRC, [leaked], {
      paramNames: ["x"],
      loadModule,
      fromFile: "/t/area.js",
    });
    expect(issues).toEqual([]);
  });

  it("generated 来源不执法（过期由 nudo:interface-drift 覆盖）", () => {
    const { loadModule } = makeFiles({
      "/t/area.nudo.js": GEN(`export const area = fn({ x: number().gt(0) });`),
    });
    const src = `
export function area(x) {
  return x;
}
`;
    const issues = checkInjectedDomainEvidence("area", src, [rec(strLit("a"))], {
      paramNames: ["x"],
      loadModule,
      fromFile: "/t/area.js",
    });
    expect(issues).toEqual([]);
  });

  it("implicit（无任何契约）不触发", () => {
    const { loadModule } = makeFiles({});
    const src = `
export function area(x) {
  return x;
}
`;
    const issues = checkInjectedDomainEvidence("area", src, [rec(strLit("a"))], {
      paramNames: ["x"],
      loadModule,
      fromFile: "/t/area.js",
    });
    expect(issues).toEqual([]);
  });

  it("手写侧车同名绑定执法：fn({ x: number().gt(0) }) + \"a\" 证据 → 一条", () => {
    const { loadModule } = makeFiles({
      "/t/area.nudo.js":
        'import { fn, number } from "@nudojs/core";\nexport const area = fn({ x: number().gt(0) });',
    });
    const src = `
export function area(x) {
  return x;
}
`;
    const issues = checkInjectedDomainEvidence("area", src, [rec(strLit("a"))], {
      paramNames: ["x"],
      loadModule,
      fromFile: "/t/area.js",
    });
    expect(issues).toHaveLength(1);
    expect(issues[0]!.code).toBe("nudo:interface-domain-exceeds");
    expect(issues[0]!.expected).toBe("number().gt(0)");
  });

  it("HOF 豁免：fn 形态参数位（f: fn({…})）不执法", () => {
    const { loadModule } = makeFiles({
      "/t/apply.nudo.js": `import { fn, number } from "@nudojs/core";\nexport const apply = fn({ f: fn({ x: number().gt(0) }) });`,
    });
    const src = `
export function apply(f) {
  return f(1);
}
`;
    // 字面量 "a" 传进 fn 位：literalMeetsConstraint 对 fn 形态恒 false，
    // 直接查必 FP → Phase 1 参数位 fn 不执法（§3.3）
    const issues = checkInjectedDomainEvidence("apply", src, [rec(strLit("a"))], {
      paramNames: ["f"],
      loadModule,
      fromFile: "/t/apply.js",
    });
    expect(issues).toEqual([]);
  });

  it("多证据去重并列：\"a\"/\"b\"/\"a\" → 一条 issue，actual 列两个", () => {
    const { loadModule } = makeFiles({});
    const issues = checkInjectedDomainEvidence(
      "area",
      POS_SRC,
      [rec(strLit("a")), rec(strLit("b")), rec(strLit("a"))],
      { paramNames: ["x"], loadModule, fromFile: "/t/area.js" },
    );
    expect(issues).toHaveLength(1);
    expect(issues[0]!.actual).toBe('"a", "b"');
  });

  it("多参数位各自独立：x 证据越域、y 证据合规 → 仅 x 一条", () => {
    const src = `
/// @nudo:import { positive, nonEmpty } from "./std.nudo.js"
/**
 * @nudo:refine x positive
 * @nudo:refine y nonEmpty
 */
export function pair(x, y) {
  return y.length + (x > 0 ? x : 0);
}
`;
    const { loadModule } = makeFiles({});
    const issues = checkInjectedDomainEvidence(
      "pair",
      src,
      [rec(numLit(-1), strLit("ok"))],
      { paramNames: ["x", "y"], loadModule, fromFile: "/t/pair.js" },
    );
    expect(issues).toHaveLength(1);
    expect(issues[0]!.message).toContain("x");
    expect(issues[0]!.actual).toBe("-1");
  });

  it("契约参数名对不上形参表（解构/rest）→ 跳过不猜", () => {
    const { loadModule } = makeFiles({});
    const issues = checkInjectedDomainEvidence("area", POS_SRC, [rec(strLit("a"))], {
      paramNames: ["n"], // 契约参数名 x 不在形参表
      loadModule,
      fromFile: "/t/area.js",
    });
    expect(issues).toEqual([]);
  });

  it("非 literal 实参（union/unknown/primitive）无证据", () => {
    const { loadModule } = makeFiles({});
    const issues = checkInjectedDomainEvidence(
      "area",
      POS_SRC,
      [rec(makeAbs({ k: "sum", members: [strLit("a"), numLit(5)] }, undefined, undefined, "exact")), rec(makeAbs({ k: "unknown" }, undefined, undefined, "partial")), rec(num())],
      { paramNames: ["x"], loadModule, fromFile: "/t/area.js" },
    );
    expect(issues).toEqual([]);
  });
});

describe("来源分流铁律：本文件内调用点违例仍走 constraint-violated", () => {
  beforeEach(() => {
    resetCheckSourceMemo();
    resetGeneralizeMemo();
    takeRefineDiags();
    takeInterfaceDiags();
  });

  it("同文件违例调用：constraint-violated，无 domain-exceeds", () => {
    const src = `
/// @nudo:import { positive } from "./std.nudo.js"
/**
 * @nudo:refine x positive
 */
function area(x) {
  if (x > 0) return x;
  return 0;
}
const r = area(-1);
`;
    const { loadModule } = makeFiles({});
    const r = checkSource("main.js", src, pTrue, { loadModule, fromFile: "/t/main.js" });
    const violated = r.issues.find((i) => i.code === "nudo:constraint-violated");
    expect(violated).toBeDefined();
    expect(r.issues.filter((i) => i.code === "nudo:interface-domain-exceeds")).toEqual([]);
    expect(r.ok).toBe(false);
  });

  it("require 跨文件被调路径（checkExternalCall）：constraint-violated 原码原语义", () => {
    const modules: Record<string, string> = {
      "./v.js": `
/// @nudo:import { positive } from "./std.nudo.js"
/**
 * @nudo:refine x positive
 */
function needsPositive(x) {
  if (x > 0) return x;
  return 0;
}
module.exports = { needsPositive };
`,
    };
    const loadModule = (spec: string): string | undefined =>
      spec.includes("std.nudo") ? STD_NUDO_SRC : modules[spec];
    const r = checkSource(
      "main.js",
      `
const { needsPositive } = require("./v.js");
needsPositive(-1);
`,
      pTrue,
      { loadModule, fromFile: "/t/main.js" },
    );
    const violated = r.issues.find((i) => i.code === "nudo:constraint-violated");
    expect(violated).toBeDefined();
    expect(r.issues.filter((i) => i.code === "nudo:interface-domain-exceeds")).toEqual([]);
    expect(r.ok).toBe(false);
  });
});
