/**
 * effectiveInterface 单点读取口（design-refine-derivation §2.1/§11 第 0 步）：
 * 侧车同名自动绑定、手写∪生成段合并序、合取/矛盾、autoBind 边界、
 * 侧车闭包指纹、formatConstraint 组合式显示。
 */
import { describe, it, expect } from "vitest";
import {
  effectiveInterface,
  sidecarPathOf,
  localNamedExports,
  generatedExportNames,
  sidecarClosureFingerprint,
  formatConstraint,
  takeInterfaceDiags,
  type EffectiveInterfaceOpts,
} from "../interface.ts";
import { execNudoModule } from "../refine.ts";
import { isNudoConstraint, number, string, lit, union, fn, shape, array } from "../constraint.ts";

/** 虚拟文件系统 loader：相对 spec 按 fromFile 目录解析 */
function makeFiles(files: Record<string, string>) {
  const resolve = (from: string, spec: string): string => {
    if (!spec.startsWith(".")) return spec;
    const parts = from.split("/").slice(0, -1);
    for (const seg of spec.split("/")) {
      if (seg === "" || seg === ".") continue;
      if (seg === "..") parts.pop();
      else parts.push(seg);
    }
    return parts.join("/");
  };
  const loadModule = (spec: string, from: string): string | undefined =>
    files[resolve(from, spec)];
  return { loadModule, resolve };
}

const STD = `
import { number } from "@nudojs/core";
export const positive = number().gt(0);
`;

describe("sidecarPathOf", () => {
  it("maps four entry extensions", () => {
    expect(sidecarPathOf("/t/a.js")).toBe("/t/a.nudo.js");
    expect(sidecarPathOf("/t/a.mjs")).toBe("/t/a.nudo.js");
    expect(sidecarPathOf("/t/a.ts")).toBe("/t/a.nudo.ts");
    expect(sidecarPathOf("/t/a.mts")).toBe("/t/a.nudo.ts");
  });
});

describe("localNamedExports", () => {
  it("collects top-level declarations only", () => {
    const src = `
export function f() {}
export const g = 1;
export let h = 2;
export class C {}
export var v = 3;
const p = 4;
export { p };
export { add2 } from "./dep.js";
export * from "./other.js";
export default function d() {}
function helper() {}
`;
    expect(localNamedExports(src)).toEqual(new Set(["f", "g", "h", "C"]));
  });
});

describe("generatedExportNames", () => {
  it("marks exports under @generated comment blocks only", () => {
    const src = `
// @generated by nudo — do not edit; regenerate with \`nudo interface --emit\`
export const add2 = fn({ x: number() }, number());

// hand-written（无标记）
export const other = number();

export const plain = number();
`;
    expect(generatedExportNames(src)).toEqual(new Set(["add2"]));
  });
});

describe("effectiveInterface: 侧车同名自动绑定", () => {
  const source = `export function add2(x) {\n  return x + 2;\n}\n`;

  it("binds fn-form sidecar export and reports handwritten source", () => {
    const { loadModule } = makeFiles({
      "/t/std.nudo.js": STD,
      "/t/add.nudo.js": `
import { positive } from "./std.nudo.js";
export const add2 = fn({ x: positive }, positive.shift(2));
`,
    });
    const r = effectiveInterface(source, "add2", { loadModule, fromFile: "/t/add.js" });
    expect(r).toBeDefined();
    expect(r!.source).toBe("handwritten");
    expect(r!.params.map((p) => p.param)).toEqual(["x"]);
    expect(formatConstraint(r!.params[0]!.constraint)).toBe("number().gt(0)");
    expect(r!.returns).toBeDefined();
    expect(formatConstraint(r!.returns!.constraint)).toBe("number().gt(2)");
  });

  it("generated sidecar segment wins only when no handwritten contract", () => {
    const { loadModule } = makeFiles({
      "/t/std.nudo.js": STD,
      "/t/add.nudo.js": `
import { positive } from "./std.nudo.js";
// @generated by nudo — do not edit
export const add2 = fn({ x: positive });
`,
    });
    const r = effectiveInterface(source, "add2", { loadModule, fromFile: "/t/add.js" });
    expect(r!.source).toBe("generated");
    expect(r!.returns).toBeUndefined();
  });

  it("handwritten source refine beats generated segment", () => {
    const src = `/// @nudo:import { positive } from "./std.nudo.js"\n/**\n * @nudo:refine x positive\n */\nexport function add2(x) {\n  return x + 2;\n}\n`;
    const { loadModule } = makeFiles({
      "/t/std.nudo.js": STD,
      "/t/add.nudo.js": `
// @generated by nudo — do not edit
export const add2 = fn({ x: number().lt(99) });
`,
    });
    const r = effectiveInterface(src, "add2", { loadModule, fromFile: "/t/add.js" });
    expect(r!.source).toBe("handwritten");
    // 生成段不进手写合并（§3.3：生成 = 事实快照）
    expect(formatConstraint(r!.params[0]!.constraint)).toBe("number().gt(0)");
  });

  it("conjoins source refine with sidecar binding per param", () => {
    const src = `/// @nudo:import { positive } from "./std.nudo.js"\n/**\n * @nudo:refine x positive\n */\nexport function add2(x) {\n  return x + 2;\n}\n`;
    const { loadModule } = makeFiles({
      "/t/std.nudo.js": STD,
      "/t/add.nudo.js": `export const add2 = fn({ x: number().lt(5) }, number());`,
    });
    const r = effectiveInterface(src, "add2", { loadModule, fromFile: "/t/add.js" });
    expect(r!.source).toBe("handwritten");
    expect(formatConstraint(r!.params[0]!.constraint)).toBe("number().gt(0).lt(5)");
    expect(r!.conflict).toBeUndefined();
  });

  it("flags constant-bound contradiction as conflict", () => {
    const src = `/// @nudo:import { positive } from "./std.nudo.js"\n/**\n * @nudo:refine x positive\n */\nexport function add2(x) {\n  return x + 2;\n}\n`;
    const { loadModule } = makeFiles({
      "/t/std.nudo.js": STD,
      "/t/add.nudo.js": `export const add2 = fn({ x: number().lt(0) });`,
    });
    const r = effectiveInterface(src, "add2", { loadModule, fromFile: "/t/add.js" });
    expect(r!.conflict).toEqual({ params: ["x"] });
  });

  it("does not bind re-exports / private names / export default", () => {
    const { loadModule } = makeFiles({
      "/t/add.nudo.js": `export const add2 = fn({ x: number() });\nexport const helper = fn({ x: number() });\nexport const d = fn({ x: number() });`,
    });
    const reexport = `export { add2 } from "./dep.js";\n`;
    expect(effectiveInterface(reexport, "add2", { loadModule, fromFile: "/t/add.js" })).toBeUndefined();
    const priv = `function helper(x) {\n  return x;\n}\n`;
    expect(effectiveInterface(priv, "helper", { loadModule, fromFile: "/t/add.js" })).toBeUndefined();
    const def = `export default function d(x) {\n  return x;\n}\n`;
    expect(effectiveInterface(def, "d", { loadModule, fromFile: "/t/add.js" })).toBeUndefined();
  });

  it("honors autoBind:false and node_modules boundary", () => {
    const { loadModule } = makeFiles({
      "/t/add.nudo.js": `export const add2 = fn({ x: number() });`,
    });
    const opts: EffectiveInterfaceOpts = { loadModule, fromFile: "/t/add.js", autoBind: false };
    expect(effectiveInterface(source, "add2", opts)).toBeUndefined();

    const nm = makeFiles({
      "/pkg/node_modules/x/index.nudo.js": `export const add2 = fn({ x: number() });`,
    });
    expect(
      effectiveInterface(source, "add2", {
        loadModule: nm.loadModule,
        fromFile: "/pkg/node_modules/x/index.js",
      }),
    ).toBeUndefined();
  });

  it("collects nudo:interface-load diag for non-fn sidecar binding", () => {
    takeInterfaceDiags(); // 清空
    const { loadModule } = makeFiles({
      "/t/add.nudo.js": `export const add2 = number().gt(0);`,
    });
    const r = effectiveInterface(source, "add2", { loadModule, fromFile: "/t/add.js" });
    expect(r).toBeUndefined();
    const diags = takeInterfaceDiags();
    expect(diags.some((d) => d.code === "nudo:interface-load" && d.message.includes("fn()"))).toBe(true);
  });

  it("returns undefined when no sidecar and no refine (implicit 由调用方处理)", () => {
    const { loadModule } = makeFiles({});
    expect(effectiveInterface(source, "add2", { loadModule, fromFile: "/t/add.js" })).toBeUndefined();
  });
});

describe("execNudoModule 注入表（新构建器）", () => {
  it("injects fn/lit/union/partial/pick/omit into sidecar scope", () => {
    const src = `
import { fn, lit, union, number, shape, partial, pick, omit, string } from "@nudojs/core";
export const u = union(lit(42), lit("a"));
export const f = fn({ x: number().gt(0) }, number());
export const s = shape({ id: number().int(), name: string() });
export const p = partial(s);
export const pk = pick(s, ["id"]);
export const om = omit(s, ["name"]);
`;
    const out = execNudoModule(src);
    expect(isNudoConstraint(out["u"])).toBe(true);
    expect((out["u"] as { members?: unknown[] }).members).toHaveLength(2);
    expect((out["f"] as { fn?: unknown }).fn).toBeDefined();
    expect(isNudoConstraint(out["p"])).toBe(true);
    expect(isNudoConstraint(out["pk"])).toBe(true);
    expect(isNudoConstraint(out["om"])).toBe(true);
  });
});

describe("sidecarClosureFingerprint", () => {
  it("changes when a transitive dep content changes", () => {
    const files: Record<string, string> = {
      "/t/std.nudo.js": STD,
      "/t/add.nudo.js": `import { positive } from "./std.nudo.js";\nexport const add2 = fn({ x: positive });`,
    };
    const { loadModule } = makeFiles(files);
    const fp1 = sidecarClosureFingerprint("/t/add.js", { loadModule });
    expect(fp1).toBeDefined();
    files["/t/std.nudo.js"] = STD.replace("gt(0)", "gt(1)");
    const fp2 = sidecarClosureFingerprint("/t/add.js", { loadModule });
    expect(fp2).toBeDefined();
    expect(fp2).not.toBe(fp1);
  });

  it("returns undefined without loadModule or sidecar", () => {
    expect(sidecarClosureFingerprint("/t/add.js", {})).toBeUndefined();
    const { loadModule } = makeFiles({});
    expect(sidecarClosureFingerprint("/t/add.js", { loadModule })).toBeUndefined();
  });
});

describe("formatConstraint", () => {
  it("renders combinator forms", () => {
    expect(formatConstraint(number().gt(0))).toBe("number().gt(0)");
    expect(formatConstraint(number().int().gt(0))).toBe("number().int().gt(0)");
    expect(formatConstraint(lit(42))).toBe("lit(42)");
    expect(formatConstraint(lit("a"))).toBe(`lit("a")`);
    expect(formatConstraint(union(lit(42), lit("a")))).toBe(`union(lit(42), lit("a"))`);
    expect(formatConstraint(string().min(1))).toBe("string().min(1)");
    expect(formatConstraint(array(number()))).toBe("array(number())");
    expect(formatConstraint(shape({ id: number().int() }))).toBe("shape({ id: number().int() })");
    expect(formatConstraint(fn({ x: number().gt(0) }, number().gt(2)))).toBe(
      "fn({ x: number().gt(0) }, number().gt(2))",
    );
  });
});
