/**
 * effectiveInterface 单点读取口（design-refine-derivation §2.1/§11 第 0 步）：
 * 侧车同名自动绑定、手写∪生成段合并序、合取/矛盾、autoBind 边界、
 * 侧车闭包指纹、formatConstraint 组合式显示。
 */
import { describe, it, expect } from "vitest";
import {
  effectiveInterface,
  sidecarPathOf,
  localNamedExports,
  generatedExportNames,
  sidecarClosureFingerprint,
  formatConstraint,
  interfaceDiagCount,
  takeInterfaceDiags,
  takeInterfaceDiagsSince,
  type EffectiveInterfaceOpts,
} from "../interface.ts";
import { execNudoModule, takeRefineDiags } from "../refine.ts";
import { isNudoConstraint, number, string, lit, union, fn, shape, array } from "../constraint.ts";

/** 虚拟文件系统 loader：相对 spec 按 fromFile 目录解析 */
function makeFiles(files: Record<string, string>) {
  const resolve = (from: string, spec: string): string => {
    if (!spec.startsWith(".")) return spec;
    const parts = from.split("/").slice(0, -1);
    for (const seg of spec.split("/")) {
      if (seg === "" || seg === ".") continue;
      if (seg === "..") parts.pop();
      else parts.push(seg);
    }
    return parts.join("/");
  };
  const loadModule = (spec: string, from: string): string | undefined =>
    files[resolve(from, spec)];
  return { loadModule, resolve };
}

const STD = `
import { number, lit } from "@nudojs/core";
export const positive = number().gt(0);
export const fortyTwo = lit(42);
export const five = lit(5);
`;

describe("sidecarPathOf", () => {
  it("maps four entry extensions", () => {
    expect(sidecarPathOf("/t/a.js")).toBe("/t/a.nudo.js");
    expect(sidecarPathOf("/t/a.mjs")).toBe("/t/a.nudo.js");
    expect(sidecarPathOf("/t/a.ts")).toBe("/t/a.nudo.ts");
    expect(sidecarPathOf("/t/a.mts")).toBe("/t/a.nudo.ts");
  });

  it("relative node_modules path is blocked by autoBind (no leading-slash bypass)", () => {
    const { loadModule } = makeFiles({
      "node_modules/pkg/x.nudo.js": `export const x = fn({});`,
    });
    // cwd-relative 形态：历史守卫只匹配 "/node_modules/" 会漏掉
    expect(
      effectiveInterface(`export function x() {}\n`, "x", {
        loadModule,
        fromFile: "node_modules/pkg/x.js",
      }),
    ).toBeUndefined();
    expect(
      effectiveInterface(`export function x() {}\n`, "x", {
        loadModule,
        fromFile: "/proj/node_modules/pkg/x.js",
      }),
    ).toBeUndefined();
  });
});

describe("localNamedExports", () => {
  it("collects declaration forms and local export lists", () => {
    const src = `
export function f() {}
export const g = 1;
export let h = 2;
export class C {}
export var v = 3;
const p = 4;
export { p };
const q = 5;
export { q as renamed };
export { add2 } from "./dep.js";
export * from "./other.js";
export default function d() {}
function helper() {}
`;
    expect(localNamedExports(src)).toEqual(new Set(["f", "g", "h", "C", "v", "p", "renamed"]));
  });
});

describe("generatedExportNames", () => {
  it("marks exports under @generated comment blocks only", () => {
    const src = `
// @generated by nudo — do not edit; regenerate with \`nudo interface --emit\`
export const add2 = fn({ x: number() }, number());

// hand-written（无标记）
export const other = number();

export const plain = number();
`;
    expect(generatedExportNames(src)).toEqual(new Set(["add2"]));
  });
});

describe("effectiveInterface: 侧车同名自动绑定", () => {
  const source = `export function add2(x) {\n  return x + 2;\n}\n`;

  it("binds fn-form sidecar export and reports handwritten source", () => {
    const { loadModule } = makeFiles({
      "/t/std.nudo.js": STD,
      "/t/add.nudo.js": `
import { positive } from "./std.nudo.js";
export const add2 = fn({ x: positive }, positive.shift(2));
`,
    });
    const r = effectiveInterface(source, "add2", { loadModule, fromFile: "/t/add.js" });
    expect(r).toBeDefined();
    expect(r!.source).toBe("handwritten");
    expect(r!.params.map((p) => p.param)).toEqual(["x"]);
    expect(formatConstraint(r!.params[0]!.constraint)).toBe("number().gt(0)");
    expect(r!.returns).toBeDefined();
    expect(formatConstraint(r!.returns!.constraint)).toBe("number().gt(2)");
  });

  it("generated sidecar segment wins only when no handwritten contract", () => {
    const { loadModule } = makeFiles({
      "/t/std.nudo.js": STD,
      "/t/add.nudo.js": `
import { positive } from "./std.nudo.js";
// @generated by nudo — do not edit
export const add2 = fn({ x: positive });
`,
    });
    const r = effectiveInterface(source, "add2", { loadModule, fromFile: "/t/add.js" });
    expect(r!.source).toBe("generated");
    expect(r!.returns).toBeUndefined();
  });

  it("handwritten source refine beats generated segment", () => {
    const src = `/// @nudo:import { positive } from "./std.nudo.js"\n/**\n * @nudo:refine x positive\n */\nexport function add2(x) {\n  return x + 2;\n}\n`;
    const { loadModule } = makeFiles({
      "/t/std.nudo.js": STD,
      "/t/add.nudo.js": `
// @generated by nudo — do not edit
export const add2 = fn({ x: number().lt(99) });
`,
    });
    const r = effectiveInterface(src, "add2", { loadModule, fromFile: "/t/add.js" });
    expect(r!.source).toBe("handwritten");
    // 生成段不进手写合并（§3.3：生成 = 事实快照）
    expect(formatConstraint(r!.params[0]!.constraint)).toBe("number().gt(0)");
  });

  it("conjoins source refine with sidecar binding per param", () => {
    const src = `/// @nudo:import { positive } from "./std.nudo.js"\n/**\n * @nudo:refine x positive\n */\nexport function add2(x) {\n  return x + 2;\n}\n`;
    const { loadModule } = makeFiles({
      "/t/std.nudo.js": STD,
      "/t/add.nudo.js": `export const add2 = fn({ x: number().lt(5) }, number());`,
    });
    const r = effectiveInterface(src, "add2", { loadModule, fromFile: "/t/add.js" });
    expect(r!.source).toBe("handwritten");
    expect(formatConstraint(r!.params[0]!.constraint)).toBe("number().gt(0).lt(5)");
    expect(r!.conflict).toBeUndefined();
  });

  it("flags constant-bound contradiction as conflict", () => {
    const src = `/// @nudo:import { positive } from "./std.nudo.js"\n/**\n * @nudo:refine x positive\n */\nexport function add2(x) {\n  return x + 2;\n}\n`;
    const { loadModule } = makeFiles({
      "/t/std.nudo.js": STD,
      "/t/add.nudo.js": `export const add2 = fn({ x: number().lt(0) });`,
    });
    const r = effectiveInterface(src, "add2", { loadModule, fromFile: "/t/add.js" });
    expect(r!.conflict).toEqual({ params: ["x"] });
  });

  it("flags eq/eq contradiction as conflict", () => {
    const src = `/// @nudo:import { fortyTwo } from "./std.nudo.js"\n/**\n * @nudo:refine x fortyTwo\n */\nexport function add2(x) {\n  return x + 2;\n}\n`;
    const { loadModule } = makeFiles({
      "/t/std.nudo.js": STD,
      "/t/add.nudo.js": `export const add2 = fn({ x: lit(43) });`,
    });
    const r = effectiveInterface(src, "add2", { loadModule, fromFile: "/t/add.js" });
    expect(r!.conflict).toEqual({ params: ["x"] });
  });

  it("flags eq/bound contradiction as conflict", () => {
    const src = `/// @nudo:import { five } from "./std.nudo.js"\n/**\n * @nudo:refine x five\n */\nexport function add2(x) {\n  return x + 2;\n}\n`;
    const { loadModule } = makeFiles({
      "/t/std.nudo.js": STD,
      "/t/add.nudo.js": `export const add2 = fn({ x: number().gt(10) });`,
    });
    const r = effectiveInterface(src, "add2", { loadModule, fromFile: "/t/add.js" });
    expect(r!.conflict).toEqual({ params: ["x"] });
  });

  it("does not bind re-exports / private names / export default", () => {
    const { loadModule } = makeFiles({
      "/t/add.nudo.js": `export const add2 = fn({ x: number() });\nexport const helper = fn({ x: number() });\nexport const d = fn({ x: number() });`,
    });
    const reexport = `export { add2 } from "./dep.js";\n`;
    expect(effectiveInterface(reexport, "add2", { loadModule, fromFile: "/t/add.js" })).toBeUndefined();
    const priv = `function helper(x) {\n  return x;\n}\n`;
    expect(effectiveInterface(priv, "helper", { loadModule, fromFile: "/t/add.js" })).toBeUndefined();
    const def = `export default function d(x) {\n  return x;\n}\n`;
    expect(effectiveInterface(def, "d", { loadModule, fromFile: "/t/add.js" })).toBeUndefined();
  });

  it("binds local export-list form (function + export { fn })", () => {
    const src = `function add2(x) {\n  return x + 2;\n}\nexport { add2 };\n`;
    const { loadModule } = makeFiles({
      "/t/add.nudo.js": `export const add2 = fn({ x: number().gt(0) });`,
    });
    const r = effectiveInterface(src, "add2", { loadModule, fromFile: "/t/add.js" });
    expect(r).toBeDefined();
    expect(r!.source).toBe("handwritten");
    expect(formatConstraint(r!.params[0]!.constraint)).toBe("number().gt(0)");
  });

  it("binds by export alias name (export { local as exported })", () => {
    const src = `function helper(x) {\n  return x;\n}\nexport { helper as add2 };\n`;
    const { loadModule } = makeFiles({
      "/t/add.nudo.js": `export const add2 = fn({ x: number().int() });`,
    });
    const r = effectiveInterface(src, "add2", { loadModule, fromFile: "/t/add.js" });
    expect(r).toBeDefined();
    expect(formatConstraint(r!.params[0]!.constraint)).toBe("number().int()");
  });

  it("does not bind import-then-export list (re-export of imported binding)", () => {
    const src = `import { add2 } from "./dep.js";\nexport { add2 };\n`;
    const { loadModule } = makeFiles({
      "/t/add.nudo.js": `export const add2 = fn({ x: number().gt(0) });`,
      "/t/dep.js": `export function add2(x) { return x; }\n`,
    });
    expect(effectiveInterface(src, "add2", { loadModule, fromFile: "/t/add.js" })).toBeUndefined();
  });

  it("does not bind export { x as default }", () => {
    const src = `function add2(x) {\n  return x;\n}\nexport { add2 as default };\n`;
    const { loadModule } = makeFiles({
      "/t/add.nudo.js": `export const default = fn({ x: number() });`,
    });
    // default 不在本地导出表内（且侧车 default 名也不自动绑）
    expect(localNamedExports(src).has("default")).toBe(false);
    expect(effectiveInterface(src, "add2", { loadModule, fromFile: "/t/add.js" })).toBeUndefined();
  });

  it("does not execute transitive sidecar import into node_modules", () => {
    const src = `export function add2(x) {\n  return x + 2;\n}\n`;
    const { loadModule } = makeFiles({
      "/t/add.nudo.js": `import { evil } from "../../node_modules/evil/p.nudo.js";\nexport const add2 = fn({ x: evil });\n`,
      "node_modules/evil/p.nudo.js": `export const evil = number();\n`,
    });
    const before = interfaceDiagCount();
    const r = effectiveInterface(src, "add2", { loadModule, fromFile: "/t/add.js" });
    const diags = takeInterfaceDiagsSince(before);
    expect(
      diags.some((d) => d.code === "nudo:interface-load" && d.message.includes("node_modules")),
    ).toBe(true);
    // 顶层 add2 绑定因 evil 未解析而无法形成合法 fn 契约
    expect(r?.params ?? []).toEqual(
      (r?.params ?? []).filter(() => true),
    );
  });

  it("honors autoBind:false and node_modules boundary", () => {
    const { loadModule } = makeFiles({
      "/t/add.nudo.js": `export const add2 = fn({ x: number() });`,
    });
    const opts: EffectiveInterfaceOpts = { loadModule, fromFile: "/t/add.js", autoBind: false };
    expect(effectiveInterface(source, "add2", opts)).toBeUndefined();

    const nm = makeFiles({
      "/pkg/node_modules/x/index.nudo.js": `export const add2 = fn({ x: number() });`,
    });
    expect(
      effectiveInterface(source, "add2", {
        loadModule: nm.loadModule,
        fromFile: "/pkg/node_modules/x/index.js",
      }),
    ).toBeUndefined();
  });

  it("collects nudo:interface-load diag for non-fn sidecar binding", () => {
    takeInterfaceDiags(); // 清空
    const { loadModule } = makeFiles({
      "/t/add.nudo.js": `export const add2 = number().gt(0);`,
    });
    const r = effectiveInterface(source, "add2", { loadModule, fromFile: "/t/add.js" });
    expect(r).toBeUndefined();
    const diags = takeInterfaceDiags();
    expect(diags.some((d) => d.code === "nudo:interface-load" && d.message.includes("fn()"))).toBe(true);
  });

  it("autoBind 谓词形态：按侧车路径逐个判定", () => {
    const { loadModule } = makeFiles({
      "/t/add.nudo.js": `export const add2 = fn({ x: number() });`,
    });
    const allow = (sidecarPath: string) => !sidecarPath.includes("/blocked/");
    expect(
      effectiveInterface(source, "add2", {
        loadModule,
        fromFile: "/t/add.js",
        autoBind: allow,
      }),
    ).toBeDefined();
    const blocked = makeFiles({
      "/blocked/add.nudo.js": `export const add2 = fn({ x: number() });`,
    });
    expect(
      effectiveInterface(source, "add2", {
        loadModule: blocked.loadModule,
        fromFile: "/blocked/add.js",
        autoBind: allow,
      }),
    ).toBeUndefined();
  });

  it("侧车环：NudoSidecarError 透传为 nudo:interface-cycle 诊断（不裸抛）", () => {
    takeInterfaceDiags(); // 清空
    const files: Record<string, string> = {
      "/t/a.nudo.js": `import { b } from "./b.nudo.js";\nexport const add2 = fn({ x: number() });\n`,
      "/t/b.nudo.js": `import { a } from "./a.nudo.js";\nexport const b = number();\n`,
    };
    const { loadModule } = makeFiles(files);
    const r = effectiveInterface(source, "add2", { loadModule, fromFile: "/t/a.js" });
    expect(r).toBeUndefined(); // 环中不可求值，无契约
    const diags = takeInterfaceDiags();
    expect(diags.some((d) => d.code === "nudo:interface-cycle")).toBe(true);
  });

  it("returns undefined when no sidecar and no refine (implicit 由调用方处理)", () => {
    const { loadModule } = makeFiles({});
    expect(effectiveInterface(source, "add2", { loadModule, fromFile: "/t/add.js" })).toBeUndefined();
  });
});

describe("诊断 side-channel（R04/R13：单口取走 + 不窃在途队列）", () => {
  it("takeInterfaceDiagsSince 只排本次增量，既有诊断保留", () => {
    takeInterfaceDiags(); // 清空
    const source = `export function add2(x) {\n  return x;\n}\nadd2(1);\n`;
    const bad = makeFiles({ "/t/add.nudo.js": `export const add2 = number().gt(0);` });
    // 第一条诊断（在途验证待消费）
    effectiveInterface(source, "add2", { loadModule: bad.loadModule, fromFile: "/t/add.js" });
    const since = interfaceDiagCount(); // 锚：既有诊断保留
    // 第二条诊断（工具自身探测）
    effectiveInterface(source, "add2", { loadModule: bad.loadModule, fromFile: "/t/add.js" });
    expect(takeInterfaceDiagsSince(since).length).toBe(1);
    // 既有诊断仍在队列，全量 take 才取走
    expect(takeInterfaceDiags().length).toBe(1);
  });

  it("@nudo:import 失败诊断转发进 interface 通道（不再残留 refine 通道跨文件污染）", () => {
    takeInterfaceDiags();
    takeRefineDiags();
    const srcWithBadImport = `/// @nudo:import { positive } from "./missing.nudo.js"
/**
 * @nudo:refine x positive
 */
export function needsPos(x) {
  return x;
}
`;
    const { loadModule } = makeFiles({});
    const r = effectiveInterface(srcWithBadImport, "needsPos", {
      loadModule,
      fromFile: "/t/a.js",
    });
    expect(r).toBeUndefined();
    expect(takeRefineDiags()).toEqual([]); // 已转发，refine 通道零残留
    const diags = takeInterfaceDiags();
    expect(diags.some((d) => d.code === "nudo:interface-load")).toBe(true);
  });
});

describe("execNudoModule 注入表（新构建器）", () => {
  it("injects fn/lit/union/partial/pick/omit into sidecar scope", () => {
    const src = `
import { fn, lit, union, number, shape, partial, pick, omit, string } from "@nudojs/core";
export const u = union(lit(42), lit("a"));
export const f = fn({ x: number().gt(0) }, number());
export const s = shape({ id: number().int(), name: string() });
export const p = partial(s);
export const pk = pick(s, ["id"]);
export const om = omit(s, ["name"]);
`;
    const out = execNudoModule(src);
    expect(isNudoConstraint(out["u"])).toBe(true);
    expect((out["u"] as { members?: unknown[] }).members).toHaveLength(2);
    expect((out["f"] as { fn?: unknown }).fn).toBeDefined();
    expect(isNudoConstraint(out["p"])).toBe(true);
    expect(isNudoConstraint(out["pk"])).toBe(true);
    expect(isNudoConstraint(out["om"])).toBe(true);
  });
});

describe("sidecarClosureFingerprint", () => {
  it("changes when a transitive dep content changes", () => {
    const files: Record<string, string> = {
      "/t/std.nudo.js": STD,
      "/t/add.nudo.js": `import { positive } from "./std.nudo.js";\nexport const add2 = fn({ x: positive });`,
    };
    const { loadModule } = makeFiles(files);
    const fp1 = sidecarClosureFingerprint("/t/add.js", { loadModule });
    expect(fp1).toBeDefined();
    files["/t/std.nudo.js"] = STD.replace("gt(0)", "gt(1)");
    const fp2 = sidecarClosureFingerprint("/t/add.js", { loadModule });
    expect(fp2).toBeDefined();
    expect(fp2).not.toBe(fp1);
  });

  it("returns undefined without loadModule or sidecar", () => {
    expect(sidecarClosureFingerprint("/t/add.js", {})).toBeUndefined();
    const { loadModule } = makeFiles({});
    expect(sidecarClosureFingerprint("/t/add.js", { loadModule })).toBeUndefined();
  });

  it("empty fromFile → undefined（不 ambient 绑 ./.nudo.js）", () => {
    const { loadModule } = makeFiles({
      "/t/add.nudo.js": `export const add2 = fn({ x: number() });`,
    });
    expect(sidecarClosureFingerprint("", { loadModule })).toBeUndefined();
  });

  it("autoBind:false → undefined（与 effectiveInterface 同门）", () => {
    const files: Record<string, string> = {
      "/t/add.nudo.js": `export const add2 = fn({ x: number().gt(0) });`,
    };
    const { loadModule } = makeFiles(files);
    expect(
      sidecarClosureFingerprint("/t/add.js", { loadModule, autoBind: false }),
    ).toBeUndefined();
    expect(sidecarClosureFingerprint("/t/add.js", { loadModule })).toBeDefined();
  });

  it("node_modules 侧车路径 → undefined（永不 ambient 加载）", () => {
    const files: Record<string, string> = {
      "/proj/node_modules/pkg/x.nudo.js": `export const x = fn({});`,
    };
    const { loadModule } = makeFiles(files);
    expect(
      sidecarClosureFingerprint("/proj/node_modules/pkg/x.js", { loadModule }),
    ).toBeUndefined();
  });
});

describe("formatConstraint", () => {
  it("renders combinator forms", () => {
    expect(formatConstraint(number().gt(0))).toBe("number().gt(0)");
    expect(formatConstraint(number().int().gt(0))).toBe("number().int().gt(0)");
    expect(formatConstraint(lit(42))).toBe("lit(42)");
    expect(formatConstraint(lit("a"))).toBe(`lit("a")`);
    expect(formatConstraint(union(lit(42), lit("a")))).toBe(`union(lit(42), lit("a"))`);
    expect(formatConstraint(string().min(1))).toBe("string().min(1)");
    expect(formatConstraint(array(number()))).toBe("array(number())");
    expect(formatConstraint(shape({ id: number().int() }))).toBe("shape({ id: number().int() })");
    expect(formatConstraint(fn({ x: number().gt(0) }, number().gt(2)))).toBe(
      "fn({ x: number().gt(0) }, number().gt(2))",
    );
  });
});
