/**
 * scan.ts × effectiveInterface 收口（design-refine-derivation Phase 1 §3.3 / §11）：
 * - 侧车同名手写绑定参与调用点执法（nudo:constraint-violated）
 * - generated 段 = 事实快照，不执法
 * - 跨文件（import / namespace member）侧车按定义文件路径绑定
 * - fwd 转发（wrapper→target）在侧车来源下仍工作
 * - conflict（源码 refine × 侧车手写绑定矛盾）→ nudo:interface-conflict 只在
 *   checkSource fn 级报告（scan 调用点级曾双报，已收口）
 * - 手写侧车参数契约优先于 body 结构推断（refinedParams）
 */
import { describe, it, expect } from "vitest";
import { scanLiteralCalls, listTopFunctions } from "../scan.ts";
import { checkSource } from "../check.ts";
import { pTrue } from "../pred.ts";

/** 虚拟文件系统 loader：相对 spec 按 fromFile 目录解析（与 interface-effective.test.ts 同构） */
function makeFiles(files: Record<string, string>) {
  const resolve = (from: string, spec: string): string => {
    if (!spec.startsWith(".")) return spec;
    const parts = from.split("/").slice(0, -1);
    for (const seg of spec.split("/")) {
      if (seg === "" || seg === ".") continue;
      if (seg === "..") parts.pop();
      else parts.push(seg);
    }
    return parts.join("/");
  };
  const loadModule = (spec: string, from: string): string | undefined =>
    files[resolve(from, spec)];
  return { loadModule, resolve };
}

const STD = `
export const positive = number().gt(0);
export const negative = number().lt(0);
`;

/** 同文件扫描：knownFns = 顶层函数表 */
function scanSameFile(files: Record<string, string>, source: string, fromFile = "/t/app.js") {
  const { loadModule } = makeFiles(files);
  return scanLiteralCalls(source, listTopFunctions(source), pTrue, { loadModule, fromFile });
}

describe("scan × effectiveInterface：同文件手写侧车绑定", () => {
  const source = `
export function needsPos(x) {
  if (x > 0) return x;
  return 0;
}
const r = needsPos(-1);
`;

  it("手写 fn() 绑定 + 违例调用 → nudo:constraint-violated", () => {
    const issues = scanSameFile(
      { "/t/app.nudo.js": `export const needsPos = fn({ x: number().gt(0) });` },
      source,
    );
    const err = issues.find((i) => i.code === "nudo:constraint-violated");
    expect(err).toBeDefined();
    expect(err!.severity).toBe("error");
    expect(err!.fn).toBe("needsPos");
    expect(err!.expected).toContain("> 0");
  });

  it("满足约束的调用不报", () => {
    const issues = scanSameFile(
      { "/t/app.nudo.js": `export const needsPos = fn({ x: number().gt(0) });` },
      source.replace("needsPos(-1)", "needsPos(5)"),
    );
    expect(issues.filter((i) => i.severity === "error")).toEqual([]);
  });

  it("generated 段（@generated 标记）+ 同样违例 → 不执法", () => {
    const issues = scanSameFile(
      {
        "/t/app.nudo.js": `
// @generated by nudo — do not edit
export const needsPos = fn({ x: number().gt(0) });
`,
      },
      source,
    );
    expect(issues.filter((i) => i.code === "nudo:constraint-violated")).toEqual([]);
  });

  it("无侧车文件时与旧提取路径行为一致（无 refine → 无执法）", () => {
    const issues = scanSameFile({}, source);
    expect(issues.filter((i) => i.severity === "error")).toEqual([]);
  });
});

describe("scan × effectiveInterface：跨文件侧车绑定", () => {
  const mainImport = `
import { needsPos } from "./lib.js";
const r = needsPos(-1);
`;
  const mainNamespace = `
import * as lib from "./lib.js";
const r = lib.needsPos(-1);
`;
  const libFiles = (generated: boolean): Record<string, string> => ({
    "/t/lib.js": `export function needsPos(x) {\n  if (x > 0) return x;\n  return 0;\n}\n`,
    "/t/lib.nudo.js": generated
      ? `// @generated by nudo\nexport const needsPos = fn({ x: number().gt(0) });\n`
      : `export const needsPos = fn({ x: number().gt(0) });\n`,
  });

  it("import 具名导入 + 手写侧车违例 → 报", () => {
    const { loadModule } = makeFiles(libFiles(false));
    const issues = scanLiteralCalls(mainImport, [], pTrue, {
      loadModule,
      fromFile: "/t/main.js",
    });
    const err = issues.find((i) => i.code === "nudo:constraint-violated");
    expect(err).toBeDefined();
    expect(err!.fn).toBe("needsPos");
  });

  it("namespace 成员调用（lib.needsPos）+ 手写侧车违例 → 报", () => {
    const { loadModule } = makeFiles(libFiles(false));
    const issues = scanLiteralCalls(mainNamespace, [], pTrue, {
      loadModule,
      fromFile: "/t/main.js",
    });
    expect(issues.some((i) => i.code === "nudo:constraint-violated" && i.fn === "needsPos")).toBe(
      true,
    );
  });

  it("跨文件 generated 段不执法", () => {
    const { loadModule } = makeFiles(libFiles(true));
    const issues = scanLiteralCalls(mainImport, [], pTrue, {
      loadModule,
      fromFile: "/t/main.js",
    });
    expect(issues.filter((i) => i.code === "nudo:constraint-violated")).toEqual([]);
  });

  it("跨文件满足约束的调用不报", () => {
    const { loadModule } = makeFiles(libFiles(false));
    const issues = scanLiteralCalls(mainImport.replace("-1", "5"), [], pTrue, {
      loadModule,
      fromFile: "/t/main.js",
    });
    expect(issues.filter((i) => i.severity === "error")).toEqual([]);
  });
});

describe("scan × effectiveInterface：fwd 转发（wrapper→target）", () => {
  const source = `
export function target(x) {
  if (x > 0) return x;
  return 0;
}
function w(a) {
  return target(a);
}
const r = w(-1);
`;

  it("target 的侧车手写绑定经 fwd.map 转发到 wrapper 实参位执法", () => {
    const issues = scanSameFile(
      { "/t/app.nudo.js": `export const target = fn({ x: number().gt(0) });` },
      source,
    );
    const err = issues.find((i) => i.code === "nudo:constraint-violated");
    expect(err).toBeDefined();
    expect(err!.fn).toBe("w→target");
    expect(err!.expected).toContain("> 0");
  });

  it("target 的 generated 段不参与转发执法", () => {
    const issues = scanSameFile(
      { "/t/app.nudo.js": `// @generated by nudo\nexport const target = fn({ x: number().gt(0) });` },
      source,
    );
    expect(issues.filter((i) => i.code === "nudo:constraint-violated")).toEqual([]);
  });

  it("无侧车时维持旧行为（转发无契约 → 不报）", () => {
    const issues = scanSameFile({}, source);
    expect(issues.filter((i) => i.severity === "error")).toEqual([]);
  });
});

describe("scan × effectiveInterface：conflict 与结构推断优先级", () => {
  it("源码 refine 与侧车手写绑定矛盾 → conflict 只在 check fn 级报告（scan 不双报）", () => {
    const source = `
/// @nudo:import { positive, negative } from "./std.nudo.js"
/**
 * @nudo:refine x positive
 */
export function needsPos(x) {
  if (x > 0) return x;
  return 0;
}
const a = needsPos(1);
const b = needsPos(2);
`;
    const files = {
      "/t/std.nudo.js": STD,
      "/t/app.nudo.js": `export const needsPos = fn({ x: number().lt(0) });`,
    };
    // scan 调用点级不再报 conflict（与 check.ts fn 级报告纯重复，曾双报两种消息形态）
    const scanIssues = scanSameFile(files, source);
    expect(scanIssues.filter((i) => i.code === "nudo:interface-conflict")).toEqual([]);
    // checkSource fn 级是权威面：恰好一条 error
    const { loadModule } = makeFiles(files);
    const report = checkSource("/t/app.js", source, pTrue, { loadModule, fromFile: "/t/app.js" });
    const conflicts = report.issues.filter((i) => i.code === "nudo:interface-conflict");
    expect(conflicts.length).toBe(1);
    expect(conflicts[0]!.severity).toBe("error");
    expect(conflicts[0]!.fn).toBe("needsPos");
  });

  it("手写侧车参数契约优先于 body 结构推断（refinedParams）", () => {
    const source = `
export function readY(p) {
  return p.y;
}
const r = readY({ x: 1 });
`;
    // 无侧车：body 访问 p.y → arg-structure 报缺字段
    const without = scanSameFile({}, source);
    expect(
      without.some((i) => i.code === "nudo:arg-structure" && i.message.includes("[p]")),
    ).toBe(true);

    // 手写侧车给 p 一个兼容 shape → 该形参不再走 body 结构推断
    const withSidecar = scanSameFile(
      { "/t/app.nudo.js": `export const readY = fn({ p: shape({ x: number() }) });` },
      source,
    );
    expect(withSidecar.filter((i) => i.severity === "error")).toEqual([]);
  });
});

describe("scan × effectiveInterface：lit()/union() 契约执法（eq/or 分支）", () => {
  it("fn({ x: lit(42) }) + 调用 f(7) → nudo:constraint-violated", () => {
    const source = `
export function f(x) {
  return x;
}
const a = f(7);
`;
    const issues = scanSameFile(
      { "/t/app.nudo.js": `export const f = fn({ x: lit(42) });` },
      source,
    );
    const err = issues.find((i) => i.code === "nudo:constraint-violated");
    expect(err).toBeDefined();
    expect(err!.severity).toBe("error");
    expect(err!.fn).toBe("f");
    expect(err!.expected).toBe("x = 42");
    expect(err!.actual).toContain("7");
  });

  it("lit 契约命中（f(42)）→ 零违例", () => {
    const source = `
export function f(x) {
  return x;
}
const a = f(42);
`;
    const issues = scanSameFile(
      { "/t/app.nudo.js": `export const f = fn({ x: lit(42) });` },
      source,
    );
    expect(issues.filter((i) => i.severity === "error")).toEqual([]);
  });

  it("fn({ x: union(lit(1), lit(2)) })：f(5) 违例、f(1)/f(2) 通过", () => {
    const bad = `
export function f(x) {
  return x;
}
const a = f(5);
`;
    const badIssues = scanSameFile(
      { "/t/app.nudo.js": `export const f = fn({ x: union(lit(1), lit(2)) });` },
      bad,
    );
    const err = badIssues.find((i) => i.code === "nudo:constraint-violated");
    expect(err).toBeDefined();
    expect(err!.fn).toBe("f");

    const good = `
export function f(x) {
  return x;
}
const a = f(1);
const b = f(2);
`;
    const goodIssues = scanSameFile(
      { "/t/app.nudo.js": `export const f = fn({ x: union(lit(1), lit(2)) });` },
      good,
    );
    expect(goodIssues.filter((i) => i.severity === "error")).toEqual([]);
  });

  it("shape 字段位 lit 契约：shape({ level: lit(3) }) × 实参 level=4 → 违例", () => {
    const source = `
export function setLevel(cfg) {
  return cfg.level;
}
const a = setLevel({ level: 4 });
`;
    const issues = scanSameFile(
      { "/t/app.nudo.js": `export const setLevel = fn({ cfg: shape({ level: lit(3) }) });` },
      source,
    );
    const err = issues.find((i) => i.code === "nudo:constraint-violated");
    expect(err).toBeDefined();
    expect(err!.fn).toBe("setLevel");
    expect(err!.expected).toContain("cfg.level");
  });
});

