/**
 * Root 驱动多文件写盘（emitDerivedFromRoot + 侧车段工具）。
 * 自 interface-derivation.ts 机械拆出；语义未改。
 */
import { existsSync, readFileSync, renameSync, unlinkSync, writeFileSync } from "node:fs";
import { basename, dirname, relative, resolve } from "node:path";
import {
  execNudoModule,
  isNodeModulesPath,
  isNudoConstraint,
  parseSource,
  refineDiagCount,
  sidecarPathOf,
  takeRefineDiagsSince,
} from "@nudojs/core";
import { defaultLoadModule, type LoadModule } from "./load-module.ts";
import { findProjectConfig, interfaceConfig, matchesEmitAllowlist } from "./evaluator/config.ts";
import { unifiedDiff } from "./case-emitter.ts";
import { deriveFromRoot } from "./interface-derivation-derive.ts";
import { formatDerivedSection } from "./interface-derivation-rewrite.ts";

// ---------------------------------------------------------------------------
// Root 驱动多文件写盘（§7.3：emit 永远 root 驱动；下游随根 emit 一并更新）
// ---------------------------------------------------------------------------

export type EmitDerivedResult = {
  /** 被写/将写的下游侧车（绝对路径） */
  sidecars: Array<{
    file: string;
    sidecarPath: string;
    fn: string;
    written: boolean;
    changed: boolean;
    skipped?: "name-clash" | "not-projectable" | "underivable" | "no-change";
    diff?: string;
    issues: Array<{ code: string; severity: "error" | "warning" | "info"; message: string }>;
  }>;
  hasRoot: boolean;
  roots: string[];
  /** 根在别处 / 无契约根且无已存在生成段 → info */
  entryOnly?: boolean;
};

const DERIVED_HEADER =
  "// @generated by nudo — do not edit; regenerate with `nudo contract --emit`";

/**
 * Root 驱动 emit：对 rootFile 的手写契约根做下行推导，把闭包内被点名的
 * 下游导出写入**各自**的 `*.nudo.js`（§7.3 / §11 Phase 2 验收：
 * `--emit src/lib.js --fn add2` 只写 add.nudo.js 的 add2）。
 *
 * 手写绑定永不覆盖；round-trip 自检失败不写垃圾。
 */
/**
 * 侧车顶层标识符（import local / 顶层声明 / export 名）。
 * 新生成段据此避让，避免同文件重复 `const x` / 重复 import 绑定。
 */
function collectTopLevelNames(src: string): Set<string> {
  const names = new Set<string>();
  if (src.trim() === "") return names;
  let ast: ReturnType<typeof parseSource>;
  try {
    ast = parseSource(src);
  } catch {
    return names;
  }
  const addDecl = (d: ReturnType<typeof parseSource>["program"]["body"][number]): void => {
    if (d.type === "VariableDeclaration") {
      for (const decl of d.declarations) {
        if (decl.id.type === "Identifier") names.add(decl.id.name);
      }
    } else if (d.type === "FunctionDeclaration" || d.type === "ClassDeclaration") {
      if (d.id) names.add(d.id.name);
    }
  };
  for (const stmt of ast.program.body) {
    if (stmt.type === "ImportDeclaration") {
      for (const s of stmt.specifiers) names.add(s.local.name);
      continue;
    }
    if (stmt.type === "ExportNamedDeclaration") {
      if (stmt.declaration) addDecl(stmt.declaration);
      for (const spec of stmt.specifiers) {
        names.add(
          spec.exported.type === "Identifier" ? spec.exported.name : spec.exported.value,
        );
      }
      continue;
    }
    addDecl(stmt);
  }
  return names;
}

function sidecarAssembles(text: string, fromFile: string, loadModule: LoadModule): boolean {
  try {
    parseSource(text);
    execNudoModule(text, { loadModule, fromFile });
    return true;
  } catch {
    return false;
  }
}

export function emitDerivedFromRoot(
  rootFile: string,
  opts: {
    fnNames?: string[];
    mode: "add" | "update";
    dryRun?: boolean;
    loadModule?: LoadModule;
    autoBind?: boolean;
    /** 只刷新目标侧车里已存在的 @generated 段（不发明新下游契约） */
    refreshExistingOnly?: boolean;
  },
): EmitDerivedResult {
  const abs = resolve(rootFile);
  const derive = deriveFromRoot(abs, {
    ...(opts.loadModule ? { loadModule: opts.loadModule } : {}),
    ...(opts.autoBind !== undefined ? { autoBind: opts.autoBind } : {}),
    ...(opts.fnNames && opts.fnNames.length > 0 ? { fnNames: opts.fnNames } : {}),
  });

  if (!derive.hasRoot) {
    return { sidecars: [], hasRoot: false, roots: [], entryOnly: true };
  }

  // package.json#nudo.contract.emit 白名单（Phase 3 §7.3）
  const proj = findProjectConfig(dirname(abs));
  const allow = interfaceConfig(proj?.config).emit;
  const projectDir = proj?.projectDir;

  const rootSidecarDir = dirname(sidecarPathOf(abs));
  const wanted =
    opts.fnNames && opts.fnNames.length > 0 ? new Set(opts.fnNames) : undefined;

  const result: EmitDerivedResult = {
    sidecars: [],
    hasRoot: true,
    roots: derive.roots,
  };

  // 按目标侧车分组（同文件多导出一次读写）
  const bySidecar = new Map<string, typeof derive.derived>();
  for (const row of derive.derived) {
    if (wanted && !wanted.has(row.fn)) continue;
    if (!matchesEmitAllowlist(row.file, projectDir, allow)) continue;
    const sp = sidecarPathOf(row.file);
    if (isNodeModulesPath(sp)) continue;
    const list = bySidecar.get(sp) ?? [];
    list.push(row);
    bySidecar.set(sp, list);
  }

  for (const [sidecarPath, rows0] of bySidecar) {
    const targetFile = rows0[0]!.file;
    const targetSidecarDir = dirname(sidecarPath);
    const prevSrc = existsSync(sidecarPath) ? readFileSync(sidecarPath, "utf-8") : "";

    // refreshExistingOnly：只碰已有生成段的导出，不发明新契约
    const rows = opts.refreshExistingOnly
      ? rows0.filter((r) => findGeneratedSectionText(prevSrc, r.fn) !== undefined)
      : rows0;
    if (rows.length === 0) continue;

    // 手写绑定名（顶层声明 − 生成段）
    const handwritten = handwrittenNames(prevSrc);
    const loadModule = opts.loadModule ?? defaultLoadModule;

    // update：剥离「本批可能重写」的生成段后收集残留顶层名；format 失败的
    // 段会保留旧文，其名字在失败时回填 taken（避免新段抢占）。
    const batchFns = new Set(
      rows.filter((r) => !r.underivable && !handwritten.has(r.fn)).map((r) => r.fn),
    );
    const baseForNames =
      opts.mode === "update" ? stripGeneratedFor(prevSrc, batchFns) : prevSrc;
    const taken = collectTopLevelNames(baseForNames);

    const accepted: Array<{ fn: string; text: string; prevText?: string }> = [];
    const issues: EmitDerivedResult["sidecars"][number]["issues"] = [];
    const written: string[] = [];
    let anySkip: EmitDerivedResult["sidecars"][number]["skipped"];

    for (const row of rows) {
      if (handwritten.has(row.fn)) {
        issues.push({
          code: "nudo:interface-name-clash",
          severity: "error",
          message: `sidecar already has a handwritten binding '${row.fn}' (${relative(process.cwd(), sidecarPath) || sidecarPath}); handwritten wins — skipping emit`,
        });
        anySkip = "name-clash";
        continue;
      }
      if (row.underivable) {
        issues.push({
          code: "nudo:interface-underivable",
          severity: "info",
          message: `${row.fn}: contract underivable from ${row.derivedFrom} (opaque / truncated / no evidence)`,
        });
        anySkip = "underivable";
        continue;
      }
      const prevSection = findGeneratedSectionText(prevSrc, row.fn);
      const body = formatDerivedSection(row, {
        rootSidecarDir,
        targetSidecarDir,
        takenNames: taken,
      });
      if (!body) {
        anySkip = "not-projectable";
        // 旧段将原样保留 → 名字继续占用
        if (prevSection !== undefined) {
          for (const n of collectTopLevelNames(prevSection)) taken.add(n);
        }
        continue;
      }
      for (const n of body.usedNames) taken.add(n);
      const srcRel = relative(targetSidecarDir, targetFile) || basename(targetFile);
      const section = [
        DERIVED_HEADER,
        `// source: ${srcRel}:${row.fn}`,
        `// derived-from: ${row.derivedFrom}`,
        body.text,
        "",
      ].join("\n");

      // round-trip：整段（含 import）必须可执行——fromFile 用目标侧车路径，
      // 相对 spec（./std.nudo.js）按该目录解析
      if (!derivedRoundTrips(section, row.fn, sidecarPath, loadModule)) {
        anySkip = "not-projectable";
        if (prevSection !== undefined) {
          for (const n of collectTopLevelNames(prevSection)) taken.add(n);
        }
        continue;
      }

      if (opts.mode === "add" && prevSection !== undefined) {
        anySkip = "no-change";
        for (const n of collectTopLevelNames(prevSection)) taken.add(n);
        continue;
      }
      const norm = normalizeSectionText(section);
      if (prevSection !== undefined && normalizeSectionText(prevSection) === norm) {
        anySkip = "no-change";
        accepted.push({ fn: row.fn, text: prevSection, prevText: prevSection });
        for (const n of collectTopLevelNames(prevSection)) taken.add(n);
        continue;
      }
      written.push(row.fn);
      accepted.push({ fn: row.fn, text: section, ...(prevSection !== undefined ? { prevText: prevSection } : {}) });
    }

    // 组装：update 只剥离**已接受**的生成段；underivable/not-projectable/
    // name-clash 的既有段原样保留（证据退化不静默删契约）。
    // accepted 为空时必须原样保留——否则 stripped=prev + preserved 会叠层。
    let finalContent: string;
    if (accepted.length === 0) {
      finalContent = prevSrc;
    } else if (opts.mode === "add") {
      finalContent = joinSectionTexts(prevSrc, accepted.map((a) => a.text));
    } else {
      const acceptedFns = new Set(accepted.map((a) => a.fn));
      const stripped = stripGeneratedFor(prevSrc, acceptedFns);
      const preserved = collectGeneratedSectionsRaw(prevSrc).filter(
        (s) => !s.names.some((n) => acceptedFns.has(n)),
      );
      finalContent = joinSectionTexts(stripped, [
        ...preserved.map((s) => normalizeSectionText(s.text)),
        ...accepted.map((a) => a.text),
      ]);
    }

    // 整文件 round-trip：同侧车多段拼装后仍必须是合法可执行模块
    // （单段自检挡不住 duplicate import / const 重定义）
    if (finalContent.trim() !== "" && !sidecarAssembles(finalContent, sidecarPath, loadModule)) {
      issues.push({
        code: "nudo:interface-not-projectable",
        severity: "error",
        message: `assembled sidecar failed round-trip (${relative(process.cwd(), sidecarPath) || sidecarPath}); refusing to write`,
      });
      anySkip = "not-projectable";
      result.sidecars.push({
        file: targetFile,
        sidecarPath,
        fn: rows.map((r) => r.fn).join(","),
        written: false,
        changed: false,
        ...(anySkip ? { skipped: anySkip } : {}),
        issues,
      });
      continue;
    }

    const changed = finalContent !== prevSrc;
    const diff = changed
      ? unifiedDiff(prevSrc, finalContent, relative(process.cwd(), sidecarPath) || sidecarPath)
      : undefined;

    if (changed && !opts.dryRun) {
      const tmp = `${sidecarPath}.tmp-${process.pid}-${Math.random().toString(16).slice(2, 10)}`;
      try {
        writeFileSync(tmp, finalContent, "utf-8");
        renameSync(tmp, sidecarPath);
      } catch (e) {
        try {
          if (existsSync(tmp)) unlinkSync(tmp);
        } catch {
          /* best-effort */
        }
        throw e;
      }
    }

    result.sidecars.push({
      file: targetFile,
      sidecarPath,
      fn: rows.map((r) => r.fn).join(","),
      written: written.length > 0 && changed,
      changed,
      ...(anySkip ? { skipped: anySkip } : {}),
      ...(diff !== undefined ? { diff } : {}),
      issues,
    });
  }

  return result;
}

// --- 侧车段工具（与 interface-emitter 同口径，独立实现避免循环依赖）---

type RawSection = { names: string[]; start: number; end: number; text: string };

function collectGeneratedSectionsRaw(src: string): RawSection[] {
  if (src.trim() === "") return [];
  let ast: ReturnType<typeof parseSource>;
  try {
    ast = parseSource(src);
  } catch {
    return [];
  }
  const stmts = ast.program.body;
  const out: RawSection[] = [];
  // 从 @generated 注释行起，到其后第一个顶层 export 止——中间允许
  // import / prelude const（组合式 §5.3 形态）。
  for (const headerPos of findGeneratedHeaderOffsets(src)) {
    for (let i = 0; i < stmts.length; i++) {
      const stmt = stmts[i]!;
      if (stmt.type !== "ExportNamedDeclaration" || stmt.source) continue;
      if (stmt.start == null || stmt.end == null || stmt.start < headerPos) continue;
      const d = stmt.declaration;
      if (!d) continue;
      const names: string[] = [];
      if (d.type === "VariableDeclaration") {
        for (const decl of d.declarations) {
          if (decl.id.type === "Identifier") names.push(decl.id.name);
        }
      } else if (d.type === "FunctionDeclaration" || d.type === "ClassDeclaration") {
        if (d.id) names.push(d.id.name);
      }
      if (names.length === 0) continue;
      out.push({
        names,
        start: headerPos,
        end: stmt.end,
        text: src.slice(headerPos, stmt.end),
      });
      break;
    }
  }
  return out;
}

/** 注释行上的 `@generated` 字节偏移（段起点） */
function findGeneratedHeaderOffsets(src: string): number[] {
  const out: number[] = [];
  let pos = 0;
  for (const line of src.split("\n")) {
    const t = line.trim();
    if (
      (t.startsWith("//") || t.startsWith("/*") || t.startsWith("*")) &&
      /@generated/.test(t)
    ) {
      out.push(pos);
    }
    pos += line.length + 1;
  }
  return out;
}

function generatedSectionNames(src: string): Set<string> {
  return new Set(collectGeneratedSectionsRaw(src).flatMap((s) => s.names));
}

function handwrittenNames(src: string): Set<string> {
  if (src.trim() === "") return new Set();
  let ast: ReturnType<typeof parseSource>;
  try {
    ast = parseSource(src);
  } catch {
    return new Set();
  }
  const names = new Set<string>();
  const collect = (stmt: ReturnType<typeof parseSource>["program"]["body"][number]): void => {
    if (stmt.type === "VariableDeclaration") {
      for (const d of stmt.declarations) {
        if (d.id.type === "Identifier") names.add(d.id.name);
      }
    } else if (stmt.type === "FunctionDeclaration" || stmt.type === "ClassDeclaration") {
      if (stmt.id) names.add(stmt.id.name);
    }
  };
  for (const stmt of ast.program.body) {
    if (stmt.type === "ExportNamedDeclaration") {
      if (stmt.declaration) collect(stmt.declaration);
      if (!stmt.source) {
        for (const spec of stmt.specifiers) {
          names.add(
            spec.exported.type === "Identifier" ? spec.exported.name : spec.exported.value,
          );
        }
      }
    } else {
      collect(stmt);
    }
  }
  // 生成段名不算手写
  for (const n of generatedSectionNames(src)) names.delete(n);
  return names;
}

function findGeneratedSectionText(src: string, fn: string): string | undefined {
  return collectGeneratedSectionsRaw(src).find((s) => s.names.includes(fn))?.text;
}

function stripGeneratedFor(src: string, fns: Set<string>): string {
  const sections = collectGeneratedSectionsRaw(src).filter((s) =>
    s.names.some((n) => fns.has(n)),
  );
  if (sections.length === 0) return src;
  const sorted = [...sections].sort((a, b) => a.start - b.start);
  let out = "";
  let pos = 0;
  for (const s of sorted) {
    out += src.slice(pos, s.start);
    pos = Math.max(pos, s.end);
  }
  out += src.slice(pos);
  return out;
}

function normalizeSectionText(text: string): string {
  return text.replace(/\s*$/, "") + "\n";
}

function joinSectionTexts(base: string, sectionTexts: string[]): string {
  const normalized = sectionTexts.map(normalizeSectionText).filter((t) => t.trim() !== "");
  const tailTrimmed = base.replace(/\s+$/, "");
  if (normalized.length === 0) return tailTrimmed === "" ? "" : `${tailTrimmed}\n`;
  const trimmed = tailTrimmed.replace(/^\s+/, "");
  const lead = trimmed === "" ? "" : `${trimmed}\n\n`;
  return lead + normalized.join("\n");
}

function derivedRoundTrips(
  text: string,
  fn: string,
  fromFile: string,
  loadModule: LoadModule,
): boolean {
  const since = refineDiagCount();
  try {
    const exports = execNudoModule(text, { loadModule, fromFile });
    const v = exports[fn];
    return isNudoConstraint(v) && (v as { fn?: unknown }).fn !== undefined;
  } catch {
    return false;
  } finally {
    takeRefineDiagsSince(since);
  }
}

