/**
 * `nudo interface --emit` 的写盘器（design-refine-derivation §5.4 / §7.3 / §11）：
 * 把分析产出的调用点域投影（joinThenProject，先 Abs join 再投影）固化为侧车
 * `*.nudo.js` / `*.nudo.ts` 的 `@generated` 段——`export const <fn> = fn({…}, …)`。
 *
 * - 生成段 = 三行：`@generated` 头注释 + `// source: <相对file>:<fn>` + export 行。
 *   DSL 由 formatConstraint 产出，**写入前 round-trip 自检**（生成文本经
 *   execNudoModule 求值、导出须 isNudoConstraint 且 fn 槽存在）：展示兜底形态
 *   （`x?:` 可选字段、`.eq()` 伪链、`{谓词原文}`）不是合法 DSL，自检拦下 →
 *   not-projectable 跳过，不写垃圾。
 * - 手写导出永不覆盖：目标名已是侧车手写绑定 → 跳过写入并报
 *   `nudo:interface-name-clash`（error，手写优先）。
 * - mode=update：剥离全部生成段再重排（幂等；非目标的既有生成段原样保留，
 *   不随 --fn 丢失）；mode=add：仅追加缺失段。
 * - 目标过滤（§7.3）：--fn 白名单 > --all 全量 > 默认/--known 只刷新已有生成段
 *   （「无根只处理已存在生成段」；Phase 1 无 root 闭包下行推导）。
 * - autoBind=false 不影响 emit（显式动作，非 ambient 加载）。
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { relative, resolve } from "node:path";
import {
  execNudoModule,
  formatConstraint,
  isNudoConstraint,
  joinThenProject,
  localNamedExports,
  parseSource,
  sidecarPathOf,
  takeInterfaceDiags,
  takeRefineDiags,
  typeValueToAbs,
  type Abs,
  type NudoConstraint,
} from "@nudojs/core";
import { analyzeFileAsync, type CaseResult, type FunctionAnalysis } from "./analyzer.ts";
import type { CallRecord } from "./evaluator/evaluator.ts";
import { unifiedDiff } from "./case-emitter.ts";

export type EmitInterfaceSkipReason =
  | "name-clash"
  | "not-projectable"
  | "not-an-export"
  | "no-change";

export type EmitInterfaceOpts = {
  /** 目标导出名白名单（Phase 1：只过滤目标文件自身的导出；跨文件 root 闭包 emit 是 Phase 2 下行推导能力） */
  fnNames?: string[];
  /** update=剥离全部生成段再重排（幂等）；add=仅追加缺失段 */
  mode: "add" | "update";
  /** 只更新已有 @generated 段的导出（显式形式；默认无 --fn/--all 时同此行为） */
  knownOnly?: boolean;
  /** 全部顶层导出（显式 opt-in，CLI 侧文档警告勿默认） */
  all?: boolean;
  /** 不写盘，返回 unifiedDiff */
  dryRun?: boolean;
  /**
   * 跨文件调用记录（--callsites 采集）：域根导出（本文件无调用点、仅有
   * 外部使用现场记录）的投影原料；缺省时仅用本文件调用点证据。
   */
  records?: CallRecord[];
};

export type EmitInterfaceResult = {
  written: string[];
  skipped: Array<{ fn: string; reason: EmitInterfaceSkipReason }>;
  changed: boolean;
  diff?: string;
  issues: Array<{ code: string; severity: "error" | "warning"; message: string }>;
  /** 侧车绝对路径（新建或已有） */
  sidecarPath: string;
};

const GENERATED_HEADER =
  "// @generated by nudo — do not edit; regenerate with `nudo interface --emit`";

/** 单个生成段：注释块起点到 export 语句终点的整段切片 */
type GeneratedSection = { names: string[]; start: number; end: number; text: string };

/**
 * 单文件 emit：分析 → 逐目标投影/自检 → 组装侧车内容 →（非 dryRun）写盘。
 * 诊断 side-channel（round-trip 自检触发的 refine/interface diags）收尾取走丢弃。
 */
export async function emitInterface(
  filePath: string,
  opts: EmitInterfaceOpts,
): Promise<EmitInterfaceResult> {
  const abs = resolve(filePath);
  const source = readFileSync(abs, "utf-8");
  const sidecarPath = sidecarPathOf(abs);
  const sidecarSrc = existsSync(sidecarPath) ? readFileSync(sidecarPath, "utf-8") : "";
  const srcRel = relative(process.cwd(), abs) || abs;

  const sections = collectGeneratedSections(sidecarSrc);
  const generatedNames = new Set(sections.flatMap((s) => s.names));
  const declared = topLevelDeclaredNames(sidecarSrc);
  if (declared === undefined) {
    throw new Error(
      `sidecar '${relative(process.cwd(), sidecarPath) || sidecarPath}' is not parseable; fix it before emitting`,
    );
  }
  for (const n of generatedNames) declared.delete(n); // 手写绑定 = 顶层声明 − 生成段

  // ---- 分析（与 interfaceSurface 同一管道：analyzer 现成 case/abs 推断）----
  const analysis = await analyzeFileAsync(abs, source, undefined, opts.records);
  const exported = localNamedExports(source);
  const fnByName = new Map<string, FunctionAnalysis>();
  for (const f of analysis.functions) {
    if (!fnByName.has(f.name)) fnByName.set(f.name, f);
  }
  const fileExportOrder = analysis.functions.map((f) => f.name).filter((n) => exported.has(n));

  // ---- 目标过滤（§7.3）：白名单 > --all > 默认/--known 刷新已有生成段 ----
  let targetNames: string[];
  if (opts.fnNames && opts.fnNames.length > 0) {
    targetNames = [...new Set(opts.fnNames)];
  } else if (opts.all) {
    targetNames = fileExportOrder;
  } else {
    targetNames = fileExportOrder.filter((n) => generatedNames.has(n));
  }
  const targetSet = new Set(targetNames);

  const written: string[] = [];
  const skipped: Array<{ fn: string; reason: EmitInterfaceSkipReason }> = [];
  const issues: EmitInterfaceResult["issues"] = [];
  /** 通过全部检查的段落（名字 → 段文本）与既有段文本（update no-change 判定） */
  const accepted: Array<{ fn: string; text: string; prevText?: string }> = [];

  for (const name of targetNames) {
    if (!exported.has(name) || !fnByName.has(name)) {
      skipped.push({
        fn: name,
        reason: "not-an-export",
      });
      continue;
    }
    if (declared.has(name)) {
      skipped.push({ fn: name, reason: "name-clash" });
      issues.push({
        code: "nudo:interface-name-clash",
        severity: "error",
        message: `sidecar already has a handwritten binding '${name}' (${srcRel}); handwritten wins — skipping emit for it`,
      });
      continue;
    }
    const prev = sections.find((s) => s.names.includes(name));
    const prevText = prev === undefined ? undefined : normalizeSection(prev.text);
    const dsl = projectFunctionDsl(fnByName.get(name)!);
    if (dsl === undefined) {
      skipped.push({ fn: name, reason: "not-projectable" });
      if (prevText !== undefined) {
        // 既有生成段但今日证据不可得（如 update 未带 --callsites）：
        // 保留原段不删（update 剥离后归位原文本），绝不因证据缺失删契约
        accepted.push({ fn: name, text: prevText, prevText });
      }
      continue;
    }
    const text = sectionText(name, dsl, srcRel);
    if (!roundTrips(text, name)) {
      skipped.push({ fn: name, reason: "not-projectable" });
      if (prevText !== undefined) {
        accepted.push({ fn: name, text: prevText, prevText });
      }
      continue;
    }
    if (opts.mode === "add" && prev !== undefined) {
      skipped.push({ fn: name, reason: "no-change" });
      continue;
    }
    if (prevText !== undefined && prevText === normalizeSection(text)) {
      skipped.push({ fn: name, reason: "no-change" });
      accepted.push({ fn: name, text, prevText }); // update：内容不变也要归位（已剥离）
      continue;
    }
    written.push(name);
    accepted.push({ fn: name, text, prevText });
  }

  // ---- 组装最终内容 ----
  let finalContent: string;
  if (opts.mode === "add") {
    // add：不动既有内容，仅追加缺失段
    finalContent = joinSections(sidecarSrc, accepted.map((a) => a.text));
  } else {
    // update：剥离全部生成段；非目标段原样保留，目标段用新文本重排（幂等）
    const base = removeSections(sidecarSrc, sections);
    const preserved = sections
      .filter((s) => !s.names.some((n) => targetSet.has(n)))
      .map((s) => normalizeSection(s.text));
    finalContent = joinSections(base, [...preserved, ...accepted.map((a) => a.text)]);
  }

  const changed = finalContent !== sidecarSrc;
  const diff = changed
    ? unifiedDiff(sidecarSrc, finalContent, relative(process.cwd(), sidecarPath) || sidecarPath)
    : undefined;
  if (changed && !opts.dryRun) {
    writeFileSync(sidecarPath, finalContent, "utf-8");
  }
  takeRefineDiags(); // round-trip 自检可能留下 interface-load 诊断——emit 不执法，丢弃
  takeInterfaceDiags();

  return {
    written,
    skipped,
    changed,
    ...(diff !== undefined ? { diff } : {}),
    issues,
    sidecarPath,
  };
}

// ---------------------------------------------------------------------------
// 投影：case 证据 → fn({ params }, returns) DSL
// ---------------------------------------------------------------------------

/**
 * 单函数域投影（§4.2 工件聚合口径）：调用点域优先——callsite case 的逐位实参
 * Abs 先 join 再投影；无调用记录退 directive case；再无（entry-only）用 entry
 * 推断（仅返回位；entry 实参恒 unknown，参数位无证据不产约束）。
 * 任一有证据位 joinThenProject 落空 → undefined（not-projectable，不产垃圾）。
 */
function projectFunctionDsl(fn: FunctionAnalysis): string | undefined {
  const callsite = fn.cases.filter((c) => c.source === "callsite");
  const directive = fn.cases.filter((c) => c.source === "directive");
  const paramCases = callsite.length > 0 ? callsite : directive;
  const returnCases = callsite.length > 0 ? callsite : directive.length > 0 ? directive : fn.cases;

  const paramParts: string[] = [];
  for (let i = 0; i < fn.paramNames.length; i++) {
    const argAbs: Abs[] = [];
    for (const c of paramCases) {
      const a = c.args[i];
      if (a === undefined) continue;
      argAbs.push(safeTypeValueToAbs(a));
    }
    if (argAbs.length === 0) continue; // 无证据：参数位留空（不产约束）
    const constraint = joinThenProject(argAbs);
    if (constraint === undefined) return undefined;
    paramParts.push(`${fn.paramNames[i]!}: ${formatConstraint(constraint)}`);
  }

  // 返回位：排除 throw case（其 result 是抛出值不是返回值）
  const retAbs: Abs[] = [];
  for (const c of returnCases) {
    if (c.throws !== undefined && c.throws.kind !== "never") continue;
    retAbs.push(c.abs ?? safeTypeValueToAbs(c.result));
  }
  const retConstraint: NudoConstraint | undefined =
    retAbs.length > 0 ? joinThenProject(retAbs) : undefined;
  if (retConstraint === undefined && paramParts.length === 0) return undefined; // 完全无证据
  if (retAbs.length > 0 && retConstraint === undefined) return undefined; // 有证据但不可表达

  const ret = retConstraint === undefined ? "" : `, ${formatConstraint(retConstraint)}`;
  return `fn({ ${paramParts.join(", ")} }${ret})`;
}

function safeTypeValueToAbs(v: Parameters<typeof typeValueToAbs>[0]): Abs {
  try {
    return typeValueToAbs(v);
  } catch {
    return { shape: { k: "unknown" }, conf: "opaque" } as Abs; // 不可桥 → 必然不可投影
  }
}

// ---------------------------------------------------------------------------
// 生成段文本 / round-trip 自检
// ---------------------------------------------------------------------------

function sectionText(fn: string, dsl: string, srcRel: string): string {
  return `${GENERATED_HEADER}\n// source: ${srcRel}:${fn}\nexport const ${fn} = ${dsl};\n`;
}

/**
 * 写入前自检：生成文本必须可执行——经 execNudoModule 求值、导出为
 * isNudoConstraint 且 fn 槽存在。展示兜底形态（`x?:`、`.eq()` 伪链、
 * `{谓词原文}`、`any()`）在此被拦下 → 调用方按 not-projectable 跳过。
 */
function roundTrips(text: string, fn: string): boolean {
  try {
    const exports = execNudoModule(text);
    const v = exports[fn];
    return isNudoConstraint(v) && v.fn !== undefined;
  } catch {
    return false;
  } finally {
    takeRefineDiags(); // 自检触发的诊断不外泄（add 侧车导出形式提示等）
  }
}

// ---------------------------------------------------------------------------
// 侧车结构：生成段识别（与 interface.ts generatedExportNames 同口径）/ 剥离
// ---------------------------------------------------------------------------

/**
 * 侧车里的生成段：ExportNamedDeclaration 且前置注释块含 `@generated`
 * （识别口径与 core/algebra/interface.ts 的 generatedExportNames 一致——
 * 从语句 start 向上扫连续注释块，空行可跨）。
 */
function collectGeneratedSections(sidecarSrc: string): GeneratedSection[] {
  if (sidecarSrc.trim() === "") return [];
  let ast: ReturnType<typeof parseSource>;
  try {
    ast = parseSource(sidecarSrc);
  } catch {
    throw new Error("sidecar is not parseable"); // 由调用方补充路径上下文
  }
  const out: GeneratedSection[] = [];
  for (const stmt of ast.program.body) {
    if (stmt.type !== "ExportNamedDeclaration" || stmt.source) continue;
    const d = stmt.declaration;
    if (!d || stmt.start == null || stmt.end == null) continue;
    const names: string[] = [];
    if (d.type === "VariableDeclaration") {
      for (const decl of d.declarations) {
        if (decl.id.type === "Identifier") names.push(decl.id.name);
      }
    } else if (d.type === "FunctionDeclaration" || d.type === "ClassDeclaration") {
      if (d.id) names.push(d.id.name);
    }
    if (names.length === 0) continue;
    const blockStart = generatedCommentBlockStart(sidecarSrc, stmt.start);
    if (blockStart === undefined) continue;
    out.push({ names, start: blockStart, end: stmt.end, text: sidecarSrc.slice(blockStart, stmt.end) });
  }
  return out;
}

/**
 * 从语句起点向上找含 `@generated` 的连续注释块的字节起点；块内无标记或
 * 起点上方不是注释块 → undefined（跳过规则与 leadingCommentHas 镜像：
 * 空行与 `\*\/` 可跨，遇代码行停）。
 */
function generatedCommentBlockStart(src: string, pos: number): number | undefined {
  const lines = src.slice(0, pos).split("\n");
  let blockStartLine = -1;
  let sawGenerated = false;
  for (let i = lines.length - 1; i >= 0; i--) {
    const line = lines[i]!.trim();
    if (line === "" || line === "*/") continue;
    if (line.startsWith("//") || line.startsWith("/*") || line.startsWith("*")) {
      blockStartLine = i;
      if (/@generated/.test(line)) sawGenerated = true;
      continue;
    }
    break;
  }
  if (!sawGenerated || blockStartLine < 0) return undefined;
  const prefix = lines.slice(0, blockStartLine);
  // blockStartLine===0 → 字节 0（首行即注释块，无前导换行可跳）
  return prefix.length === 0 ? 0 : prefix.join("\n").length + 1;
}

/**
 * 侧车顶层声明名表（变量声明/函数/类 + export 列形式），供 name-clash 判定；
 * 解析失败 → undefined（调用方报错，不盲目追加造成重复导出）。
 */
function topLevelDeclaredNames(sidecarSrc: string): Set<string> | undefined {
  if (sidecarSrc.trim() === "") return new Set();
  let ast: ReturnType<typeof parseSource>;
  try {
    ast = parseSource(sidecarSrc);
  } catch {
    return undefined;
  }
  const names = new Set<string>();
  const collect = (stmt: ReturnType<typeof parseSource>["program"]["body"][number]): void => {
    if (stmt.type === "VariableDeclaration") {
      for (const d of stmt.declarations) {
        if (d.id.type === "Identifier") names.add(d.id.name);
      }
    } else if (stmt.type === "FunctionDeclaration" || stmt.type === "ClassDeclaration") {
      if (stmt.id) names.add(stmt.id.name);
    }
  };
  for (const stmt of ast.program.body) {
    if (stmt.type === "ExportNamedDeclaration") {
      if (stmt.declaration) collect(stmt.declaration);
      for (const spec of stmt.specifiers) {
        names.add(spec.exported.type === "Identifier" ? spec.exported.name : spec.exported.value);
      }
    } else {
      collect(stmt);
    }
  }
  return names;
}

/** 从内容中切除指定生成段（[注释块起点, 语句终点]），其余字节不动 */
function removeSections(src: string, sections: GeneratedSection[]): string {
  if (sections.length === 0) return src;
  const sorted = [...sections].sort((a, b) => a.start - b.start);
  let out = "";
  let pos = 0;
  for (const s of sorted) {
    out += src.slice(pos, s.start);
    pos = Math.max(pos, s.end);
  }
  out += src.slice(pos);
  return out;
}

/** 段文本归一：尾随空白（含无空白情形）统一压成单个换行（幂等键比较 / 重排拼接用） */
function normalizeSection(text: string): string {
  return text.replace(/\s*$/, "") + "\n";
}

/** 基底 + 段落组装：基底尾随空白压成单换行，段间空一行；空基底段顶格 */
function joinSections(base: string, sectionTexts: string[]): string {
  const normalized = sectionTexts.map(normalizeSection).filter((t) => t.trim() !== "");
  const trimmed = base.replace(/\s+$/, "");
  if (normalized.length === 0) return trimmed === "" ? "" : `${trimmed}\n`;
  const lead = trimmed === "" ? "" : `${trimmed}\n\n`;
  return lead + normalized.join("\n");
}
