/**
 * nudo:interface-domain-exceeds 端到端（T10b）：
 *
 * - analyzer 注入消费区接线：externalCallRecords → 归属守卫 → 手写契约
 *   （源码 @nudo:contract / 侧车同名绑定，defaultLoadModule 真实读盘）→
 *   字面量域证据执法；恰一条 error 诊断，range 落在被调函数声明处
 * - generated / 无契约 / 证据合规 / 非本文件归属记录 → 零新诊断
 * - real-package zero-FP：真实包（ms / kleur）注入记录回灌 analyzeFile，
 *   证明接线在真实包上不产生 domain-exceeds FP（夹具包声明在 core
 *   devDependencies，createRequire 从 core 位置按 Node 解析规则定位——
 *   沿用 check-real-packages.test.ts 方案）
 */
import { describe, it, expect } from "vitest";
import { mkdtempSync, writeFileSync, rmSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { analyzeFile, collectCallRecords, type CallRecord } from "../analyzer.ts";
import { numLit, strLit, abs as makeAbs } from "@nudojs/core";

const DOMAIN = "nudo:interface-domain-exceeds";
const neverAbs = () => makeAbs({ k: "never" }, undefined, undefined, "exact");

const rec = (over: Partial<CallRecord>): CallRecord => ({
  fnName: "area",
  argAbs: [strLit("a")],
  resultAbs: numLit(1),
  throwsAbs: neverAbs(),
  ...over,
});

describe("nudo:interface-domain-exceeds（analyzer 注入消费区接线）", () => {
  it("手写侧车契约 + 注入 \"a\" 证据 → 恰一条 error，range 在被调函数声明处", () => {
    const dir = mkdtempSync(join(tmpdir(), "nudo-dom-"));
    try {
      const libSrc = `export function area(x) {
  return x;
}
`;
      const libPath = join(dir, "lib.js");
      writeFileSync(libPath, libSrc);
      writeFileSync(
        join(dir, "lib.nudo.js"),
        'import { fn, number } from "@nudojs/core";\nexport const area = fn({ x: number().gt(0) });\n',
      );
      const result = analyzeFile(libPath, libSrc, undefined, [
        rec({ targetModule: libPath, targetExport: "area", callLoc: { line: 3, column: 0 } }),
      ]);
      const issues = result.diagnostics.filter((d) => d.code === DOMAIN);
      expect(issues).toHaveLength(1);
      expect(issues[0]!.severity).toBe("error");
      // loc 用被调函数声明处（line 1，`export function area`），不是使用现场 line 3
      expect(issues[0]!.range.start.line).toBe(1);
      expect(issues[0]!.message).toContain("area");
      expect(issues[0]!.message).toContain("x");
      expect((issues[0]!.data as { actual?: string }).actual).toBe('"a"');
      expect((issues[0]!.data as { expected?: string }).expected).toBe("number().gt(0)");
      // 诊断是纯增量：不污染 case 合成（证据记录仍合成 call@ case）
      const area = result.functions.find((f) => f.name === "area")!;
      expect(area.cases.some((c) => c.source === "callsite")).toBe(true);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it("源码 @nudo:contract 手写契约（std 侧车经 defaultLoadModule 读盘）→ 执法", () => {
    const dir = mkdtempSync(join(tmpdir(), "nudo-dom-"));
    try {
      writeFileSync(
        join(dir, "std.nudo.js"),
        'import { number } from "@nudojs/core";\nexport const positive = number().gt(0);\n',
      );
      const libSrc = `/// @nudo:import { positive } from "./std.nudo.js"
/**
 * @nudo:contract x positive
 */
export function area(x) {
  return x;
}
`;
      const libPath = join(dir, "lib.js");
      writeFileSync(libPath, libSrc);
      const result = analyzeFile(libPath, libSrc, undefined, [
        rec({ targetModule: libPath, targetExport: "area" }),
      ]);
      const issues = result.diagnostics.filter((d) => d.code === DOMAIN);
      expect(issues).toHaveLength(1);
      expect(issues[0]!.severity).toBe("error");
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it("证据 ⊆ 手写契约 → 零新诊断", () => {
    const dir = mkdtempSync(join(tmpdir(), "nudo-dom-"));
    try {
      const libSrc = `export function area(x) {
  return x;
}
`;
      const libPath = join(dir, "lib.js");
      writeFileSync(libPath, libSrc);
      writeFileSync(
        join(dir, "lib.nudo.js"),
        'import { fn, number } from "@nudojs/core";\nexport const area = fn({ x: number().gt(0) });\n',
      );
      const result = analyzeFile(libPath, libSrc, undefined, [
        rec({ argAbs: [numLit(5)], targetModule: libPath, targetExport: "area" }),
        rec({ argAbs: [numLit(1)], targetModule: libPath, targetExport: "area" }),
      ]);
      expect(result.diagnostics.filter((d) => d.code === DOMAIN)).toEqual([]);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it("generated 侧车不执法（过期归 nudo:interface-drift，T10a）", () => {
    const dir = mkdtempSync(join(tmpdir(), "nudo-dom-"));
    try {
      const libSrc = `export function area(x) {
  return x;
}
`;
      const libPath = join(dir, "lib.js");
      writeFileSync(libPath, libSrc);
      writeFileSync(
        join(dir, "lib.nudo.js"),
        'import { fn, number } from "@nudojs/core";\n// @generated by nudo — do not edit\nexport const area = fn({ x: number().gt(0) });\n',
      );
      const result = analyzeFile(libPath, libSrc, undefined, [
        rec({ targetModule: libPath, targetExport: "area" }),
      ]);
      expect(result.diagnostics.filter((d) => d.code === DOMAIN)).toEqual([]);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it("归属守卫：指向其他模块的注入记录（fnName 撞名）不触发", () => {
    const dir = mkdtempSync(join(tmpdir(), "nudo-dom-"));
    try {
      const libSrc = `export function area(x) {
  return x;
}
`;
      const libPath = join(dir, "lib.js");
      writeFileSync(libPath, libSrc);
      writeFileSync(
        join(dir, "lib.nudo.js"),
        'import { fn, number } from "@nudojs/core";\nexport const area = fn({ x: number().gt(0) });\n',
      );
      const result = analyzeFile(libPath, libSrc, undefined, [
        // 使用现场另有同名 area（别的文件）：fnModule/targetModule 都不指向本文件
        rec({ fnModule: "/elsewhere/other.js", targetModule: "/elsewhere/other.js" }),
      ]);
      expect(result.diagnostics.filter((d) => d.code === DOMAIN)).toEqual([]);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it("带 @nudo:case 的导出函数同样执法（此前盲区）", () => {
    const dir = mkdtempSync(join(tmpdir(), "nudo-dom-case-"));
    try {
      const withCase = `// @nudo:case "ok" (5)
export function area(x) {
  return x;
}
`;
      const libPath = join(dir, "lib.js");
      writeFileSync(libPath, withCase);
      writeFileSync(
        join(dir, "lib.nudo.js"),
        'import { fn, number } from "@nudojs/core";\nexport const area = fn({ x: number().gt(0) });\n',
      );
      const result = analyzeFile(libPath, withCase, undefined, [
        rec({ targetModule: libPath, targetExport: "area", callLoc: { line: 5, column: 0 } }),
      ]);
      const issues = result.diagnostics.filter((d) => d.code === DOMAIN);
      expect(issues).toHaveLength(1);
      expect(issues[0]!.severity).toBe("error");
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe("real-package zero-FP：真实包注入记录不产生 domain-exceeds", () => {
  /**
   * 夹具包声明在 core devDependencies（沿 check-real-packages.test.ts 的
   * createRequire 方案）；service 侧从 core 位置按 Node 解析规则定位。
   */
  const coreRequire = createRequire(
    join(dirname(fileURLToPath(import.meta.url)), "../../../core/src/index.ts"),
  );

  /** 正例对照：同一套 analyzeFile 接线对手写契约 + 越域证据必须报（证明夹具带电） */
  function positiveControl(dir: string): void {
    const libSrc = `export function area(x) {
  return x;
}
`;
    const libPath = join(dir, "lib.js");
    writeFileSync(libPath, libSrc);
    writeFileSync(
      join(dir, "lib.nudo.js"),
      'import { fn, number } from "@nudojs/core";\nexport const area = fn({ x: number().gt(0) });\n',
    );
    const result = analyzeFile(libPath, libSrc, undefined, [
      rec({ targetModule: libPath, targetExport: "area" }),
    ]);
    expect(result.diagnostics.filter((d) => d.code === DOMAIN).length).toBe(1);
  }

  it("ms / kleur：真实使用现场记录回灌被调文件，零 domain-exceeds", () => {
    const dir = mkdtempSync(join(tmpdir(), "nudo-real-"));
    try {
      positiveControl(dir);

      const msEntry = coreRequire.resolve("ms");
      const kleurEntry = coreRequire.resolve("kleur");
      const usageSrc = `
const ms = require(${JSON.stringify(msEntry)});
ms(5000);
ms("2 days");
ms("1h");
const kleur = require(${JSON.stringify(kleurEntry)});
kleur.red("text");
kleur.bold("bold text");
kleur.blue(42);
`;
      const usagePath = join(dir, "usage.js");
      writeFileSync(usagePath, usageSrc);
      const records = collectCallRecords(usagePath, usageSrc);

      // 夹具带电三重断言：有记录、有字面量实参证据、有指向包内文件的归属
      expect(records.length).toBeGreaterThan(0);
      expect(records.some((r) => r.argAbs.some((a) => a.term?.op === "lit"))).toBe(true);
      const targets = new Set(
        records
          .flatMap((r) => [r.targetModule, r.fnModule])
          .filter((p): p is string => p !== undefined),
      );
      expect(targets.size).toBeGreaterThan(0);

      for (const target of [...targets].slice(0, 6)) {
        const result = analyzeFile(target, readFileSync(target, "utf-8"), undefined, records);
        const fps = result.diagnostics.filter((d) => d.code === DOMAIN);
        expect(fps, `${target}:\n${fps.map((f) => f.message).join("\n")}`).toEqual([]);
      }
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});
