/**
 * interfaceSurface：`nudo interface` 打印数据源——分层展示（handwritten /
 * generated / implicit）、autoBind 配置链（opts 覆盖 + package.json#nudo.interface）、
 * kind（export/local 按自动绑定口径 localNamedExports）。
 * 真实临时目录夹具（defaultLoadModule 真实读盘，与 CLI 路径一致）。
 */
import { describe, it, expect, afterAll } from "vitest";
import { mkdtempSync, writeFileSync, mkdirSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { interfaceSurface } from "../interface-surface.ts";
import { T, typeValueToAbs } from "@nudojs/core";

const dirs: string[] = [];
afterAll(() => {
  for (const d of dirs) rmSync(d, { recursive: true, force: true });
});

function makeFixture(files: Record<string, string>): string {
  const root = mkdtempSync(join(tmpdir(), "nudo-iface-surface-"));
  dirs.push(root);
  for (const [rel, content] of Object.entries(files)) {
    const p = join(root, rel);
    mkdirSync(dirname(p), { recursive: true });
    writeFileSync(p, content);
  }
  return root;
}

const LIB_JS = `
export function add(x) {
  return x + 2;
}

function helper(n) {
  return n * 2;
}
`;

const STD_NUDO_JS = `
import { number } from "@nudojs/core";
export const positive = number().gt(0);
`;

const LIB_NUDO_JS = `
import { fn } from "@nudojs/core";
import { positive } from "./std.nudo.js";

export const add = fn({ x: positive }, positive.shift(2));
`;

const LIB_NUDO_GENERATED_JS = `
import { fn, number } from "@nudojs/core";

// @generated by nudo — do not edit; regenerate with \`nudo interface --emit\`
export const add = fn({ x: number() });
`;

const CALLS_JS = `
export function double(x) {
  return x * 2;
}

double(21);
`;

describe("interfaceSurface", () => {
  it("handwritten sidecar binding wins: formatConstraint display + export kind", async () => {
    const root = makeFixture({
      "lib.js": LIB_JS,
      "lib.nudo.js": LIB_NUDO_JS,
      "std.nudo.js": STD_NUDO_JS,
    });
    const entries = await interfaceSurface(join(root, "lib.js"));

    const add = entries.find((e) => e.fn === "add");
    expect(add).toBeDefined();
    expect(add!.kind).toBe("export");
    expect(add!.source).toBe("handwritten");
    expect(add!.params).toEqual([{ name: "x", display: "number().gt(0)" }]);
    expect(add!.returns).toBe("number().gt(2)");

    // 无契约的本地函数：implicit + local
    const helper = entries.find((e) => e.fn === "helper");
    expect(helper).toBeDefined();
    expect(helper!.kind).toBe("local");
    expect(helper!.source).toBe("implicit");
    expect(helper!.params).toEqual([{ name: "n", display: "unknown" }]); // entry@ 回退
    expect(helper!.returns).toBe("number");
  });

  it("generated sidecar segment reports generated source (returns optional)", async () => {
    const root = makeFixture({
      "lib.js": LIB_JS,
      "lib.nudo.js": LIB_NUDO_GENERATED_JS,
      "std.nudo.js": STD_NUDO_JS,
    });
    const entries = await interfaceSurface(join(root, "lib.js"));
    const add = entries.find((e) => e.fn === "add");
    expect(add).toBeDefined();
    expect(add!.source).toBe("generated");
    expect(add!.params).toEqual([{ name: "x", display: "number()" }]);
    expect(add!.returns).toBeUndefined();
  });

  it("no sidecar, no refine: implicit shows analyzer inference content", async () => {
    const root = makeFixture({ "calls.js": CALLS_JS });
    const entries = await interfaceSurface(join(root, "calls.js"));
    const dbl = entries.find((e) => e.fn === "double");
    expect(dbl).toBeDefined();
    expect(dbl!.kind).toBe("export");
    expect(dbl!.source).toBe("implicit");
    expect(dbl!.params[0]!.name).toBe("x");
    // 调用点合成 case 的实参/结果直接展示（字面量精度，不强求约束式）
    expect(dbl!.params[0]!.display).toBe("21");
    expect(dbl!.returns).toBe("42");
  });

  it("autoBind:false (opts override) skips the sidecar → implicit", async () => {
    const root = makeFixture({
      "lib.js": LIB_JS,
      "lib.nudo.js": LIB_NUDO_JS,
      "std.nudo.js": STD_NUDO_JS,
    });
    const entries = await interfaceSurface(join(root, "lib.js"), { autoBind: false });
    const add = entries.find((e) => e.fn === "add");
    expect(add).toBeDefined();
    expect(add!.source).toBe("implicit");
  });

  it("autoBind flows from package.json#nudo.interface (config wiring)", async () => {
    const off = makeFixture({
      "package.json": JSON.stringify({ name: "fx", nudo: { interface: { autoBind: false } } }),
      "lib.js": LIB_JS,
      "lib.nudo.js": LIB_NUDO_JS,
      "std.nudo.js": STD_NUDO_JS,
    });
    const offAdd = (await interfaceSurface(join(off, "lib.js"))).find((e) => e.fn === "add");
    expect(offAdd!.source).toBe("implicit"); // 配置关掉自动绑定 → 侧车不读

    const on = makeFixture({
      "package.json": JSON.stringify({ name: "fx", nudo: { interface: {} } }),
      "lib.js": LIB_JS,
      "lib.nudo.js": LIB_NUDO_JS,
      "std.nudo.js": STD_NUDO_JS,
    });
    const onAdd = (await interfaceSurface(join(on, "lib.js"))).find((e) => e.fn === "add");
    expect(onAdd!.source).toBe("handwritten"); // 默认 autoBind:true
  });

  it("cross-file records feed the implicit domain display", async () => {
    const root = makeFixture({ "lib.js": `export function scale(x) {\n  return x * 2;\n}\n` });
    const libPath = join(root, "lib.js");
    const rec = (arg: string | number | boolean | null | undefined) => ({
      fnName: "scale",
      targetModule: libPath,
      targetExport: "scale",
      argAbs: [typeValueToAbs(T.literal(arg))],
      resultAbs: typeValueToAbs(T.literal(84)),
      throwsAbs: typeValueToAbs(T.never),
      callLoc: { line: 3, column: 0 },
    });
    const entries = await interfaceSurface(libPath, { records: [rec(42), rec("a")] });
    const scale = entries.find((e) => e.fn === "scale");
    expect(scale).toBeDefined();
    expect(scale!.source).toBe("implicit");
    expect(scale!.params[0]!.display).toBe('42 | "a"');
  });
});
