/**
 * `nudo contract --emit` 写盘器（service/interface-emitter.ts）：
 * 生成段写盘 / name-clash（手写优先）/ update 幂等 / 默认只刷新已有段 /
 * dryRun / not-projectable / 写盘产物可被 effectiveInterface 读回。
 */
import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtempSync, writeFileSync, readFileSync, rmSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { emitInterface } from "../interface-emitter.ts";
import { effectiveInterface, numLit, strLit, abs as makeAbs } from "@nudojs/core";

let dir: string;

beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), "nudo-emit-"));
});

afterEach(() => {
  rmSync(dir, { recursive: true, force: true });
});

const ADD_JS = `export function add2(x) {\n  return x + 2;\n}\n\nadd2(42);\n`;

describe("emitInterface", () => {
  it("creates sidecar with @generated segment for the named export", async () => {
    const file = join(dir, "add.js");
    writeFileSync(file, ADD_JS);
    const r = await emitInterface(file, { fnNames: ["add2"], mode: "add" });
    expect(r.written).toEqual(["add2"]);
    expect(r.issues).toEqual([]);
    const sidecar = readFileSync(join(dir, "add.nudo.js"), "utf-8");
    expect(sidecar).toContain("// @generated by nudo — do not edit");
    expect(sidecar).toContain("// source: ");
    expect(sidecar).toContain("add.js:add2");
    expect(sidecar).toContain("export const add2 = fn({ x: lit(42) }, lit(44));");
  });

  it("emitted sidecar reads back as source=generated via effectiveInterface", async () => {
    const file = join(dir, "add.js");
    writeFileSync(file, ADD_JS);
    await emitInterface(file, { fnNames: ["add2"], mode: "add" });
    const loadModule = (spec: string, from: string): string | undefined => {
      if (!spec.startsWith(".")) return undefined;
      const parts = from.split("/").slice(0, -1);
      for (const seg of spec.split("/")) {
        if (seg === "" || seg === ".") continue;
        if (seg === "..") parts.pop();
        else parts.push(seg);
      }
      try {
        return readFileSync(parts.join("/"), "utf-8");
      } catch {
        return undefined;
      }
    };
    const eff = effectiveInterface(ADD_JS, "add2", { loadModule, fromFile: file });
    expect(eff).toBeDefined();
    expect(eff!.source).toBe("generated");
    expect(eff!.params.map((p) => p.param)).toEqual(["x"]);
  });

  it("skips with nudo:interface-name-clash when sidecar has a handwritten binding", async () => {
    const file = join(dir, "add.js");
    writeFileSync(file, ADD_JS);
    const sidecar = join(dir, "add.nudo.js");
    writeFileSync(sidecar, `export const add2 = fn({ x: number() });\n`);
    const r = await emitInterface(file, { fnNames: ["add2"], mode: "add" });
    expect(r.written).toEqual([]);
    expect(r.skipped).toEqual([{ fn: "add2", reason: "name-clash" }]);
    expect(r.issues.some((i) => i.code === "nudo:interface-name-clash" && i.severity === "error")).toBe(true);
    expect(r.changed).toBe(false);
    expect(readFileSync(sidecar, "utf-8")).toBe(`export const add2 = fn({ x: number() });\n`);
  });

  it("update mode is idempotent (second run reports no change)", async () => {
    const file = join(dir, "add.js");
    writeFileSync(file, ADD_JS);
    const r1 = await emitInterface(file, { fnNames: ["add2"], mode: "update" });
    expect(r1.written).toEqual(["add2"]);
    const sidecar = readFileSync(join(dir, "add.nudo.js"), "utf-8");
    const r2 = await emitInterface(file, { fnNames: ["add2"], mode: "update" });
    expect(r2.changed).toBe(false);
    expect(r2.skipped.some((s) => s.fn === "add2" && s.reason === "no-change")).toBe(true);
    expect(readFileSync(join(dir, "add.nudo.js"), "utf-8")).toBe(sidecar);
  });

  it("default (no filter) refreshes only already-persisted generated segments", async () => {
    const src = `${ADD_JS}\nexport function other(y) {\n  return y * 2;\n}\n\nother(3);\n`;
    const file = join(dir, "add.js");
    writeFileSync(file, src);
    // 先只固化 add2
    await emitInterface(file, { fnNames: ["add2"], mode: "add" });
    // 无过滤再跑：只刷新 add2 的生成段，不碰 other（未固化）
    const r = await emitInterface(file, { mode: "update" });
    expect(r.written).toEqual([]);
    expect(existsSync(join(dir, "add.nudo.js"))).toBe(true);
    const sidecar = readFileSync(join(dir, "add.nudo.js"), "utf-8");
    expect(sidecar).not.toContain("other");
    // --all 才会补 other
    const rAll = await emitInterface(file, { mode: "update", all: true });
    expect(rAll.written).toContain("other");
    expect(readFileSync(join(dir, "add.nudo.js"), "utf-8")).toContain("other");
  });

  it("dryRun reports diff without writing to disk", async () => {
    const file = join(dir, "add.js");
    writeFileSync(file, ADD_JS);
    const r = await emitInterface(file, { fnNames: ["add2"], mode: "add", dryRun: true });
    expect(r.changed).toBe(true);
    expect(r.diff).toBeDefined();
    expect(r.diff).toContain("+export const add2");
    expect(existsSync(join(dir, "add.nudo.js"))).toBe(false);
  });

  it("skips not-projectable when there is no derivable evidence", async () => {
    const file = join(dir, "lonely.js");
    writeFileSync(file, `export function lonely(x) {\n  return x;\n}\n`);
    const r = await emitInterface(file, { fnNames: ["lonely"], mode: "add" });
    expect(r.written).toEqual([]);
    expect(r.skipped).toEqual([{ fn: "lonely", reason: "not-projectable" }]);
    expect(existsSync(join(dir, "lonely.nudo.js"))).toBe(false);
  });

  it("skips not-an-export for names that are not local exports of the file", async () => {
    const file = join(dir, "add.js");
    writeFileSync(file, ADD_JS);
    const r = await emitInterface(file, { fnNames: ["nope"], mode: "add" });
    expect(r.written).toEqual([]);
    expect(r.skipped).toEqual([{ fn: "nope", reason: "not-an-export" }]);
    expect(r.changed).toBe(false);
  });

  it("cross-file records project a domain-root export to a union contract", async () => {
    // 设计验收（§11）：域根导出——本文件无调用点，域证据全部来自 --callsites
    const file = join(dir, "mixed.js");
    writeFileSync(file, `export function scale(x) {\n  return x * 2;\n}\n`);
    const rec = (arg: string | number | boolean | null | undefined) => {
      const argAbs =
        typeof arg === "number"
          ? numLit(arg)
          : typeof arg === "string"
            ? strLit(arg)
            : typeof arg === "boolean"
              ? makeAbs({ k: "prim", type: "boolean" }, { op: "lit", value: arg }, undefined, "exact")
              : makeAbs({ k: "unknown" }, { op: "lit", value: arg ?? null }, undefined, "exact");
      return {
        fnName: "scale",
        targetModule: file,
        targetExport: "scale",
        argAbs: [argAbs],
        resultAbs: numLit(84),
        throwsAbs: makeAbs({ k: "never" }, undefined, undefined, "exact"),
        callLoc: { line: 3, column: 0 },
      };
    };
    const r = await emitInterface(file, {
      fnNames: ["scale"],
      mode: "add",
      records: [rec(42), rec("a")],
    });
    expect(r.written).toEqual(["scale"]);
    const sidecar = readFileSync(join(dir, "mixed.nudo.js"), "utf-8");
    expect(sidecar).toContain(
      "export const scale = fn({ x: union(lit(42), lit(\"a\")) }, number());",
    );
  });

  it("multi-declarator generated section kept atomically (no duplicate declarations)", async () => {
    // R10 边界：手工合并的多声明符生成段。按名归位会把整段复制给每个
    // 证据缺失的名字 + 可重写兄弟的新段 → 重复声明、侧车不可解析。
    // 段内任一名字不可重写（lonely 无调用点证据）→ 整段原样保留，全部
    // 名字跳过（multi-declarator），侧车保持可解析。
    const file = join(dir, "pair.js");
    writeFileSync(
      file,
      `export function add2(x) {\n  return x + 2;\n}\n\nexport function lonely(y) {\n  return y;\n}\n\nadd2(42);\n`,
    );
    const sidecarPath = join(dir, "pair.nudo.js");
    writeFileSync(
      sidecarPath,
      `// @generated by nudo — do not edit; regenerate with \`nudo contract --emit\`\n// source: pair.js\n` +
        `export const add2 = fn({ x: lit(42) }, lit(44)), lonely = fn({ y: number() });\n`,
    );
    const r = await emitInterface(file, { mode: "update", all: true });
    // add2 今日可投影，但段原子保留 → 整段不动、两名字均 skip
    expect(r.written).toEqual([]);
    const skipped = new Map(r.skipped.map((s) => [s.fn, s.reason]));
    expect(skipped.get("add2")).toBe("multi-declarator");
    expect(skipped.get("lonely")).toBe("multi-declarator");
    expect(r.issues.some((i) => i.code === "nudo:interface-multi-declarator")).toBe(true);
    // 侧车仍可解析、无重复声明（exec 不 throw）
    const after = readFileSync(sidecarPath, "utf-8");
    const { execNudoModule } = await import("@nudojs/core");
    const exports = execNudoModule(after);
    expect(Object.keys(exports).sort()).toEqual(["add2", "lonely"]);
  });

  it("multi-declarator section with all names re-emittable splits into single sections", async () => {
    const file = join(dir, "pair2.js");
    writeFileSync(
      file,
      `export function add2(x) {\n  return x + 2;\n}\n\nexport function triple(y) {\n  return y * 3;\n}\n\nadd2(42);\ntriple(7);\n`,
    );
    const sidecarPath = join(dir, "pair2.nudo.js");
    writeFileSync(
      sidecarPath,
      `// @generated by nudo — do not edit; regenerate with \`nudo contract --emit\`\n// source: pair2.js\n` +
        `export const add2 = fn({ x: lit(42) }, lit(44)), triple = fn({ y: lit(7) }, lit(21));\n`,
    );
    const r = await emitInterface(file, { mode: "update", all: true });
    expect(r.written.sort()).toEqual(["add2", "triple"]);
    const after = readFileSync(sidecarPath, "utf-8");
    // 拆成两个单名段（不再多声明符）；无重复声明
    expect(after.match(/export const /g)!.length).toBe(2);
    const { execNudoModule } = await import("@nudojs/core");
    const exports = execNudoModule(after);
    expect(Object.keys(exports).sort()).toEqual(["add2", "triple"]);
  });

  it("update without evidence preserves persisted segments (no data loss)", async () => {
    // 回归：update 剥离生成段后若重投影失败（证据缺失），既有段必须原样
    // 归位，不得被静默删除（默认无 --callsites 的典型场景）。
    const file = join(dir, "mixed.js");
    writeFileSync(file, `export function scale(x) {\n  return x * 2;\n}\n`);
    const rec = (arg: string | number | boolean | null | undefined) => {
      const argAbs =
        typeof arg === "number"
          ? numLit(arg)
          : typeof arg === "string"
            ? strLit(arg)
            : typeof arg === "boolean"
              ? makeAbs({ k: "prim", type: "boolean" }, { op: "lit", value: arg }, undefined, "exact")
              : makeAbs({ k: "unknown" }, { op: "lit", value: arg ?? null }, undefined, "exact");
      return {
        fnName: "scale",
        targetModule: file,
        targetExport: "scale",
        argAbs: [argAbs],
        resultAbs: numLit(84),
        throwsAbs: makeAbs({ k: "never" }, undefined, undefined, "exact"),
        callLoc: { line: 3, column: 0 },
      };
    };
    const first = await emitInterface(file, { fnNames: ["scale"], mode: "add", records: [rec(42)] });
    expect(first.written).toEqual(["scale"]);
    const before = readFileSync(join(dir, "mixed.nudo.js"), "utf-8");
    const second = await emitInterface(file, { mode: "update" });
    expect(second.changed).toBe(false);
    expect(readFileSync(join(dir, "mixed.nudo.js"), "utf-8")).toBe(before);
    expect(second.skipped).toContainEqual({ fn: "scale", reason: "not-projectable" });
  });
});
