/**
 * Homepage content constants (copy, code samples, comparison rows, feature lists).
 * Kept free of React so `src/pages/index.tsx` stays a thin layout layer.
 *
 * Translate ids are the i18n contract — do not rename without updating
 * `i18n/zh-Hans/code.json`.
 */

/* ── Shared product example ────────────────────────────────────────────────
   Inlays follow product semantics:
   - Function body: algebraic Abs (sidecar vars / path preds). No concrete
     case bindings unless a call-site / @nudo:case is in view.
   - calls.js tab: concrete call-site facts + contract gate.
   ------------------------------------------------------------------------ */

/** Lines are 1-based; inlay = always-visible hint, detail = hover panel. */
export type LineHint = { line: number; inlay: string; detail: string };

export const sourceCode = `export function lineTotal(price, qty) {
  return price * qty;
}

export function applyCoupon(order, code) {
  const rate =
    code === "VIP10" ? 0.1 :
    code === "VIP20" ? 0.2 : 0;
  return {
    ...order,
    total: order.subtotal * (1 - rate),
    coupon: rate > 0 ? code : null,
  };
}`;

/* Algebraic inlays — no case, no concrete "when" */
export const sourceHints: LineHint[] = [
  {
    line: 1,
    inlay: "price: number · price > 0",
    detail:
      "param  price\nshape  number\npred   price > 0     // sidecar\nconf   path\n\nqty    number · qty ≥ 1",
  },
  {
    line: 2,
    inlay: "term (price × qty) · > 0",
    detail:
      "return\n  term  (price * qty)\n  pred  (price * qty) > 0\n        // price>0 ∧ qty≥1  ⇒  product > 0\n        // aligns with sidecar return number().gt(0)\n  conf  path\n\n(no concrete case — algebraic entry vars)",
  },
  {
    line: 5,
    inlay: "order shape · code: string",
    detail:
      "param  order\n  shape  { subtotal ≥ 0; items ≥ 0 }\n  conf   path (sidecar)\nparam  code\n  shape  string\n  conf   path",
  },
  {
    line: 8,
    inlay: "rate ∈ {0, 0.1, 0.2}",
    detail:
      "term   rate\npred   rate = 0 ∨ rate = 0.1 ∨ rate = 0.2\n       // path-narrowed on code === …\nconf   path",
  },
  {
    line: 12,
    inlay: "term subtotal×(1−rate) · ≥ 0",
    detail:
      "field  total\n  term  order.subtotal * (1 - rate)\n  pred  total ≥ 0          // sidecar number().ge(0)\n  conf  path",
  },
  {
    line: 13,
    inlay: "coupon: string | null",
    detail:
      "field  coupon\n  term  rate>0 ? code : null\n  pred  string ∨ null\n  conf  path",
  },
];

export const contractCode = `import { number, fn, shape, string } from "@nudojs/core";

export const lineTotal = fn(
  { price: number().gt(0), qty: number().ge(1) },
  number().gt(0)
);

export const applyCoupon = fn(
  {
    order: shape({
      subtotal: number().ge(0),
      items: number().ge(0),
    }),
    code: string(),
  },
  shape({
    subtotal: number(),
    items: number(),
    total: number().ge(0),
    coupon: string(),
  })
);`;

/* Draft module format follows service/interface-draft.ts formatDraftModule */
export const draftOutput = `$ npx nudojs contract --draft pricing.js --from calls.js
// @nudo:draft
// Generated by \`nudo contract --draft\` from pricing.js
// This pricing.nudo.draft.js file is NOT loaded as a sidecar contract.
// Review each export, then copy it into pricing.nudo.js to accept.
//
// Evidence: callsite = observed args; body = fields the
// implementation reads (suggestion only — never a check obligation);
// symbolic = generalize; omitted = no evidence.
// Handwritten contracts are never overwritten.

import { fn, number, shape, string } from "@nudojs/core";

// lineTotal — param: callsite, return: symbolic
export const lineTotal = fn(
  { price: number(), qty: number() },
  number()
);

// applyCoupon — param: body, return: body
//   order: /* body reads subtotal, items */
//   code:  /* body reads — suggestion */
export const applyCoupon = fn(
  {
    order: shape({ subtotal: number(), items: number() }),
    code: string(),
  },
  shape({
    subtotal: number(),
    items: number(),
    total: number(),
    coupon: string(),
  })
);`;

export const draftHints: LineHint[] = [
  {
    line: 2,
    inlay: "contract --draft",
    detail:
      "code-first draft from existing JS\nwrites *.nudo.draft.js only with --write\nnever ambient-loads as contract",
  },
  {
    line: 7,
    inlay: "evidence policy",
    detail:
      "callsite → best starting point\nbody    → suggestion only\nomit    → no evidence / TODO\ndraft does NOT invent check obligations",
  },
  {
    line: 15,
    inlay: "param: callsite",
    detail:
      "observed lineTotal(12, 3) projects number()\nnot lit(12) / lit(3) — review may tighten\nreturn symbolic generalize → number()",
  },
  {
    line: 22,
    inlay: "body · suggestion",
    detail:
      "implementation reads order.subtotal / items\ncode.toUpperCase() → string\nsuggestion only — human promotes real obligations",
  },
];

/* Accepted sidecar after review — human-tightened preds */
export const contractHints: LineHint[] = [
  {
    line: 3,
    inlay: "reviewed · price > 0 · qty ≥ 1",
    detail:
      "accepted into pricing.nudo.js\nhuman tightened number() → number().gt(0)\nreturn number().gt(0)\n\ndraft is a starting point — this is the gate",
  },
  {
    line: 8,
    inlay: "reviewed shape",
    detail:
      "promoted body-read fields to obligations\nonly after review — draft never auto-enforces",
  },
  {
    line: 17,
    inlay: "return shape · total ≥ 0",
    detail: "L1 obligations live here after accept",
  },
];

/* Call sites live in their own tab — concrete facts + gate example */
export const callsCode = `// calls.js — call sites (evidence + one bad call)
import { lineTotal, applyCoupon } from "./pricing.js";

lineTotal(12, 3);
applyCoupon({ subtotal: 100, items: 3 }, "VIP10");

// parameter violates sidecar: price > 0
lineTotal(0, 2);`;

export const callsHints: LineHint[] = [
  {
    line: 4,
    inlay: "=> 36  #exact",
    detail:
      "call   lineTotal(12, 3)\nresult 36  #exact\nterm   (price * qty)  where price=12, qty=3\n\nConcrete values appear here — at the call site.",
  },
  {
    line: 5,
    inlay: "total 90 · coupon \"VIP10\"",
    detail:
      "call   applyCoupon({subtotal:100, items:3}, \"VIP10\")\nrate   0.1\ntotal  90\ncoupon \"VIP10\"  #exact",
  },
  {
    line: 8,
    inlay: "⊭ price > 0",
    detail:
      "call     lineTotal(0, 2)\nactual   0  #exact\nexpected price > 0   // sidecar\ngate     nudo:constraint-violated",
  },
];

export const checkOutput = `$ npx nudojs check pricing.js --from calls.js
signatures
  applyCoupon(order: any, code: any) => any
  lineTotal(price: any, qty: any) => any
issues
  [error] lineTotal: actual ⊭ expected  (nudo:constraint-violated)
    call:     lineTotal(0, 2)   // calls.js
    actual:   0  #exact
    expected: price > 0         // pricing.nudo.js`;

export const checkHints: LineHint[] = [
  {
    line: 3,
    inlay: "entry any",
    detail:
      "signatures stay any on entry params\nuntil evidence/refinements say otherwise.\nunknown = inference failed — not this.",
  },
  {
    line: 6,
    inlay: "L1 gate",
    detail:
      "call-site from calls.js ⊭ sidecar pred\nactual ⊭ expected on Abs\nCI: nudo check exits 1",
  },
  {
    line: 9,
    inlay: "price > 0",
    detail: "expected pred from pricing.nudo.js\nalgebraic — not a declared TS type",
  },
];

export const dtsOutput = `$ npx nudojs export pricing.js --format dts
// === applyCoupon TypeScript Declarations ===
/**
 * @param order  - { subtotal: number; items: number }
 * @param code   - string
 * @returns { subtotal: number; items: number;
 *            total: number; coupon: string | null }
 */
export declare function applyCoupon(
  order: { subtotal: number; items: number },
  code: string
): {
  subtotal: number;
  items: number;
  total: number;
  coupon: string | null;
};

// === lineTotal TypeScript Declarations ===
/**
 * @param price - number
 * @param qty   - number
 * @returns number   // sidecar: number().gt(0)
 */
export declare function lineTotal(
  price: number,
  qty: number
): number;`;

export const dtsHints: LineHint[] = [
  {
    line: 8,
    inlay: "abs → .d.ts",
    detail:
      "one-way projection of Abs\nparams widened · return keeps structure\nCI gate remains nudo check",
  },
  {
    line: 21,
    inlay: "abs → .d.ts",
    detail:
      "export declare function lineTotal…\nTS surface is number; Abs/sidecar keep pred > 0\n(check / zod carry the bound)",
  },
];

/* CLI export --format schema writes a ready-to-import zod JS module. */
export const zodOutput = `// nudo export pricing.js --format schema --dialect zod

import { z } from "zod";

export const lineTotalInput = z.object({
  price: z.number().gt(0),
  qty: z.number().gte(1),
});
export const lineTotalOutput = z.number().gt(0);

export const applyCouponInput = z.object({
  order: z.object({
    subtotal: z.number().gte(0),
    items: z.number().gte(0),
  }),
  code: z.string(),
});
export const applyCouponOutput = z.object({
  subtotal: z.number(),
  items: z.number(),
  total: z.number().gte(0),
  coupon: z.string().nullable(),
});`;

export const zodHints: LineHint[] = [
  {
    line: 7,
    inlay: "pred → z.number().gt(0)",
    detail:
      "sidecar number().gt(0)\nprojects to zod bound\n(absToSchemaSource)",
  },
  {
    line: 10,
    inlay: "return → z.number().gt(0)",
    detail:
      "return contract number().gt(0)\n→ z.number().gt(0)\n// matches algebra on entry preds",
  },
  {
    line: 22,
    inlay: "total ≥ 0 → gte(0)",
    detail:
      "sidecar total: number().ge(0)\n→ z.number().gte(0)",
  },
];

export const absObserve = `$ npx nudojs check pricing.js --abs
lineTotal
  price  : number  where price > 0     #path
  qty    : number  where qty ≥ 1       #path
  return : number  where (price * qty) > 0  #path
           // sidecar return number().gt(0)

applyCoupon
  rate   ∈ {0, 0.1, 0.2}               #path
  total  : number  where total ≥ 0     #path
  coupon : string | null                #path`;

export const absObserveHints: LineHint[] = [
  {
    line: 3,
    inlay: "param Abs",
    detail:
      "price — algebraic entry var\npred from sidecar, not a case value",
  },
  {
    line: 6,
    inlay: "return Abs",
    detail: "term (price * qty)\npred derived by arithmetic on entry preds",
  },
  {
    line: 10,
    inlay: "local Abs",
    detail: "path-narrowed rate without binding code to a literal case",
  },
];

/* ── Comparison / feature / list data ─────────────────────────────────────── */

export type BeyondRow = { code: string; ts: string; nudo: string };

export const beyondExamples: BeyondRow[] = [
  { code: `"0x" + id`, ts: "string", nudo: "`0x${string}`" },
  { code: `"hello".slice(1, 3)`, ts: "string", nudo: '"el"' },
  { code: `"a,b,c".split(",")`, ts: "string[]", nudo: '["a", "b", "c"]' },
  { code: `for (let i = 0; i < 5; i++) sum += i`, ts: "number", nudo: "10" },
];

export type AdoptStep = {
  tagId: string;
  tagDefault: string;
  titleId: string;
  titleDefault: string;
  cmd: string;
};

export const adoptSteps: AdoptStep[] = [
  {
    tagId: "homepage.adopt.day0.tag",
    tagDefault: "Logic first",
    titleId: "homepage.adopt.day0.title",
    titleDefault: "Draft contracts",
    cmd: "npx nudojs contract --draft lib.js --from test/",
  },
  {
    tagId: "homepage.adopt.day1.tag",
    tagDefault: "Contracts first",
    titleId: "homepage.adopt.day1.title",
    titleDefault: "Handwrite refine",
    cmd: "lib.nudo.js  ·  @nudo:contract",
  },
  {
    tagId: "homepage.adopt.eco.tag",
    tagDefault: "Same validate",
    titleId: "homepage.adopt.eco.title",
    titleDefault: "check → export",
    cmd: "npx nudojs check src/  ·  export dts|zod|schema",
  },
];

export type TrialStat = { value: string; labelId: string; labelDefault: string };

export const trialStats: TrialStat[] = [
  {
    value: "98.6%",
    labelId: "homepage.trial.stat1",
    labelDefault: "precise signatures on @hapi/hoek",
  },
  {
    value: "0",
    labelId: "homepage.trial.stat2",
    labelDefault: "type annotations you write",
  },
  {
    value: "291 → 0",
    labelId: "homepage.trial.stat3",
    labelDefault: "contract check failures cleared",
  },
];

export type SignatureCard = {
  fn: string;
  evidenceId: string;
  evidenceDefault: string;
  beforeId: string;
  beforeDefault: string;
  after: string;
};

export const signatureCards: SignatureCard[] = [
  {
    fn: "coupon",
    evidenceId: "homepage.trial.card.evidence1",
    evidenceDefault: "from cart.js call site",
    beforeId: "homepage.trial.card.before",
    beforeDefault: "no call-site evidence → any",
    after: '("vip") => "SAVE-VIP"',
  },
  {
    fn: "deepEqual",
    evidenceId: "homepage.trial.card.evidence2",
    evidenceDefault: "from @hapi/hoek usage",
    beforeId: "homepage.trial.card.before",
    beforeDefault: "no call-site evidence → any",
    after: "({a:1,b:{c:2}}, {a:1,b:{c:2}}) => boolean",
  },
  {
    fn: "flatten",
    evidenceId: "homepage.trial.card.evidence3",
    evidenceDefault: "from recursive + loop usage",
    beforeId: "homepage.trial.card.before",
    beforeDefault: "no call-site evidence → any",
    after: "([1,[2,[3,4]]]) => [1,2,3,4]",
  },
];

/** Validate vs. project rail under Work modes. */
export type EcoItem = { title: string; descId: string; descDefault: string };

export const ecoItems: EcoItem[] = [
  {
    title: "nudo check",
    descId: "homepage.eco.check",
    descDefault: "Validation / CI only. Does not generate artifacts.",
  },
  {
    title: "export · dts",
    descId: "homepage.eco.dts",
    descDefault: "`.d.ts` for TypeScript consumers. Lossy projection.",
  },
  {
    title: "export · Zod / guards",
    descId: "homepage.eco.zod",
    descDefault: "Runtime validators from Abs. Not a substitute for `check`.",
  },
  {
    title: "export · Standard Schema",
    descId: "homepage.eco.json",
    descDefault:
      "Standard Schema validators for runtime checks and downstream tooling.",
  },
  {
    title: "IDE / LSP",
    descId: "homepage.eco.ide",
    descDefault: "Hover / inlay read Abs directly.",
  },
  {
    title: "Agent / MCP",
    descId: "homepage.eco.agent",
    descDefault:
      "Coding agents read the same Abs via LSP / MCP — see the AI agents section.",
  },
];

export type AgentCard = {
  titleId: string;
  titleDefault: string;
  descId: string;
  descDefault: string;
  cmd: string;
};

export const agentCards: AgentCard[] = [
  {
    titleId: "homepage.agent.card1.title",
    titleDefault: "Same Abs as the IDE",
    descId: "homepage.agent.card1.desc",
    descDefault:
      "Hover / inlay and agent tools consume Abs directly. `export` projections stay lossy; Abs remains the source of truth.",
    cmd: "npx nudojs check src/ --json",
  },
  {
    titleId: "homepage.agent.card2.title",
    titleDefault: "LSP + MCP surface",
    descId: "homepage.agent.card2.desc",
    descDefault:
      "`@nudojs/lsp` exposes agent `executeCommand` tools. Wire MCP for Cursor, Claude Code, and other agent clients without a separate server protocol.",
    cmd: "@nudojs/lsp · nudo.contract · nudo.whatIf",
  },
  {
    titleId: "homepage.agent.card3.title",
    titleDefault: "Stable product rules",
    descId: "homepage.agent.card3.desc",
    descDefault:
      "Agents must not invent body-AST obligations or treat `@nudo:case` as contracts. Entry `any` ≠ `unknown`. Day 0 is `check`; Day 1 is `contract` + `check`.",
    cmd: "actual ⊭ expected · nudo:constraint-violated",
  },
  {
    titleId: "homepage.agent.card4.title",
    titleDefault: "Agent entrypoint",
    descId: "homepage.agent.card4.desc",
    descDefault:
      "Publish `agents.md` + `llms.txt` so coding agents can set up Nudo without guessing product nouns. Paste the setup block into your agent and go.",
    cmd: "nudojs.github.io/nudo/agents.md",
  },
];

export const agentPaste = `Read https://nudojs.github.io/nudo/docs/reference/agents
Primary gate: npx nudojs check <path>
Contracts are *.nudo.js / @nudo:contract
Do not invent body-AST obligations. @nudo:case is debug-only.
Entry params print as any; unknown = inference failed.`;

export type PathCard = {
  eyebrow: string;
  title: string;
  desc: string;
  to: string;
  cta: string;
};

export const pathCards: PathCard[] = [
  {
    eyebrow: "homepage.paths.card1.eyebrow",
    title: "homepage.paths.card1.title",
    desc: "homepage.paths.card1.desc",
    to: "/docs/getting-started/quick-start",
    cta: "homepage.paths.card1.cta",
  },
  {
    eyebrow: "homepage.paths.card2.eyebrow",
    title: "homepage.paths.card2.title",
    desc: "homepage.paths.card2.desc",
    to: "/docs/guides/vs-typescript",
    cta: "homepage.paths.card2.cta",
  },
  {
    eyebrow: "homepage.paths.card3.eyebrow",
    title: "homepage.paths.card3.title",
    desc: "homepage.paths.card3.desc",
    to: "/docs/guides/migrating-js",
    cta: "homepage.paths.card3.cta",
  },
  {
    eyebrow: "homepage.paths.card4.eyebrow",
    title: "homepage.paths.card4.title",
    desc: "homepage.paths.card4.desc",
    to: "/docs/guides/recipes",
    cta: "homepage.paths.card4.cta",
  },
  {
    eyebrow: "homepage.paths.card5.eyebrow",
    title: "homepage.paths.card5.title",
    desc: "homepage.paths.card5.desc",
    to: "/docs/reference/agents",
    cta: "homepage.paths.card5.cta",
  },
];

/** Command shown in hero copy button and the closing CTA. */
export const heroCmd = "npx nudojs check ./pricing.js";
