import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { rmSync, writeFileSync, mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import nodePath, { join } from "node:path";
import { fileURLToPath } from "node:url";
import { harvestDts, emitEnvModule, type HarvestedEnv } from "../index.ts";

const typesNode = nodePath.resolve(
  nodePath.dirname(fileURLToPath(import.meta.url)),
  "../../../..",
  "node_modules/@types/node",
);

const files = [
  "fs.d.ts",
  "path.d.ts",
  "os.d.ts",
  "buffer.d.ts",
  "buffer.buffer.d.ts",
  "url.d.ts",
  "process.d.ts",
].map((f) => nodePath.join(typesNode, f));

let env: HarvestedEnv;
let code: string;

beforeAll(() => {
  env = harvestDts(files);
  code = emitEnvModule(env, "@types/node");
}, 120_000);

describe("interface augmentation merge (lodash LoDashStatic)", () => {
  it("expands merged interface members from declare module blocks", () => {
    const files = [
      writeTemp(
        "idx.d.ts",
        `export = _;
export as namespace _;
declare const _: _.LoDashStatic;
declare namespace _ {
  interface LoDashStatic {}
}
`,
      ),
      writeTemp(
        "aug.d.ts",
        `declare module "idx" {
  interface LoDashStatic {
    uniq(xs: number[]): number[];
    chunk(xs: number[], n: number): number[][];
  }
}
`,
      ),
    ];
    const env = harvestDts(files);
    const g = env.globals;
    expect(g["uniq"]).toBeDefined();
    expect(g["chunk"]).toBeDefined();
    expect(env.stats.symbols).toBeGreaterThan(2);
  });
});

function writeTemp(name: string, content: string): string {
  const dir = mkdtempSync(join(tmpdir(), "nudo-harvest-aug-"));
  const p = join(dir, name);
  writeFileSync(p, content, "utf-8");
  return p;
}

describe("harvestDts", () => {
  it("registers both node:-prefixed and bare module keys", () => {
    expect(env.modules["node:fs"]).toBeDefined();
    expect(env.modules.fs).toBeDefined();
    expect(env.modules["node:path"]).toBeDefined();
    expect(env.modules.path).toBeDefined();
    expect(env.modules["node:os"]).toBeDefined();
    expect(env.modules.os).toBeDefined();
    // The bare key aliases the same record as its node: twin.
    expect(env.modules.fs).toBe(env.modules["node:fs"]);
  });

  it("maps fs.readFileSync to a function returning union(string, Buffer)", () => {
    const fn = env.modules["node:fs"].readFileSync as any;
    expect(fn.shape.k).toBe("fn");
    const ret = fn.shape.returnType;
    expect(ret).toBeDefined();
    expect(ret.shape.k).toBe("sum");
    const members = ret.shape.members ?? [];
    const hasString = members.some((m: any) => m.shape.k === "prim" && m.shape.type === "string");
    const hasBuffer = members.some((m: any) => m.shape.k === "brand" && m.shape.name === "Buffer");
    expect(hasString).toBe(true);
    expect(hasBuffer).toBe(true);
  });

  it("maps path.join and os.platform", () => {
    expect((env.modules.path.join as any).shape.k).toBe("fn");
    const platform = env.modules.os.platform as any;
    expect(platform.shape.k).toBe("fn");
    const ret = platform.shape.returnType;
    const isString = ret.shape.k === "prim" && ret.shape.type === "string";
    const isStringLiteralUnion = ret.shape.k === "sum" && (ret.shape.members ?? []).length > 0;
    expect(isString || isStringLiteralUnion).toBe(true);
  });

  it("exposes harvest stats and global-block symbols", () => {
    expect(env.stats.files).toBeGreaterThanOrEqual(3);
    expect(env.stats.files).toBe(files.length);
    expect(env.stats.symbols).toBeGreaterThan(50);
    // process.d.ts declares `global { var process: NodeJS.Process; }`.
    expect(env.globals.process).toBeDefined();
    expect(env.globals.process.shape.k).toBe("brand");
  });
});

describe("emitEnvModule", () => {
  const generatedUrl = new URL("./generated-env.tmp.ts", import.meta.url);
  const generatedPath = fileURLToPath(generatedUrl);

  afterAll(() => {
    rmSync(generatedPath, { force: true });
  });

  it("emits importable TS source", () => {
    expect(code).toContain("// Auto-generated by @nudojs/harvester — DO NOT EDIT");
    expect(code).toContain('from "@nudojs/core"');
    expect(code).toContain("export function defineEnv");
    expect(code).toContain("relationFn");
    expect(code).toContain("objOf");
    writeFileSync(generatedPath, code);
  });

  it("emitted module evaluates and defines the env", { timeout: 120_000 }, async () => {
    const mod = await import("./generated-env.tmp.ts");
    const evaluated = mod.defineEnv();
    expect(evaluated.modules.fs).toBeDefined();
    expect(evaluated.modules["node:fs"].readFileSync).toBeDefined();
    expect((evaluated.modules["node:fs"].readFileSync as { shape: { k: string } }).shape.k).toBe("fn");
    expect((evaluated.globals.process as { shape: { k: string } }).shape.k).toBe("brand");
  });
});
