import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { rmSync, writeFileSync } from "node:fs";
import nodePath from "node:path";
import { fileURLToPath } from "node:url";
import { harvestDts, emitEnvModule, type HarvestedEnv } from "../index.ts";

const typesNode = nodePath.resolve(
  nodePath.dirname(fileURLToPath(import.meta.url)),
  "../../../..",
  "node_modules/@types/node",
);

const files = [
  "fs.d.ts",
  "path.d.ts",
  "os.d.ts",
  "buffer.d.ts",
  "buffer.buffer.d.ts",
  "url.d.ts",
  "process.d.ts",
].map((f) => nodePath.join(typesNode, f));

let env: HarvestedEnv;
let code: string;

beforeAll(() => {
  env = harvestDts(files);
  code = emitEnvModule(env, "@types/node");
}, 120_000);

describe("harvestDts", () => {
  it("registers both node:-prefixed and bare module keys", () => {
    expect(env.modules["node:fs"]).toBeDefined();
    expect(env.modules.fs).toBeDefined();
    expect(env.modules["node:path"]).toBeDefined();
    expect(env.modules.path).toBeDefined();
    expect(env.modules["node:os"]).toBeDefined();
    expect(env.modules.os).toBeDefined();
    // The bare key aliases the same record as its node: twin.
    expect(env.modules.fs).toBe(env.modules["node:fs"]);
  });

  it("maps fs.readFileSync to a function returning union(string, Buffer)", () => {
    const fn = env.modules["node:fs"].readFileSync as Record<string, unknown>;
    expect(fn.kind).toBe("function");
    const sig = fn._signature as {
      returnType: { kind: string; members?: Array<{ kind: string; type?: string; className?: string }> };
    };
    expect(sig).toBeDefined();
    expect(sig.returnType.kind).toBe("union");
    const members = sig.returnType.members ?? [];
    const hasString = members.some((m) => m.kind === "primitive" && m.type === "string");
    const hasBuffer = members.some((m) => m.kind === "instance" && m.className === "Buffer");
    expect(hasString).toBe(true);
    expect(hasBuffer).toBe(true);
  });

  it("maps path.join and os.platform", () => {
    expect(env.modules.path.join.kind).toBe("function");
    const platform = env.modules.os.platform as Record<string, unknown>;
    expect(platform.kind).toBe("function");
    const ret = (platform._signature as { returnType: { kind: string; type?: string; members?: unknown[] } })
      .returnType;
    const isString = ret.kind === "primitive" && ret.type === "string";
    const isStringLiteralUnion =
      ret.kind === "union" &&
      (ret.members ?? []).every(
        (m) => (m as { kind: string; value: unknown }).kind === "literal" && typeof (m as { value: unknown }).value === "string",
      );
    expect(isString || isStringLiteralUnion).toBe(true);
  });

  it("exposes harvest stats and global-block symbols", () => {
    expect(env.stats.files).toBeGreaterThanOrEqual(3);
    expect(env.stats.files).toBe(files.length);
    expect(env.stats.symbols).toBeGreaterThan(50);
    // process.d.ts declares `global { var process: NodeJS.Process; }`.
    expect(env.globals.process).toBeDefined();
    expect(env.globals.process.kind).toBe("instance");
  });
});

describe("emitEnvModule", () => {
  const generatedUrl = new URL("./generated-env.tmp.ts", import.meta.url);
  const generatedPath = fileURLToPath(generatedUrl);

  afterAll(() => {
    rmSync(generatedPath, { force: true });
  });

  it("emits importable TS source", () => {
    expect(code).toContain("// Auto-generated by nudo harvest — DO NOT EDIT");
    expect(code).toContain('import { type TypeValue, T } from "@nudojs/core"');
    expect(code).toContain("export function defineEnv");
    expect(code).toContain("T.fnSig");
    expect(code).toContain("T.instanceOf");
    writeFileSync(generatedPath, code);
  });

  it("emitted module evaluates and defines the env", { timeout: 120_000 }, async () => {
    const mod = (await import("./generated-env.tmp.ts")) as {
      defineEnv: () => { globals: Record<string, unknown>; modules: Record<string, Record<string, unknown>> };
    };
    const evaluated = mod.defineEnv();
    expect(evaluated.modules.fs).toBeDefined();
    expect(evaluated.modules["node:fs"].readFileSync).toBeDefined();
    expect((evaluated.modules["node:fs"].readFileSync as { kind: string }).kind).toBe("function");
    expect((evaluated.globals.process as { kind: string }).kind).toBe("instance");
  });
});
